### PR TITLE
Russian language 375k addition

### PR DESCRIPTION
**Pull request by aNOOBisTheGod**
found it in here https://en.wiktionary.org/wiki/Wiktionary:Frequency_lists so some words may not exist, but that will be really small part as I think. Tried to remove bad words but they can still be in there.

### CODE REVIEW

**Comment by aNOOBisTheGod** [comment]
ok will fix it now

**Comment by aNOOBisTheGod** [comment]
bruh
wanted to create another PR for that

**Comment by aNOOBisTheGod** [comment]
ea226212322db148a9d7923ca1717cb9818161a4 - in this commit I've renamed some files so now auto-reloading when you change files while debugging on windows works fine. Before this fix  it didn't work

**Comment by Miodec** [comment]
Why the are the pages renamed?

**Pull request merged**
