### PR TITLE
Add 11 Arabic quotes to arabic.json ➕

### PR DESCRIPTION
**Pull request by MohanadOO**

### CODE REVIEW

**Comment by Miodec** [comment]
Could you please translate the quotes?

**Comment by MohanadOO** [comment]
Yeah sure here is the translation of quotes in a text file 👇

[Arabic Quotes Translation.txt](https://github.com/monkeytypegame/monkeytype/files/9409817/Arabic.Quotes.Translation.txt)
 
**I'm not a Good Translator but I hope the translation deliver the meanings**

**Comment by Miodec** [comment]
Could you just please send it as text instead of a file

**Comment by Miodec** [comment]
Also, the quote length fields are incorrect - please fix

**Comment by MohanadOO** [comment]
> Could you just please send it as text instead of a file

ID: 71
Whoever is stingy with knowledge is afflicted by three: either he dies and his knowledge goes, or he is going to be forgettable, or he accompanies and his works goes away.
من بخل بالعلم ابتلى بثلاث: إما موت فيذهب علمه, إما ينسى, وإما يصحب فيذهب عمله
Abdullah Bin Al Mubarak

ID: 72
He who is patient is just for a while, and he who is very worried can't enjoy.
من صبر فما أقل ما يصبر , ومن جزع فما أقل ما يتمتع
Abdullah Bin Al Mubarak

ID: 73
Muhammad ibn Ali said to his son: O son be careful of laziness and boredom because they are the key to evil actions, if you are lazy you can't perform, and if you are bored you will not be patient with the truth.
وقال محمد بن علي لابنه: يا بنى إياك والكسل والضجر , فأنهما مفتاح كل شر إنك إن كسلت لم تؤد حقا, وإن ضجرت لم تصبر على حق.
Mohammed bin Ali bin Al Hussein bin Ali Abi Talib

ID: 74
If you see a man doing a good deed, know that he has multiple good deeds,  and if you see him doing bad deed, know that he has multiple bad deeds. Good Deeds lead to another, and Bad deeds lead to another.
إذا رأيت الرجل يعمل الحسنة, فاعلم أن لها عنده أخوات, وإذا رأيته يعمل السيئة, فاعلم أن لها عنده أخوات, فإن الحسنة تدل على أختها, وإن السيئة تدل على أختها
Orwa Bin Zubair

ID: 75
He said: It is written in wisdom: Let your word be good and let your face be simple, you will be loved more than people who give gifts.
وقال: مكتوب في الحكمة: لتكن كلمتك طيبة, وليكن وجهك بسطا, تكن أحب إلى الناس ممن يعطيهم العطاء.
Orwa Bin Zubair

ID: 76
Good words are good and better than good words is to use them, and better than using them as rewards, and better than their rewards the satisfaction of those who work for them.
الكلام الحسن حسن وأحسن من الحسن معناه استعماله, وأحسن من استعماله ثوابه, وأحسن من ثوابه رضا من يعمل له.
Yahya ibn Mu'az Al-Razi 

ID: 77
Yahya ibn Mu'az said: The people are three: a man who was occupied by his earning on his pension a man who occupied his pension by his earning, and a man who is occupied by all,  the first being the degree of winners, the second the degree of the lost, and the third the degree of risk-takers.
وقال يحيى بن معاذ: الناس ثلاثة : رجل شغله معاده عن معاشه ورجل شغله معاشه عن معاده, ورجل مشتغل بهما جميعاَ فالأولى درجة الفائزين, والثانية درجة الهالكين, والثالثة درجة المخاطرين.
Yahya ibn Mu'az Al-Razi 

ID: 78
I wondered who grieves for the lack of money and how he did not grieve for the decrease in his age.
عجبت ممن يحزن على نقصان ماله كيف لا يحزن على نقصان عمره.
Yahya ibn Mu'az Al-Razi 

ID: 79
Asceticism has three things: have a little, isolation, and hunger, and he used to say: the hunger of repentance is the experience, the hunger of the ascetics is politics, and the hunger of the two is kindness.
الزهد ثلاثة أشياء: القلة, والخلوة, والجوع, وكان يقول: جوع التوابين تجربة, وجوع الزاهدين سياسة, وجوع الصديقين تكرمة.
Yahya ibn Mu'az Al-Razi 

ID: 80
My son, beware of temptation over inattention, when the call is not answered, there is no way to return, and do not be deceived by the length of well-being, it is a destiny, without it is annihilation, nor after it is existence.
يا بني احذر الصرعة على الغفلة, حين لا تستجاب الدعوة, ولا سبيل إلى رجعة, ولا تغترن بطول العافية, فإنما هو أجل, ليس دونه فناء, ولا بعد أن تستكمله بقاء.
Omar Bin Abd El , Aziz

ID: 81
If you can, be a scientist, if you can't, be a student, if you can't, love them, if you can't, don't hate them.
ان استطعت فكن عالماً, فإن لم تستطع فكن متعلماً, فإن لم تستطع فأحبهم, فإن لم تستطع فلا تبغضهم.
Omar Bin Abd El, Aziz

**Pull request merged**
