### PR TITLE
Orthography and vocabulary changes in Ukrainian language

### PR DESCRIPTION
**Pull request by meleten**
### Description

Closes #

### CODE REVIEW

**Comment by monkeytypegeorge** [comment]
Continuous integration check(s) failed. Please review the failing check's logs and make the necessary changes. https://github.com/monkeytypegame/monkeytype/actions/runs/5402713958

**Comment by Miodec** [comment]
Whats up with 50 thousand line changes?

**Comment by meleten** [comment]
Sorry, what do you mean?

чт, 29 черв. 2023 р. о 13:03 Jack ***@***.***> пише:

**Comment by Miodec** [comment]
image

100k changes in the 50k file. Did you change something with the whitespace?

**Comment by meleten** [comment]
White space is spaces between words, or what? No, I don’t think i did
something to it.

Jack ***@***.***> schrieb am Do. 29. Juni 2023 um 3:57 PM:

**Pull request closed without merging**
