### PR TITLE
Create fightclub.txt

### PR DESCRIPTION
**Pull request by Anu-Ra-g**
### Description

Closes #

### CODE REVIEW

**Review by rizwanmustafa — CHANGES_REQUESTED** [review]
What are you trying to achieve here? From my best guess you are trying to add a quote from the movie "Fight Club" but you aren't following the correct syntax. You need to add this quote in the `english.json` file in the `quotes` folder

**Comment by Anu-Ra-g** [comment]
Do I need to add it by making a quotes folder or just the JSON file in the quotes folder ?

**Comment by rizwanmustafa** [comment]
> Do I need to add it by making a quotes folder or just add the JSON file in the quotes folder ?

Please take a look at this page. https://github.com/monkeytypegame/monkeytype/blob/master/QUOTES.md

**Comment by Miodec** [comment]
As rizwan said, please follow the step by step guide and open another pr

**Pull request closed without merging**
