### PR TITLE
fix(russian 375k): delete unwanted (mb6ockatf)

### PR DESCRIPTION
**Pull request by mb6ockatf**
hello, it's me [again](https://github.com/monkeytypegame/monkeytype/pull/4997)

### Description

- removed "sex", "genitalia", "penis", "vagina", "ass" related words -- not mentioning them here
- элай -- company name¿
- фокеев -- surname
- фоксфорд -- online courses company name
- фокс -- transliterated "fox"
- removed ["гельминт"](https://en.wikipedia.org/wiki/Parasitic_worm)
- елдак -- literally informal word for "dick"
- еити -- abbreviation for scientific organisation
- ["жид"](https://en.wikipedia.org/wiki/Zhyd) -- antisemitic slur
- гидроцефалия -- hydrocephalus (speedtyping disease names, fr)
- ёпрст -- euphemism
- адюльтер -- adultery
- адыгея -- republic name
- перемога -- [here](https://en.wiktionary.org/wiki/%D0%BF%D0%B5%D1%80%D0%B5%D0%BC%D0%BE%D0%B3%D0%B0)
- хохол -- [ethnic slur](https://en.wikipedia.org/wiki/Oseledets#Khokhol)
- жидобандеровцев -- combined: antisemitic slur + calling someone a nazist
- чуркобес -- combined: racistic clur against mid-asians + devil (uttely offensive)
- зашквар -- criminal slang
- зашмонают -- criminal slang
- заэс -- abbreviation for one nuclear power plant
- збс -- something like "cool af", cuss + slang
- монтенегро -- transliterated Montenegro (in russian its called Черногория [BlackMountains])
- залупа -- [this](https://en.wikipedia.org/wiki/Glans_penis)
- бездарь -- "having-zero-talants", offensive
- бейби -- transliterated "baby"
- заднеприводный -- slur for passive homosexual ("back-driven", also applies for cars")
- кончать -- to ejaculate
- презерватив -- condom
- анус -- asshole
- зануси -- name of a company which no more exists
- побухать -- informal for "go drink a lot", go get drunk for fun
- бухлишко -- informal for "alcohool"
- быдло -- slur, means "animals"
- быдлокод -- code, written by быдло (slur, too)
- чувак -- argot, [fenya](https://en.wikipedia.org/wiki/Fenya)... philologists claim it derived from gypsies' "whore"
- фаллоимитатор -- dildo
- фаллос -- phallus
- фюрер -- fuhrer
- хентай -- hentai
- этти -- erotic anime genre

after googling, removed some words that have 0 meanings (literally just random letters)

### Checks

- [ ] Adding quotes?
  - [ ] Make sure to include translations for the quotes in the description (or another comment) so we can verify their content.
- [ ] Adding a language or a theme?
  - [ ] If is a language, did you edit `_list.json`, `_groups.json` and add `languages.json`?
  - [ ] If is a theme, did you add the theme.css?
    - Also please add a screenshot of the theme, it would be extra awesome if you do so!
- [ ] Check if any open issues are related to this PR; if so, be sure to tag them below.
- [ ] Make sure the PR title follows the Conventional Commits standard. (https://www.conventionalcommits.org for more info)
- [ ] Make sure to include your GitHub username inside parentheses at the end of the PR title

Closes #

### CODE REVIEW

**Comment by Miodec** [comment]
Thanks

**Comment by RatzattaK** [comment]
Some (maybe even most) of the removed words are legit and make sense in the right context.

> заднеприводный -- slur for passive homosexual

"Заднеприводный" literally means "Задний привод" (Rear-wheel drive transmission layout). It's like removing the word "scum" just because it can refer to an immoral person in a bad way. 

> кончать -- to ejaculate

The literary definition is "bring something to an end; complete, finish". Also applies to similar removed words.

> чувак -- argot, [fenya](https://en.wikipedia.org/wiki/Fenya)... philologists claim it derived from gypsies' "whore"

"Чувак" means just "dude" and that why most people use this definition of the word.
Again, just because the word _can_ be considered "bad" doesn't mean that it always does.

Some mentioned words (condom, phallus, ejaculate...) even appear in the [english_25k.json](https://github.com/monkeytypegame/monkeytype/blob/0715352c5a91924f3ca19dae851ee23b64eb50cc/frontend/static/languages/english_25k.json#L22817) which makes this MR even more strange.

Consider reviewing these changes please, this is some heavily based opinion of the original author.

**Comment by mb6ockatf** [comment]
@RatzattaK Thanks for you reply

чувак has a controversial origin, as I stated. I do not thing that leaving a word that some people can consider inappropriate for some reason is a good idea. More to the point, it is -- with no doubt -- informal language. There are enough words in russian vocabulary which are completely neutral and not considered "informal" or something like that.

I apologise for removing words connected to topic of sex. I erroneously assumed that such topics are usually being avoided and it would be a good idea to remove these words, completely missing the fact that those could be considered medical terms.

My honest purpose was to make the set of words in russian 375k usable, like previous #4997, by removing controversial words which can be misinterpreted or some non-existent words. I am sorry it went that way

Hovewer, I still reckon my PR was somewhat useful in terms of removing unnecessary slang (no "nigger" even in english 450k), non-russian vocabulary & stuff.

Which words you think should be returned, among the ones already been mentioned?

**Comment by mb6ockatf** [comment]
@RatzattaK checked it, usage of sexualised language (or imagery) is against code of conduct. Suppose it is not suitable here

**Pull request merged**
