### PR TITLE
feat(sounds): add `fist fight` and `rubber keys` (Absalon43)

### PR DESCRIPTION
**Pull request by Absalon43**
### Description

Added two new sound fonts 

### Checks

- [ ] Adding quotes?
  - [ ] Make sure to include translations for the quotes in the description (or another comment) so we can verify their content.
- [ ] Adding a language or a theme?
  - [ ] If is a language, did you edit `_list.json`, `_groups.json` and add `languages.json`?
  - [ ] If is a theme, did you add the theme.css?
    - Also please add a screenshot of the theme, it would be extra awesome if you do so!
- [x] Check if any open issues are related to this PR; if so, be sure to tag them below.
- [x] Make sure the PR title follows the Conventional Commits standard. (https://www.conventionalcommits.org for more info)
- [x] Make sure to include your GitHub username inside parentheses at the end of the PR title

Closes #

### CODE REVIEW

**Comment by monkeytypegeorge** [comment]
Continuous integration check(s) failed. Please review the failing check's logs and make the necessary changes. https://github.com/monkeytypegame/monkeytype/actions/runs/7715281063

**Comment by monkeytypegeorge** [comment]
Continuous integration check(s) failed. Please review the failing check's logs and make the necessary changes. https://github.com/monkeytypegame/monkeytype/actions/runs/7718537768

**Comment by Miodec** [comment]
There is loads of "empty space" in the new error sound, I would trim it down to make it more responsive.

image


Also, im still unsure about the "plastic toy" name...

**Comment by Absalon43** [comment]
All should be in order now

**Review by Miodec — APPROVED** [review]
Thanks

**Pull request merged**
