### PR TITLE
Create latin.json

### PR DESCRIPTION
**Pull request by TheEccentricDuck**
I would like to make Latin quotes an option, as I greatly appreciate Latin literature.

### Description

Closes #

### CODE REVIEW

**Comment by Miodec** [comment]
I think it would be good to start with a few more quotes

**Comment by TheEccentricDuck** [comment]
No problem, I will get back to you on that.

在 2023-01-04 21:24:53，Jack ***@***.***> 写道：


I think it would be good to start with a few more quotes

**Comment by TheEccentricDuck** [comment]
Hello Miodec, I think for now all the quotes will have to be brief proverbs (for the purposes of mass-generation through code) and I think longer quotes will have to just be added in the future and submitted by users.

**Comment by Miodec** [comment]
Another PR added latin quotes. If you wish to add more quotes please expand that file

**Pull request closed without merging**
