### PR TITLE
impr(test config): allow keyboard navigation (@Truiteseche)

### PR DESCRIPTION
**Pull request by Truiteseche**
### Description
Improve keyboard navigation accessibility on the test-config section, improve semantic.

Maybe the fact that we were not able to focus textButtons with the keyboard was on purpose but I think it's more relevant to allow it, especially since in mobile layout it is focusable. I also sometimes accidentally log out because the log out button is just before the text field in the tabindex hierarchy, so it would resolve that small but annoying issue.

impr(test-config section): impossible to navigate with the keyboard in the test-config section (@Truiteseche)

Related issues (doesn't fix it at all):
#4857

### CODE REVIEW

**Comment by Miodec** [comment]
Focused elements should use the outline to indicate focus. I know it would require a lot more changes than this (you would need to remove variable padding on the button to avoid outline misalignment) - do you want me to do this or do you wanna give it a try?

**Comment by Truiteseche** [comment]
Thank you for your feedback! Indeed I kicked the outline in favor of the same effect as on hover, because the outline was glitched, but yeah it would be better with the outline. I'd like to give it a try even though I don't fully understand what you mean removing **variable** padding** .

**Comment by Miodec** [comment]
> Thank you for your feedback! Indeed I kicked the outline in favor of the same effect as on hover, because the outline was glitched, but yeah it would be better with the outline. I'd like to give it a try even though I don't fully understand what you mean removing **variable padding**.

By variable padding i mean this 
image
image

**Comment by Truiteseche** [comment]
Thank you very much! I put the outline back in place, as you advised me I removed the variable padding (in favor of the variable margin) to avoid the outline misalignment, and I removed `overflow: hidden` on some containers to avoid the outline display problems On my side, it's ready to merge.

**Comment by Miodec** [comment]
Nicely done, thanks.

**Pull request merged**
