### PR TITLE
Added two french quotes

### PR DESCRIPTION
**Pull request by Felixbstck**
### Description

Added two french quotes (id 131-132)

### CODE REVIEW

**Comment by Miodec** [comment]
Please resolve conflicts

**Comment by Felixbstck** [comment]
Conflicts have been resolved

**Comment by Miodec** [comment]
Please don't change IDs of existing quotes (as this would break things like quote ratings and reports) Modify the new quote IDs instead.

**Comment by Felixbstck** [comment]
My bad it's my first pull request I modified the ids

**Review by Miodec — APPROVED** [review]

**Pull request merged**
