### PR TITLE
Improve word highlight UI in input history

### PR DESCRIPTION
**Pull request by ademirkan**
### Problem
* Mouse blocks wpm speed while hovering words in input history
monkeytype-wpm-bad

### Solution
* Moved wpm speed above word so that it is not blocked by mouse
* Changed color to sub-alt, cleaner imo
monkeytype-wpm-good

### Notes
* Changed .wordInputAfter to .wordInputHighlight base class, added .wordInputHighlight--WithSpeed, which can be omitted for highlights not using speed
* Here is the only other time .wordInputAfter was being used. As you can see, it is working perfectly
monkeytype-multi-highlight

### CODE REVIEW

**Comment by Miodec** [comment]
Ooooorrrrr.... we could keep the speed below the word but make the cursor invisible when hovering over a word? What do you think?

**Comment by ademirkan** [comment]
> Ooooorrrrr.... we could keep the speed below the word but make the cursor invisible when hovering over a word? What do you think?

**Comment by Miodec** [comment]
@ademirkan why close the PR?

**Comment by ademirkan** [comment]
> @ademirkan why close the PR?

oof, misclick. Was trying to close the reply.

**Comment by ademirkan** [comment]
how can I open it back up?

**Comment by ademirkan** [comment]
> Ooooorrrrr.... we could keep the speed below the word but make the cursor invisible when hovering over a word? What do you think?

This is what I first tested out. It looked good and solved the problem but it felt jank to me personally. If you append cursor:none to .word in inspect element, you can see what it would look/feel like. If you feel that it makes more sense, I can make the changes

**Comment by Miodec** [comment]
It miiight be a tiny bit confusing at first, but it definitely improves the readability of the word and speed with absolutely nothing in the way.

**Comment by ademirkan** [comment]
Sure, I can give it a go. Do you want to keep the speed color change from bg to sub-alt?

**Comment by Miodec** [comment]
Yeah, keep that

**Comment by ademirkan** [comment]
Also, thanks for the css feedback :) I knew my naming was jank but I didn't know the Sass way to fix it.

**Comment by Miodec** [comment]
Thanks

**Pull request merged**
