### PR TITLE
feat(lang): added language option portuguese_5k (acalanato)

### PR DESCRIPTION
**Pull request by acalanato**
### Description

feat(lang): Added portuguese_8k to languages

  - [x] If is a language, did you edit `_list.json`, `_groups.json` and add `languages.json`?

### CODE REVIEW

**Comment by monkeytypegeorge** [comment]
Continuous integration check(s) failed. Please review the failing check's logs and make the necessary changes. https://github.com/monkeytypegame/monkeytype/actions/runs/9307245976

**Comment by monkeytypegeorge** [comment]
Continuous integration check(s) failed. Please review the failing check's logs and make the necessary changes. https://github.com/monkeytypegame/monkeytype/actions/runs/9308783151

**Comment by Miodec** [comment]
Why "short"? Why not just the usual top 8k most used words?

**Comment by acalanato** [comment]
Because the source file had more than 200k words, i striped words with more than 6 characters. The longer words can have as much as 20 characters. I was about to include them but its rather silly to have words like "descongestionaremos". I can rename the file, no problem.

**Comment by acalanato** [comment]
Sure, i didn't verify words by usage as i have no means to verify that. I just stripped words between 2 and 6 characters and removed words that go against the rules manually. Sorry if i misinterpreted you, i thought you asked because there was a conformity problem with the name.

**Comment by Miodec** [comment]
Personally I dont see much sense in including a list thats just short words (the words filter option is available if you only want to include short words). I would rather add something like top 10k most common words, then let the user filter it down if they wish to.

**Comment by acalanato** [comment]
Interesting, i didn't know about this feature! Even tho i looked for it.
To explain further, the original idea was to extend the word lists as this one have much more words than existing ones, limit to shorter word was just a criteria i chose without much consideration. I decided to expand the list because i keep stumbling across the same words in my language while English had much more variety. So, i'll try and do as you said, i'll look for most used words and include them.

**Comment by monkeytypegeorge** [comment]
Continuous integration check(s) failed. Please review the failing check's logs and make the necessary changes. https://github.com/monkeytypegame/monkeytype/actions/runs/9454243331

**Comment by acalanato** [comment]
Done,
ditched previous word list in favor of top most used words according to dicio.com.br.
If there is anything else i can do to improve, please let me know.

**Review by Miodec — APPROVED** [review]
Thanks

**Comment by acalanato** [comment]
Thank you for merging, i learned a lot throughout the process.

**Pull request merged**
