### PR TITLE
feat(languages): add Occitan 200, 1k, 2k, 5k, 10k (Mejans)

### PR DESCRIPTION
**Pull request by Mejans**
### Description

This PR adds the files for Occitan language

### CODE REVIEW

**Comment by monkeytypegeorge** [comment]
Continuous integration check(s) failed. Please review the failing check's logs and make the necessary changes. https://github.com/monkeytypegame/monkeytype/actions/runs/9877405164

**Comment by Mejans** [comment]
@Miodec Hello! How to resolve issues?

**Comment by Augustin68** [comment]
> @Miodec Hello! How to resolve issues?

If you click on the bot link you will see the pipeline error:
image

I think you missnamed your languages. The name property in the json should be the same as your file.
Exemple, for occitan_1k, the name in the json should be occitan_1k

**Comment by Mejans** [comment]
@Augustin68 Hello! Many thanks, I've just applied the changes, the CI looks happy now.
I hope this PR is okay now ✌️

**Comment by Miodec** [comment]
Thanks

**Pull request merged**
