### PR TITLE
impr(profile): add level percentage when hovering over progress bar (vjgtigers)

### PR DESCRIPTION
**Pull request by vjgtigers**
### Description

Added code so when the users mouse hovers over the progress bar the percent complete of that level is displayed

Also:
    added "data-balloon-pos="up""  so that the total user xp on profile view will new appear

Closes #

pull [#5269]
messed up the branch when changing and couldn't fix it

on account and profile view page:

Screenshot 2024-04-02 220658

on profile view page:

Screenshot 2024-04-02 220744

### CODE REVIEW

**Comment by monkeytypegeorge** [comment]
Continuous integration check(s) failed. Please review the failing check's logs and make the necessary changes. https://github.com/monkeytypegame/monkeytype/actions/runs/8532204264

**Comment by Miodec** [comment]
From the screenshots it looks like the vertical alignment is off. Please try to fix it.

**Comment by Miodec** [comment]
I broke the PR somehow.... Can you hard reset to the "update styling a tiny bit" commit, then force push?

**Comment by vjgtigers** [comment]
_**Should**_ be working again

**Comment by Miodec** [comment]
Thanks

**Pull request merged**
