### PR TITLE
New Theme : iv

### PR DESCRIPTION
**Pull request by riyuzenn**
## New theme based on the [iv palette](https://github.com/riyuzenn/iv)

<div>
    <h4><a href="https://monkeytype.com?customTheme=WyIjZDRkNGQ0IiwiI2EwYTBhMCIsIiM4ZDhkOGQiLCIjMzUzNTM1IiwiI2VkZWRlZCIsIiMzYjJkM2IiLCIjOTM3MTczIiwiIzk4NzY3OCIsIiNhZDhkNjAiLCIjYjc5NzZhIl0=">iv : clover (light mode)</a></h4>
    <a href="https://monkeytype.com?customTheme=WyIjZDRkNGQ0IiwiI2EwYTBhMCIsIiM4ZDhkOGQiLCIjMzUzNTM1IiwiI2VkZWRlZCIsIiMzYjJkM2IiLCIjOTM3MTczIiwiIzk4NzY3OCIsIiNhZDhkNjAiLCIjYjc5NzZhIl0="></a>

<h4 align="right"><a href="https://monkeytype.com?customTheme=WyIjMGMwYzBjIiwiI2EwYTBhMCIsIiNiZWJlYmUiLCIjNDA0MDQwIiwiIzEyMTIxMiIsIiNkY2NlZGMiLCIjOWQ3YjdkIiwiI2E3ODU4NyIsIiNiNzk3NmEiLCIjYzFhMTc0Il0=">iv : spade (dark mode)</a></h4>
    <a href="https://monkeytype.com?customTheme=WyIjMGMwYzBjIiwiI2EwYTBhMCIsIiNiZWJlYmUiLCIjNDA0MDQwIiwiIzEyMTIxMiIsIiNkY2NlZGMiLCIjOWQ3YjdkIiwiI2E3ODU4NyIsIiNiNzk3NmEiLCIjYzFhMTc0Il0="></a>

</div>

<h3><a href="https://github.com/riyuzenn/iv/">Color Palette Used</a></h3>
<a href="https://github.com/riyuzenn/iv/"></a>

### CODE REVIEW

**Review by rizwanmustafa — CHANGES_REQUESTED** [review]
The  iv_spade theme looks extremely similar to `dark` theme on the website. Please choose a different color scheme

**Comment by Miodec** [comment]
And the light version looks similar to `paper`

**Comment by riyuzenn** [comment]
## New iv_spade  

image

## New iv_clover  

image

**Comment by Miodec** [comment]
The new dark theme is similar to `olivia`.

**Comment by riyuzenn** [comment]
## updated iv spade
should I change the main color to something else?

image

**Comment by Miodec** [comment]
I wouldn't say its enough. I think i can only merge the light one

**Comment by riyuzenn** [comment]
how about this one?
image

**Comment by Miodec** [comment]
Fine, we can do that one

**Pull request merged**
