### PR TITLE
Added Oromo language

### PR DESCRIPTION
**Pull request by turinaf**
### Description

Closes #

### CODE REVIEW

**Comment by turinaf** [comment]
> I can see a lot of words with dots and capital letters. Please fix.
@Miodec 
Some words have apostrophe in Oromo language (like har'a which means today), should they be removed too? It seems no punctuation is allowed in monkeytype.

**Comment by Miodec** [comment]
> > I can see a lot of words with dots and capital letters. Please fix.
> > @Miodec
> > Some words have apostrophe in Oromo language (like har'a which means today), should they be removed too? It seems no punctuation is allowed in monkeytype.

Keep them, ill remove them during test initialisation if punctuation mode is disabled.

**Comment by Miodec** [comment]
I see a lot of \u characters in words.

**Comment by turinaf** [comment]
> I see a lot of \u characters in words. Please fix.

@Miodec that's apostrophe being represented as "\u2019" in json file.  I used dump function of json python library to create json file. Let me try adding more arguments to dump function to represent it as it is and also improve the readability. 
image

**Comment by Miodec** [comment]
One more duplicate was found in the 5k list

**Comment by Miodec** [comment]
Thanks

**Pull request merged**
