### PR TITLE
Add REAL name to canary layout

### PR DESCRIPTION
**Pull request by j-fosstvedt**
### Description
Added "(hotdog)" to the end of canary layouts

### CODE REVIEW

**Comment by Miodec** [comment]
Explain?

**Comment by j-fosstvedt** [comment]
Everyone wants it to be named hotdog, except semi. (And maybe some others). Would be funny if it was also in monkeytype

**Comment by Miodec** [comment]
Ill close this one for now because changing the layout could cause some weird things if people have it currently active

**Pull request closed without merging**
