### PR TITLE
docs: made the the PR template more informative

### PR DESCRIPTION
**Pull request by aikooo7**
### Description

As the title says, I saw the pull request template and thought it was a little bit small, so I added more content to it.

### CODE REVIEW

**Comment by Miodec** [comment]
I think if we are going to add this checks section, we might aswell just convert all/most comments to another check.

**Comment by Miodec** [comment]
Actually, nevermind - the checkboxes don't fully make sense here because they will appear as text anyway

image

Im not sure if we should use only checkboxes or only comments.

**Comment by aikooo7** [comment]
> Actually, nevermind - the checkboxes don't fully make sense here because they will appear as text anyway

Aren't they clickable? I thinked so and already some some that were, I will probably need to find it

**Comment by aikooo7** [comment]
> Im not sure if we should use only checkboxes or only comments.

Well by experience most people ignore comments xD, with checkboxes we can also be sure they saw it

**Comment by aikooo7** [comment]
> I think if we are going to add this checks section, we might aswell just convert all/most comments to another check.

I could do it if you want to, but I don't think is a good idea in my opinion.

Maybe some specific comment but all/mosts comments no.

**Comment by Miodec** [comment]
Alright, lets move the language and themes comments into the checks section then

**Comment by aikooo7** [comment]
My bad, for the long time gone, what you mean by comments on languages and themes? Where are they?

**Comment by Miodec** [comment]
> My bad, for the long time gone, what you mean by comments on languages and themes? Where are they?

The very first comment, the one mentioning themes or languages.

**Comment by aikooo7** [comment]
Want to apologize a lot for the time delay, I did completely forget this pull request.

**Comment by aikooo7** [comment]
@Miodec do I need to do anything else or is it normal?

**Comment by aikooo7** [comment]
> > > My bad, for the long time gone, what you mean by comments on languages and themes? Where are they?
> > 
> > 
> > The very first comment, the one mentioning themes or languages.
> 
> Still waiting on this.

Wasn't what I added in 5c6ae71 what you asked for?

**Comment by Miodec** [comment]
> > > > My bad, for the long time gone, what you mean by comments on languages and themes? Where are they?
> > > 
> > > 
> > > The very first comment, the one mentioning themes or languages.
> > 
> > 
> > Still waiting on this.
> 
> Wasn't what I added in [5c6ae71](https://github.com/monkeytypegame/monkeytype/commit/5c6ae71b86aad85447e97237a2891e5b874208a7) what you asked for?

Hmmm, i might have missed it actually. Left a comment though.

**Comment by aikooo7** [comment]
> > > > > My bad, for the long time gone, what you mean by comments on languages and themes? Where are they?
> > > > 
> > > > 
> > > > The very first comment, the one mentioning themes or languages.
> > > 
> > > 
> > > Still waiting on this.
> > 
> > 
> > Wasn't what I added in [5c6ae71](https://github.com/monkeytypegame/monkeytype/commit/5c6ae71b86aad85447e97237a2891e5b874208a7) what you asked for?
> 
> Hmmm, i might have missed it actually. Left a comment though.

It's done, give me your opinion in anything else

**Review by Miodec — APPROVED** [review]

**Comment by Miodec** [comment]
Thanks

**Pull request merged**
