### PR TITLE
fix: set correct delimiter and digits for bangla (shahnewaz-labib)

### LINKED ISSUE #4696: Delimiter Problem in Bengali Language
### Did you clear cache before opening an issue?

- [X] I have cleared my cache

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Does the issue happen when logged in?

Yes

### Does the issue happen when logged out?

Yes

### Does the issue happen in incognito mode when logged in?

Yes

### Does the issue happen in incognito mode when logged out?

Yes

### Account name

mmcrjx

### Account config

_No response_

### Current Behavior

In the Bangla language, the sentence delimiter is '।' however '.' shows up in the text. I think this is just an issue of the input text, a simple regex should fix this. Eg s%/./।/gc

### Expected Behavior

When I open up to type the sentenses are delimited by . instead of ।

### Steps To Reproduce
1. Open [Monkeytype.com](https://monkeytype.com/)
2. Change typing language to Bangla
3. Turn on punctuation

### Environment

- OS: ubuntu 22.04
- Browser: firefox
- Browser Version: 117.0.1 (64-bit)

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by shahnewaz-labib**
### Description
* There's no "." (period) in bangla, instead there's "।". Simply doing a regex match and replacing the period with the appropriate character. It was already implemented for Nepali language.

* For latin numerals, converting them to proper bangla numerals

#### Current deployment
* Notice the english numerals and periods
image
#### After changes
* Notice the "।"s (no periods) and bangla numerals
image

### Checks

- [ ] Adding quotes?
  - [ ] Make sure to include translations for the quotes in the description (or another comment) so we can verify their content.
- [ ] Adding a language or a theme?
  - [ ] If is a language, did you edit `_list.json`, `_groups.json` and add `languages.json`?
  - [ ] If is a theme, did you add the theme.css?
    - Also please add a screenshot of the theme, it would be extra awesome if you do so!
- [x] Check if any open issues are related to this PR; if so, be sure to tag them below.
- [x] Make sure the PR title follows the Conventional Commits standard. (https://www.conventionalcommits.org for more info)
- [x] Make sure to include your GitHub username inside parentheses at the end of the PR title

Closes #4696

### CODE REVIEW

**Review by ruru-m07 — APPROVED** [review]

**Comment by shahnewaz-labib** [comment]
@ruru-m07 Is there anything blocking the merge?

**Review by ruru-m07 — COMMENTED** [review]
looks every thing ok...

**Review by ruru-m07 — APPROVED** [review]

**Comment by Miodec** [comment]
Please resolve conflicts.

**Comment by shahnewaz-labib** [comment]
@Miodec resolved.

**Review by Miodec — APPROVED** [review]
Thanks

**Pull request merged**
