### PR TITLE
added Georgian quotes

### PR DESCRIPTION
**Pull request by avetisovi**
PS. translations aren't 100% accurate and even may not grammatically correct, but they represent core meaning:

16) It isn't a cat, to take and hang; whatever it is, it's the spirit of God, human.

17) The people, who were in a state of despair a moment ago, were now cheering and cheering. The mass of people broke up, dispersed and spread across the field. Everyone went home fully satisfied that they had seen this disgraceful and heart-wrenching game. Peter looked around and saw that no one was staying here. The army also left, only two guards remained near gallows. That red-shirted man also changed into some other clothes and left. The unfortunate child was left hanging motionless.

18) Only here ended the funeral march in four parts, which included the southern sun, the sadness of Tbilisi, the horn of a car, the noise of a propeller, the roar of a Paris coffee house, the slow rustle of Chinese silk, the boundless respect of Bromley, the envious smile of Tino, the slithering of a snake on a woman's flawless body, a secret spell and all This was surrounded by the roar of the spirit warrior Shalva. Ramino's quiet smile and the voiceless, elderly chirping, crying and sometimes speaking of her aunt, who was raised in a remote village in Georgia...

19) The bookworm, who was constantly bored, cold and obsessed with the fate of the country, gradually got her out of habit to music, singing, dancing, singing; To her madness, the laughter of love and the joy of life. As time went by, Teimuraz also got deeper and deeper into public affairs and books, day by day, he became like a bookworm and he didn't even notice Margo's heart becoming engrossed, conditioned and spiritually orphaned.

20) When Teimuraz's life bent his neck to the ground and bent him to the ground, the bent scribe also took his hand to his books - those books, which for Teimuraz were comparable to the children and were more necessary and precious than furniture, family treasures, Margot's precious stones, crockery and bed linen.

21) Yes, yes! - she heard Jacko's funny laugh, - Jacko knows that.

22) Speaking wisely is pure silver, but silence - gold

23) - Are you killing me, father? - He came to Bekina. - Are you killing me? Are you putting a knife in my throat?.. Why are you sacrificing me?!

### CODE REVIEW

**Comment by Miodec** [comment]
> 16. It isn't a cat, to take and hang; whatever it is, it's the spirit of God, human.

Remove

> 23. * Are you killing me, father? - He came to Bekina. - Are you killing me? Are you putting a knife in my throat?.. Why are you sacrificing me?!

Remove

**Comment by avetisovi** [comment]
> > 16. It isn't a cat, to take and hang; whatever it is, it's the spirit of God, human.
> 
> Remove
> 
> > 23. * Are you killing me, father? - He came to Bekina. - Are you killing me? Are you putting a knife in my throat?.. Why are you sacrificing me?!
> 
> Remove

Can I leave 23th? It's not about actually killing, but one man overreacts to his fathers decision to marry.

**Comment by Miodec** [comment]
Nothing in the quote actually mentions anything about marriage, so in its current state, it can't stay.

**Comment by avetisovi** [comment]
> Nothing in the quote actually mentions anything about marriage, so in its current state, it can't stay.

"We died" is standard Georgian phrase which is used during panic and hard time. If someone who knows language reads it he will understand that. But if it's forbidden anyway, I'll delete it.

**Pull request merged**
