### PR TITLE
impr(quotes): add Spanish quotes (KANGRIZ)

### PR DESCRIPTION
**Pull request by KANGRIZ**
Added Spanish quotes, ID 148 to 150 (3 in total).
Comes from all different authors/sources.

**Quotes Added (integrity checks)**

1. Sabía muy bien que aparte de los grandes planetas como la Tierra, Júpiter, Marte, Venus, a los cuales se les ha dado nombre, existen otros centenares de ellos tan pequeños a veces, que es difícil distinguirlos aún con la ayuda del telescopio. Cuando un astrónomo descubre uno de estos planetas, le da por nombre un número. Le llama, por ejemplo, "el asteroide 3251". Tengo poderosas razones para creer que el planeta del cual venía el principito era el asteroide B612. Este asteroide ha sido visto sólo una vez con el telescopio en 1909, por un astrónomo turco. Este astrónomo hizo una gran demostración de su descubrimiento en un congreso Internacional de Astronomía. Pero nadie le creyó a causa de su manera de vestir. Las personas mayores son así. Felizmente, para la reputación del asteroide B 612, un dictador turco impuso a su pueblo, bajo pena de muerte, el vestido a la europea. Entonces el astrónomo volvió a dar cuenta de su descubrimiento en 1920 y como lucía un traje muy elegante, todo el mundo aceptó su demostración.

2. Por mucho que lo intentes, por mucho que te esfuerces, es posible que todo salga mal. De hecho, es probable que la mayor parte de las cosas que creías que iban a salir de una manera, salgan de otra. Porque la realidad va su aire. No puedes gobernarla tanto como crees.

3. Este es mi gusto, no un buen gusto, no un mal gusto, pero sí mi gusto, del cual no me avergüenzo ni lo oculto. Este es mi camino, ¿dónde está el suyo?  

**Translation:**

1. He knew very well that apart from the great planets such as the Earth, Jupiter, Mars, Venus, to which names have been given, there are hundreds of others so small at times that it is difficult to distinguish them even with the aid of the telescope. When an astronomer discovers one of these planets, he names it with a number. He calls it, for example, "asteroid 3251". I have strong reasons to believe that the planet from which the little prince came was asteroid B612. This asteroid has been seen only once with the telescope in 1909, by a Turkish astronomer. This astronomer made a great demonstration of his discovery at an International Astronomy Congress. But nobody believed him because of the way he was dressed. Old people are like that. Fortunately, for the reputation of asteroid B 612, a Turkish dictator imposed on his people, under penalty of death, the European-style dress. Then the astronomer returned to give an account of his discovery in 1920 and as he was wearing a very elegant suit, everyone accepted his demonstration.

2. No matter how hard you try, no matter how hard you try, it is possible for everything to go wrong. In fact, most of the things you thought were going to go one way are likely to go another way. Because reality goes its own way. You can't rule it as much as you think you can.

3. This is my taste, not a good taste, not a bad taste, but my taste, of which I am not ashamed nor do I hide it. This is my way, where is yours?

**evidence screenshot**

Screenshot_1

### Checks

- [ ] Adding a language or a theme?
    - [ ] If is a language, did you edit `_list.json`, `_groups.json` and add `languages.json`?
    - [ ] If is a theme, did you add the theme.css?
        - Also please add a screenshot of the theme, it would be extra awesome if you do so!
- [ ] Check if any open issues are related to this PR; if so, be sure to tag them below.
- [x] Make sure the PR title follows the Conventional Commits standard. (https://www.conventionalcommits.org for more info)
- [x] Make sure to include your GitHub username inside round brackets at the end of the PR title

### CODE REVIEW

**Comment by monkeytypegeorge** [comment]
Continuous integration check(s) failed. Please review the failing check's logs and make the necessary changes. https://github.com/monkeytypegame/monkeytype/actions/runs/7146437798

**Comment by monkeytypegeorge** [comment]
Continuous integration check(s) failed. Please review the failing check's logs and make the necessary changes. https://github.com/monkeytypegame/monkeytype/actions/runs/7146499918

**Comment by KANGRIZ** [comment]
I added 2 commits to correct two errors, but I forgot to put the title:

1. Removed a "," at the end of the document.
2. Corrected an incorrect character size (1033 to 1031).

**Comment by Miodec** [comment]
I think i would remove the first quote - it doesn't seem very "quotable".

**Comment by monkeytypegeorge** [comment]
Continuous integration check(s) failed. Please review the failing check's logs and make the necessary changes. https://github.com/monkeytypegame/monkeytype/actions/runs/7182955656

**Comment by KANGRIZ** [comment]
I removed the first note (id:148) and replaced it with this one:

Las personas mayores me aconsejaron abandonar el dibujo de serpientes
boas, ya fueran abiertas o cerradas, y poner más interés en la geografía, la
historia, el cálculo y la gramática. De esta manera a la edad de seis años
abandoné una magnífica carrera de pintor. Había quedado desilusionado por el
fracaso de mis dibujos número 1 y número 2. Las personas mayores nunca
pueden comprender algo por sí solas y es muy aburrido para los niños tener
que darles una y otra vez explicaciones.

**Translation**

Older people advised me to abandon drawing boa snakes, whether open or closed, and to put more interest in geography, history, calculus and grammar. Thus at the age of six I gave up a magnificent career as a painter. I had been disillusioned by the failure of my drawings number 1 and number 2. Older people can never understand anything on their own and it is very boring for children to have to give them over and over again explanations. to give them explanations over and over again.


Screenshot_1

**Comment by Miodec** [comment]
Sorry, but the new quote also seems quite weird and random.

**Comment by KANGRIZ** [comment]
> Sorry, but the new quote also seems quite weird and random.

**I have already deleted it**

**Review by Miodec — APPROVED** [review]

**Comment by Miodec** [comment]
Thanks

**Pull request merged**
