### PR TITLE
feat: add tokyo night theme

### PR DESCRIPTION
**Pull request by rendi12345678**
### Checks

- [ ] Adding quotes?
  - [ ] Make sure to include translations for the quotes in the description (or another comment) so we can verify their content.
- [x] Adding a language or a theme?
  - [ ] If is a language, did you edit `_list.json`, `_groups.json` and add `languages.json`?
  - [x] If is a theme, did you add the theme.css?
    - Also please add a screenshot of the theme, it would be extra awesome if you do so!
- [ ] Check if any open issues are related to this PR; if so, be sure to tag them below.
- [x] Make sure the PR title follows the Conventional Commits standard. (https://www.conventionalcommits.org for more info)
- [ ] Make sure to include your GitHub username inside parentheses at the end of the PR title

Closes #

### CODE REVIEW

**Comment by rendi12345678** [comment]
screenshot-20240727-091409Z-all
screenshot-20240727-091402Z-all
screenshot-20240727-091347Z-all

**Comment by rendi12345678** [comment]
screenshot-20240727-091223Z-all

**Comment by Miodec** [comment]
Sorry, looks simmilar to other themes already available.

**Comment by rendi12345678** [comment]
wow thanks for reviewed my PR, okey peace

**Pull request closed without merging**
