### PR TITLE
docs: provide a miscellaneous issue template

### PR DESCRIPTION
**Pull request by Panquesito7**
### Description

- Provide a miscellaneous issue template.
  - I believe this is very important as there's only one issue template which is the bug report template. In case someone else wants to report an issue, the only template they have is the bug report template, which is very limited in my opinion.

### CODE REVIEW

**Comment by Miodec** [comment]
> In case someone else wants to report an issue

So... a bug report?

**Comment by Panquesito7** [comment]
> > In case someone else wants to report an issue
> 
> So... a bug report?

Nope, not a bug report, it can be other types of issues such as making improvements to the docs, which isn't a bug report in any way.

**Comment by Miodec** [comment]
Ah, well in that case - years ago i made the decision to isolate actual bugs and todo's to issues, and have everything else like suggestions and feedback come through github discussions, discord channels and emails. I found it much easier to manage and understand what needs to be done.

**Comment by Panquesito7** [comment]
> Ah, well in that case - years ago i made the decision to isolate actual bugs and todo's to issues, and have everything else like suggestions and feedback come through github discussions, discord channels and emails. I found it much easier to manage and understand what needs to be done.

I see. Would it be better to create a feature request template instead?

**Comment by Miodec** [comment]
> > Ah, well in that case - years ago i made the decision to isolate actual bugs and todo's to issues, and have everything else like suggestions and feedback come through github discussions, discord channels and emails. I found it much easier to manage and understand what needs to be done.
> 
> I see. Would it be better to create a feature request template instead?

As already mentioned - feature requests should be sent through github discussions, discord feedback channel or email.

**Comment by Panquesito7** [comment]
> > > Ah, well in that case - years ago i made the decision to isolate actual bugs and todo's to issues, and have everything else like suggestions and feedback come through github discussions, discord channels and emails. I found it much easier to manage and understand what needs to be done.
> > 
> > 
> > I see. Would it be better to create a feature request template instead?
> 
> As already mentioned - feature requests should be sent through github discussions, discord feedback channel or email.

Alrighty. I guess I should close this PR, then.

**Pull request closed without merging**
