### PR TITLE
Added new english quotes

### PR DESCRIPTION
**Pull request by vitiligo610**
### Description

The changes made in my PR were the following:
- Added English quotes from ID 6819 to 6854 in the `english.json` file.
- Fixed a quote length error that was causing an issue in a previously [closed PR](https://github.com/monkeytypegame/monkeytype/pull/4146).
- Fixed a unique ID error that was affecting the quotes in the `english.json` file.

Closes #

### CODE REVIEW

**Comment by Miodec** [comment]
The PR says youve modified 40k lines. Did you convert the indentation in the file or something?

**Comment by vitiligo610** [comment]
Maybe, the indentation might have been changed because of prettier.

**Comment by Miodec** [comment]
> Perhaps the indentation was changed due to Prettier.

Prettier exists specifically so diffs like this *don't* happen. Looks like rerunning it brought the diff back down to reasonable levels.

**Comment by vitiligo610** [comment]
So, should I now open another PR with correct indentation?

**Pull request closed without merging**
