### PR TITLE
feat: Input history heatmap is add the new speed unit setting

### LINKED ISSUE #4531: Input history heatmap is not using the new speed unit setting

### PR DESCRIPTION
**Pull request by ridemountainpig**
### Description
Input history heatmap is add the new speed unit setting

wpm:

https://github.com/monkeytypegame/monkeytype/assets/92412722/03525c64-0543-4fc5-aeec-696cef589781

cpm:

https://github.com/monkeytypegame/monkeytype/assets/92412722/defc05c4-594c-4711-a5e7-8ee39a93aed5

wps:

https://github.com/monkeytypegame/monkeytype/assets/92412722/ccff5c0c-e590-46e0-864b-120f9e410573

cps:

https://github.com/monkeytypegame/monkeytype/assets/92412722/fee0261e-ec9f-4594-bb08-0302f9424846

Closes #4531

### CODE REVIEW

**Comment by monkeytypegeorge** [comment]
Continuous integration check(s) failed. Please review the failing check's logs and make the necessary changes. https://github.com/monkeytypegame/monkeytype/actions/runs/5857943401

**Comment by monkeytypegeorge** [comment]
Continuous integration check(s) failed. Please review the failing check's logs and make the necessary changes. https://github.com/monkeytypegame/monkeytype/actions/runs/5858197283

**Comment by monkeytypegeorge** [comment]
Continuous integration check(s) failed. Please review the failing check's logs and make the necessary changes. https://github.com/monkeytypegame/monkeytype/actions/runs/5858229072

**Comment by monkeytypegeorge** [comment]
Continuous integration check(s) failed. Please review the failing check's logs and make the necessary changes. https://github.com/monkeytypegame/monkeytype/actions/runs/5858288254

**Comment by Miodec** [comment]
Why close the pr?

**Comment by ridemountainpig** [comment]
> Why close the pr?

There seem have preittier check problem in this pr, so i reopen the new one #4542.

**Pull request closed without merging**
