### PR TITLE
impr(quotes): Add English quotes (@TheFrenchTechMan)

### PR DESCRIPTION
**Pull request by TheFrenchTechMan**
### Description

Added some quotes to the English file.

### Checks

- [x] Adding quotes?
  - [X] Make sure to include translations for the quotes in the description (or another comment) so we can verify their content.
- [X] Adding a language or a theme?
  - [X] If is a language, did you edit `_list.json`, `_groups.json` and add `languages.json`?
  - [X] If is a theme, did you add the theme.css?
    - Also please add a screenshot of the theme, it would be extra awesome if you do so!
- [X] Check if any open issues are related to this PR; if so, be sure to tag them below.
- [x] Make sure the PR title follows the Conventional Commits standard. (https://www.conventionalcommits.org for more info)
- [X] Make sure to include your GitHub username prefixed with @ inside parentheses at the end of the PR title.

### CODE REVIEW

**Comment by Miodec** [comment]
Please remove the last one.

**Comment by TheFrenchTechMan** [comment]
Is it because of the wrong ID or for something else?

**Comment by Miodec** [comment]
I don't really like its content, IDs seem fine.

**Comment by TheFrenchTechMan** [comment]
It should be removed...?

**Comment by TheFrenchTechMan** [comment]
I think it can be merged now.

**Review by Miodec — APPROVED** [review]
Thanks

**Comment by TheFrenchTechMan** [comment]
The checks failed because in one of the quotes there are quotation marks, and backslashes to include them correctly, but they are being counted by the auto checker thing.

**Comment by Miodec** [comment]
> The checks failed because in one of the quotes there are quotation marks, and backslashes to include them correctly, but they are being counted by the auto checker thing.

Then you need to update the length property to what the continous integration script is saying it should be.

**Comment by TheFrenchTechMan** [comment]
Ok, now it should be good.

**Comment by TheFrenchTechMan** [comment]
I'm going insane

**Comment by TheFrenchTechMan** [comment]
You can review the changes now

**Comment by TheFrenchTechMan** [comment]
@Miodec?

**Review by Miodec — APPROVED** [review]
Thanks

**Pull request merged**
