### PR TITLE
feat(themes): add Indigo theme (geoffdavis92)

### PR DESCRIPTION
**Pull request by geoffdavis92**
### Description

Added theme for [GMK Indigo](https://geekhack.org/index.php?topic=114461.0).

#### Main page
Main Monkeytype page with Indigo theme

#### Flip Mode
Monkeytype Indigo theme during test in Flip mode

#### Test with Errors
Monkeytype Indigo theme during test with errors

### Checks

- [x] Adding a language or a theme?
    - [ ] If is a language, did you edit `_list.json`, `_groups.json` and add `languages.json`?
    - [x] If is a theme, did you add the theme.css?
        - Also please add a screenshot of the theme, it would be extra awesome if you do so!
- [x] Check if any open issues are related to this PR; if so, be sure to tag them below.
- [x] Make sure the PR title follows the Conventional Commits standard. (https://www.conventionalcommits.org for more info)
- [x] Make sure to include your GitHub username inside round brackets at the end of the PR title

### CODE REVIEW

**Comment by Miodec** [comment]
Im not sure i like this theme. Plus, where did this dark purple come form? Looking at the keycap set that color is nowhere to be found.

**Comment by geoffdavis92** [comment]
> Plus, where did this dark purple come form? Looking at the keycap set that color is nowhere to be found.

The dark purple is [RAL 5000/"Violet blue"](https://ralcolor.com/#:~:text=RAL%205000), which is listed under the [keycap specifications GMK CYL Indigo](https://spaceholdings.net/products/gmk-cyl-indigo-keycaps?variant=44048871719170).

**Comment by Miodec** [comment]
Idk, this purple looks nothing like the image here
image

**Comment by Miodec** [comment]
Well, looking at the actual keyset image, it looks like it looks simmilar to other blue themes that are already available - I dont think ill merge this one in sorry. Don't forget you can use the custom theme setting to create your own theme.

**Pull request closed without merging**
