### PR TITLE
impr(quotes): add 2 russian quotes (NipulM)

### PR DESCRIPTION
**Pull request by NipulM**
Translation of the first quote by -> Stanisław Jerzy Lec (Станислав Ежи Лец):
- "Learning is always useful, even if it doesn't always bring benefits."
- "Учиться всегда полезно, даже если не всегда приносит пользу."

Translation of the second quote by -> Arthur Schopenhauer (Артур Шопенгауэр):
- "Politeness is a silent agreement to ignore and not emphasize the moral and intellectual poverty in each other."
- "Вежливость - это молчаливое соглашение игнорировать и не подчёркивать друг в друге моральную и умственную нищету."

### CODE REVIEW

**Comment by Miodec** [comment]
Whats up with the random protuguese quote?

**Comment by NipulM** [comment]
> Whats up with the random protuguese quote?

This commit was made a few days ago. I'm not sure why it's appearing here.

**Comment by Miodec** [comment]
> > Whats up with the random protuguese quote?
> 
> This commit was made a few days ago. I'm not sure why it's appearing here.

Oh wait i know where it came from - dont worry about it.

**Comment by Miodec** [comment]
> > > > Whats up with the random protuguese quote?
> > > 
> > > 
> > > This commit was made a few days ago. I'm not sure why it's appearing here.
> > 
> > 
> > Oh wait i know where it came from - dont worry about it.
> 
> Ah, I've already deleted that file. Will that be a problem?

Yeah lol, If i merge this now it would completely remove portuguese quotes.

**Comment by Miodec** [comment]
Alright

**Pull request closed without merging**
