### PR TITLE
added indonesian quote

### PR DESCRIPTION
**Pull request by Faris0520**
### Description

Added some indonesian quotes

Closes #

### CODE REVIEW

**Comment by rizwanmustafa** [comment]
Can you please provide a translation of these quotes. Thanks

**Comment by Faris0520** [comment]
- The day will come when all will be judged with scales made of fire and water. (it means like 'yaum al hisaab')

- Humans are stupid. But humans are also changeable creatures.

**Comment by rizwanmustafa** [comment]
> * The day will come when all will be judged with scales made of fire and water. (it means like 'yaum al hisaab')

I don't think Miodec will approve this quote because it references relegious beliefs but I am not sure.

**Comment by Faris0520** [comment]
oh ok, sorry

**Comment by Faris0520** [comment]
Updated.

**Pull request merged**
