### PR TITLE
fix: ctrl+backspace replay bug (ashinberish)

### PR DESCRIPTION
**Pull request by ashinberish**
### Checks

- [ ] Adding quotes?
  - [ ] Make sure to include translations for the quotes in the description (or another comment) so we can verify their content.
- [ ] Adding a language or a theme?
  - [ ] If is a language, did you edit `_list.json`, `_groups.json` and add `languages.json`?
  - [ ] If is a theme, did you add the theme.css?
    - Also please add a screenshot of the theme, it would be extra awesome if you do so!
- [x] Check if any open issues are related to this PR; if so, be sure to tag them below.
- [x]  Make sure the PR title follows the Conventional Commits standard. (https://www.conventionalcommits.org for more info)
- [x] Make sure to include your GitHub username inside parentheses at the end of the PR title

Closes #

### CODE REVIEW

**Review by FFUV — CHANGES_REQUESTED** [review]
The inconsistency lies in how the code handles deletion positions. Specifically, it sets the position to delete from differently based on the direction, causing potential issues when the word is empty.

**Review by FFUV — CHANGES_REQUESTED** [review]
ADD const keyStroke = (event?.originalEvent || {}) as InputEvent;
if (keyStroke.inputType === "deleteWordBackward") {
  Replay.addReplayEvent("setLetterIndex", 0); // Letter index will be 0 on CTRL + Backspace Event
} else {
  Replay.addReplayEvent("setLetterIndex", currTestInput.length - 1);
}

instead

**Comment by ashinberish** [comment]
But this condition will always true
image

**Comment by FFUV** [comment]
> But this condition will always be true image

hm alright then the code seems good to me

**Review by FFUV — APPROVED** [review]
Lets Gamble, Try Merging

**Review by fehmer — APPROVED** [review]

**Pull request merged**
