### PR TITLE
impr(quotes): add english quote (daa)

### PR DESCRIPTION
**Pull request by deftasparagusanaconda**
cool quote from danny devito

my first PR!! pls approve

### CODE REVIEW

**Comment by fehmer** [comment]
There is something wrong with your PR, it shows   38,542 additions and  38,536 deletions.

**Comment by deftasparagusanaconda** [comment]
Thats the no. of rows of the entire english.json in frontend/static/quotes. I copied all lines over to a text editor, appended a new quote, and copied the new text into the "edit file" page

**Comment by fehmer** [comment]
your commit should only contain the added lines. Maybe only use the online editor on github if you are unfamiliar with git.

**Comment by deftasparagusanaconda** [comment]
hmmm.. not sure how to get it to show "6 additions" correctly. Do I need to revert all changes and start over?
Also, i cant open the file in github's online editor, the file is too large

**Comment by fehmer** [comment]
You'll need to start over. You can try the https://github.dev/deftasparagusanaconda/monkeytypequotecontrib/blob/master/frontend/static/quotes/english.json editor. If this is not working for you you have to clone the repository to your computer, do the changes locally and push them.

If you don't know how to do that please search for a tutorial online.

**Comment by deftasparagusanaconda** [comment]
did as recommended. did not know how to change branch of PR so i made a new PR

**Pull request closed without merging**
