### PR TITLE
added uzbek_70k words

### PR DESCRIPTION
**Pull request by ShaakhDev**
I have collected 76000+ Uzbek words and I am happy to contribute for monkeytype.

### CODE REVIEW

**Review by code-alt — APPROVED** [review]

**Comment by ShaakhDev** [comment]
@Miodec please review my PR.

**Comment by Miodec** [comment]
Please revert the whitespace changes in list and group files.

**Comment by ShaakhDev** [comment]
@Miodec done

**Review by Miodec — APPROVED** [review]
Thanks

**Pull request merged**
