### PR TITLE
impr(language): rework malay (kopipahit-1)

### PR DESCRIPTION
**Pull request by kopipahit-1**
Fixed malay.json because certain words in there is not in Bahasa Malaysia

### CODE REVIEW

**Comment by monkeytypegeorge** [comment]
Continuous integration check(s) failed. Please review the failing check's logs and make the necessary changes. https://github.com/monkeytypegame/monkeytype/actions/runs/6074282960

**Comment by monkeytypegeorge** [comment]
Continuous integration check(s) failed. Please review the failing check's logs and make the necessary changes. https://github.com/monkeytypegame/monkeytype/actions/runs/6074282960

**Comment by Shuja-Mahmood** [comment]
Since it is a fix for malay words list it should only edit the `malay.json` file.

**Review by kopipahit-1 — COMMENTED** [review]
Deleted unnecessary file.

**Comment by monkeytypegeorge** [comment]
Continuous integration check(s) failed. Please review the failing check's logs and make the necessary changes. https://github.com/monkeytypegame/monkeytype/actions/runs/6083258095

**Review by kopipahit-1 — COMMENTED** [review]
Updated. Thank you.

**Review by Shuja-Mahmood — APPROVED** [review]

**Pull request merged**
