### PR TITLE
Add Hack Nerd Font.

### PR DESCRIPTION
**Pull request by ojas-bhagavath**
I use the Hack Nerd Font with the custom fonts option in monkeytype, and I think it looks cool, so I have added Hack Nerd Font.

### CODE REVIEW

**Comment by refact0r** [comment]
Why Hack Nerd Font instead of the normal Hack font? Nerd Font symbols and icons don't really serve a purpose in Monkeytype and using the original font would be less confusing.

**Comment by ojas-bhagavath** [comment]
Noted, will add Hack font itself.

**Comment by ojas-bhagavath** [comment]
> Why Hack Nerd Font instead of the normal Hack font? Nerd Font symbols and icons don't really serve a purpose in Monkeytype and using the original font would be less confusing.

But there are differences between these two fonts, aesthetically, for example '0' in the Hack Nerd Font has a dot in the middle, and Hack Font has a line instead.

**Comment by Miodec** [comment]
Thanks

**Pull request merged**
