### PR TITLE
Quotes in Ukrainian

### PR DESCRIPTION
**Pull request by mellangr**
### Description

Added quotes in Ukrainian from literature, films, quotes of several figures

Closes #

### CODE REVIEW

**Comment by mellangr** [comment]
> Hi there! Please provide a translation of all the quotes.

I'm a newbie, sorry if I did something wrong! Here is the translation:

```
{
  "text": "Okay, Murph, if you're talking about science, don't say you're afraid of ghosts. Go deeper, find out the facts, analyze, look for what and how... and then show the conclusions.",
  "source": "Cooper — Interstellar",
  "length": 155,
  "id": 21
},
{
  "text": "When you came to us, your mother told me one thing that I still cannot understand. She said: "From now on, we are only memories for our children.","source": "Cooper — Interstellar",
  "length": 139,
  "id": 22
},
{
  "text": "Who knows, maybe love is not an invention of mankind, but a force. And one of the most powerful. It has a meaning and purpose... Maybe love is some kind of proof that there is a higher, unexplored dimension in the universe. Therefore, something and pulls me to a man I haven't seen in 10 years, who may no longer be alive. Love is the only force we know that transcends time and space. Maybe we should trust it, even if we can't even fathom it yet. ",
  "source": "Amelia Brand — Interstellar",
  "length": 413,
  "id": 23
},
{
  "text": "Do not listen to the darkness in the midnight day, let your fire burn at the end of the day. So that the light of the night will not be disgraced. Let the wise men stop fighting, because their words will not pierce the fog. Do not listen to the darkness in the midnight day. So that the light of the night don't give it to shame.",
  "source": "Dylan Thomas",
  "length": 247,
  "id": 24
},
{
  "text": "Donald: This world doesn't suit you, does it, Coup? Cooper: And what's wrong with thinking I was born for this flight? And that makes me happy. No, I don't see it as a crime. Donald: Who knows. I've never believed in good intentions. Consequences are the most important thing. Cooper: That's the most important thing, yes. We farmers sit like this every year when it rains and say, ``This is the year.'' But next year won't save us and the one behind him, too. Earth is a treasure, Donald, but she's asking to leave it. We were born on Earth, but we don't have to die on it.",
  "source": "Interstellar",
  "length": 511,
  "id": 25
},
{
  "text": "The path of the righteous is difficult, because he is hindered by selfishness and tyrants from evil people. Blessed is the shepherd who, in the name of mercy and kindness, leads the weak through the valley of darkness, because he is the one who truly cares for his neighbor , and brings back children who have gone astray. And I will take cruel revenge on them with fierce punishments on those who plan to poison and harm my brothers, and you will know that my name is the Lord, when my vengeance falls on you.",
  "source": "Jules - Pulp Fiction",
  "length": 448,
  "id": 26
},
{
  "text": "Vincent: Do you know what they call a quarter-pound cheeseburger in Paris? Jules: What, they don't call it a quarter-pound cheeseburger? Vincent: They have a metric system there. They don't even understand what a quarter pound is. Jules: And what do they call it? Vincent: They call it a "Royal Cheeseburger". Jules: A "Royal Cheeseburger"? And what do they call a "Big Mac" then? Vincent: A "Big Mac" is a \ "Big Mac", only they call it "Le Big Mac"."source": "Pulp Fiction",
  "length": 428,
  "id": 27
},
{
  "text": "Jules: We had to get shotguns. Vincent: How many? Jules: Three or four. Vincent: Including our guy? Jules: Not sure. Vincent: So there could be five or more? Jules: Maybe. Vincent: Should have taken the damn shotguns.",
  "source": "Pulp Fiction",
  "length": 244,
  "id": 28
},
{
  "text": "Vincent: You know what they put on French fries instead of ketchup over there in France? Jules: What? Vincent: Mayonnaise! Jules: Fuck it! Vincent: I've seen them do it myself. They just put that shit on everything !",
  "source": "Pulp Fiction",
  "length": 202,
  "id": 29
},
{
  "text": "Fabian: Whose motorcycle is that? Butch: It's not a motorcycle, it's a chopper, honey. Fabian: And whose chopper is that? Butch: Zed. Fabian: Where's Zed? Butch: Zed's dead, baby. Zed's dead.",
  "source": "Pulp Fiction",
  "length": 158,
  "id": 30
},
{
  "text": "Mia: Do you hate it too? Vincent: Hate what? Mia: Awkward silence. Why do people have to make up some nonsense to feel good about themselves? Vincent: I don't know. Good question. Mia: Only then do you understand , who found a truly special person when you can just shut up for a minute and enjoy the silence with him...",
  "source": "Pulp Fiction",
  "length": 350,
  "id": 31
},
{
  "text": "Dreams seem real as long as you are dreaming. Is that right? Only when you wake up do you realize that it was actually just a dream. Think about it - you never know when exactly a dream begins, you always find yourself right in the center of events.",
  "source": "Cobb - The Beginning",
  "length": 227,
  "id": 32
},
{
  "text": "I watched John play with this machine and suddenly realized - the Terminator will never stop. He will never leave John, will never harm him. He will never snap at a boy, get drunk and hit him. He will always find time for him. He would always be there. And he would die protecting him. Of all the possible fathers that had come and gone over the years, this robot was the only one who could actually replace him. In a crazy world, it was the smartest choice.",
  "source": "Sarah Connor - Terminator",
  "length": 465,
  "id": 33
},
{
  "text": "For a husband must do good, be generous in his estate for rewards, so that his people fight in return, good men, when war is raging, do their service - glorious because all actions give wealth to the husband.",
  "source": "Beowulf (trans. Elena O'Lear)",
  "length": 196,
  "id": 34
},
{
  "text": "That is a formidable demon, called Grendel, an infamous vagrant who took wastelands, swamps and swamps for himself. A monster of relatives, he cowered in their lair, wretched, since they were judged by God to be outcasts - the tribe of Cain - this is the Ancient One's retribution for Abel - Cain's murder.",
  "source": "Beowulf (trans. Elena O'Lear)",
  "length": 264,
  "id": 35
},
{
  "text": "At night, Grendel rushed to explore the circle of the high house, whether the Danes-mailers, drunk with beer, stopped at the chats. He sees - inside the noble men according to the account rested, not knowing sorrow, human misfortune. A merciless manifestation, the spawn of evil, angry and predatory , immediately daring, pulled thirty warriors from the field, - happy with the meal, dragging the rich booty home, fed up with the murder, moved to the den.",
  "source": "Beowulf (trans. Elena O'Lear)",
  "length": 384,
  "id": 36
},
{
  "text": "Vealgteov came out, Grotgar's wife, vigilant in politeness; she greeted, all in gold, in the hall of husbands and, a worthy wife, gave a glass to the deputy of the land of the Eastern Danes to the first, called the beloved people to enjoy themselves with a feast. He gladly took part, victorious, in the account is hoppy. The wife of the Helming family carried the precious goblet around the group of heroes and youth in turn, until the time came for her to give Beowulf - in high spirit, adorned with a ring - a goblet of honey. She congratulates her husband, with a wise word she thanks God that the desired has come true, that in salvation from the atrocities, you can blame her on someone now. He, a mad warrior, accepted the cup from the Vealgteov and led the thing, zealous for battle, - said Beowulf, whose father Ejteov: \"I decided when I set out on the sea, getting into the boat, - and my people with me - that I will fully fulfill the people of Denmark's desire - or I would fall dead, crushed by the enemy. I have to perform the act bravely - or in the halls of honey these sknit, until I meet the skin". It was a word to listen to love, the praise of the Geat; the queen sat down, noble, all in gold, next to her husband-lord.","source": "Beowulf (trans. Elena O'Lear)",
  "length": 1031,
  "id": 37
},
{
  "text": "After these words, for the second time the torn snake, an ominous terror, moved, fiery, towards the enemies, the hated people. The flame flowed in waves, the shield burned to the core, the chain mail was strong enough to help the young warrior, and the young man fearlessly ran over his shield kinsman, just destroyed by his own flame.",
  "source": "Beowulf (trans. Elena O'Lear)",
  "length": 300,
  "id": 38
},
{
  "text": "He lay there, a huge golden-red dragon, fast asleep; rumblings and billows of smoke rose from his mouth and nostrils, but flames slumbered in his womb. Under his belly, under all his limbs and his massive ringed tail and in general, everywhere around, on the entire invisible floor, there were innumerable piles of jewels, gold articles and just gold in bars, gems and gems, and the shaft glittered crimson in the reddish light.",
  "source": "J.R.R. Tolkien - The Hobbit, or There and There",
  "length": 453,
  "id": 39
},
{
  "text": "The matrix is a system. The system is our enemy. But when you are in it - look who you see? Businessmen, teachers, lawyers, carpenters, ordinary people whose minds we save. However, as long as they are part of the system, they are all our enemies. You have to remember that most people are not ready to accept reality, and some are so poisoned and so hopelessly dependent on the system that they will fight for it.",
  "source": "Morpheus - The Matrix",
  "length": 387,
  "id": 40
},
{
  "text": "I felt a great fluctuation of power, as if a million voices simultaneously screamed in terror, and then suddenly fell silent. I'm afraid something terrible has happened.""source": "Obi-Wan Kenobi - Star Wars",
  "length": 139,
  "id": 41
},
{
  "text": "If you see that the city government is acting inefficiently, that it is corrupt - do not stand aside! Be active, go to power yourself to fundamentally change the situation. As they say: if you want a place under the sun - create your own sun! Modern politicians are \"humus\" for the youth, on which it should later blossom and bear fruit. So the student body should take power into its own hands - it is quite possible.",
  "source": "Andriy Sadovy",
  "length": 388,
  "id": 42
},
{
  "text": "In my opinion, the worst thing is when a school builds its work on intimidation, violence and artificially created authorities. Such an education system destroys the healthy feelings and immediacy of schoolchildren, kills their faith in their own strength. This is how humiliated loyal subjects are created.",
  "source": "Albert Einstein",
  "length": 254,
  "id": 43
},
{
  "text": "Nature shows us only the tail of a lion. But I have no doubt that this lion exists, although due to its enormous size it cannot appear immediately in its entirety.",
  "source": "Albert Einstein",
  "length": 149,
  "id": 44
},
{
  "text": "As long as a mathematical law reflects real reality, it is inaccurate; as soon as a mathematical law is accurate, it does not reflect real reality.",
  "source": "Albert Einstein",
  "length": 141,
  "id": 45
},
{
  "text": "It was of course a lie what you read about my religious beliefs and it is systematically repeated. I do not believe in a personified God, and I have never denied it, on the contrary I have made it clear. If anything in me can be called religious yes, this is an unlimited fascination with the structure of the universe, up to the limit to which science can reveal it.",
  "source": "Albert Einstein",
  "length": 343,
  "id": 46
},
{
  "text": "The most beautiful thing we can experience is the feeling of mystery. It is the source of all true art and science. He who has never experienced this feeling, who does not know how to stop and think, is seized by a fearful fascination, is like a dead body, that his eyes are closed. Insight into the mysteries of life, combined with fear, also gave impetus to the development of religion. To know whether there really exists for us something unknowable in the manifestation of higher wisdom and radiant beauty, which our primitive faculties can only comprehend in the most primitive forms is knowledge and this is the basis of true religiosity. In this and only this sense I belong to the number of religious people.",
  "source": "Albert Einstein",
  "length": 678,
  "id": 47
}
```

**Comment by Miodec** [comment]
Quotes 25 and 42 have incorrect length fields. Please fix.

**Comment by mellangr** [comment]
I see my mistakes. Did I understand correctly? I have to close this pull request, correct the mistakes and make another new pull request?

**Comment by mellangr** [comment]
Thank you for your help. I think I fixed the errors

**Review by rizwanmustafa — APPROVED** [review]
LGTM!

**Pull request merged**
