### PR TITLE
add ukrainian quotes

### PR DESCRIPTION
**Pull request by deni-kon**
### Translations aren't 100% accurate and some are definitely grammatically incorrect, but they represent core meaning though.
1. There is no science without books, no enlightenment without science, and without enlightenment - all misery. - Ivan Franko
2. Life without freedom, without the right to self-determination - is the life of a soul on a hook. - Lesya Ukrainka
3. A person's work determines their value. - Taras Shevchenko
4. One should live for the state and die for it. - Bohdan Khmelnytsky
5. One for all, and all for one. - Petro Sagaidachny
6. Courage makes victory possible. - Andriy Meleshko
7. A person lives as long as the memory of them lives in the hearts of others. - Vasyl Sukhomlynsky
8. Success always begins with a dream. - Olena Pchilka
9. Not only great deeds, but also small actions can change the world. - Hryhoriy Skovoroda
10. Education is the light that illuminates the dark paths of our lives. - Mykhailo Hrushevsky
11. Strength lies not in the sword, but in the spirit that holds the sword. - Yaroslav the Wise
12. Nothing happens twice, and everything that happens - forever. - Yuri Andrukhovych
13. True love is a moment of inspiration that can last an eternity. - Oleksandr Dovzhenko
14. With love for our people, we must raise our children. - Lina Kostenko
15. A person who does not take risks will never achieve success. - Volodymyr Vynnychenko
16. The ability to forgive is a great strength of the spirit. - Marko Vovchok
17. You will take with you only what you have shared with others. - Ostap Vyshnia
18. Freedom is when you understand that the responsibility for your life belongs to you. - Pavlo Tychyna
19. Laughter is the best medicine for the soul. - Yevhen Hutsalo
20. Happiness is the ability to rejoice in small things. - Valerian Pidmohylny
21. It is the heart that leads us to true happiness, not the mind. - Ivan Bahrianyi
22. Good deeds should be reflected in the heart, notin the wallet. - Mykola Gogol
23. Life is too short not to do what you love. - Oleksandr Ivanovych Kuprin
24. Words have great power, but only the heart can understand them. - Vasyl Stus
25. Real success lies in overcoming your fears. - Andriy Kuzmenko
26. Creativity is a journey into the unknown, where you can find inspiration. - Oleg Lysheha
27. Every moment is a priceless gift that we should cherish. - Oksana Zabuzhko
28. Happiness is when your desires coincide with your abilities. - Anatoliy Dimarov
29. Love for one's homeland is a source of inspiration and strength. - Iryna Wilde
30. Courage is the ability to stand shoulder to shoulder with your fears. - Volodymyr Vernadsky

### CODE REVIEW

**Comment by monkeytypegeorge** [comment]
Continuous integration check(s) failed. Please review the failing check's logs and make the necessary changes. https://github.com/monkeytypegame/monkeytype/actions/runs/4633159756

**Comment by Miodec** [comment]
The length fields are incorrect - please fix.

**Comment by abhaychaturvedii** [comment]
hello , can anyone suggest or guide me how a beginner can contribute to open source ?

**Comment by Miodec** [comment]
> hello , can anyone suggest or guide me how a beginner can contribute to open source ?

Here: https://github.com/monkeytypegame/monkeytype/blob/master/CONTRIBUTING.md

**Comment by abhaychaturvedii** [comment]
thankyou :)

**Pull request merged**
