### PR TITLE
feat(theme): add ranya black (abdullahhussein1)

### PR DESCRIPTION
**Pull request by abdullahhussein1**
### Description

Added a new theme called '**ranya black**'.

### Screenshots

- **HomePage**

1-normal
- With **Errors**

2-with-errors
- With **Flip Test Color Mode**

3-with-flip-colors-mode
- With **Colorful Mode**

4-with-colorful-mode
- With Both **Filp Test Color Mode** and **Colorful Mode**

5-with-both-flip-and-colorful-modes
- **SettingsPage**

6-settings

### CODE REVIEW

**Comment by Miodec** [comment]
Duplicate. Please verify theme is unique before opening a PR.

**Comment by abdullahhussein1** [comment]
I Checked other themes, there is dark grey, but there is no black one with white text.

**Comment by FFUV** [comment]
> I Checked other themes like **mountain**, it is dark grey, but there is no black one with white text.

true that there is none that are complete duplicates but still really similar

**Comment by abdullahhussein1** [comment]
I got it, thank you all 💎

**Pull request closed without merging**
