### PR TITLE
feat(theme): add acid rain theme

### PR DESCRIPTION
**Pull request by DefinitelySomeHuman**
Was bored so I made a theme based on random ideas. I like dark stuff :).
Screenshot 2024-02-07 4 40 38 PM
Screenshot 2024-02-07 4 41 02 PM
Screenshot 2024-02-07 4 41 16 PM
Screenshot 2024-02-07 4 41 27 PM
Screenshot 2024-02-07 4 41 35 PM
Screenshot 2024-02-07 4 41 43 PM

### CODE REVIEW

**Comment by monkeytypegeorge** [comment]
Continuous integration check(s) failed. Please review the failing check's logs and make the necessary changes. https://github.com/monkeytypegame/monkeytype/actions/runs/7822204302

**Comment by DefinitelySomeHuman** [comment]
my bad think i fixed it

**Comment by Miodec** [comment]
Text color should be as close to white as possible (can have a slight tint).

**Comment by DefinitelySomeHuman** [comment]
Should look a bit better now 
Screenshot 2024-02-08 7 52 28 AM
Screenshot 2024-02-08 7 53 14 AM

**Comment by mizaagi** [comment]
lol miodec is probably gonna say "too little contrast!" or something 😭

**Comment by Miodec** [comment]
Yeah i would make both sub color and sub alt color a bit darker.

**Comment by DefinitelySomeHuman** [comment]
I lowered the colors a bit so there would be a bit more contrast between the main and subtext. 
Screenshot 2024-02-08 12 32 01 PM

**Comment by mizaagi** [comment]
:)

**Pull request closed without merging**
