### PR TITLE
chore: lady_jam theme added

### PR DESCRIPTION
**Pull request by GaryGosh**
Added a new theme lady_jam

Screenshot 2023-08-15 at 6 54 23 PM

### CODE REVIEW

**Comment by Warrobot10** [comment]
Please rename your title to have chore: before your current title, like this: chore: lady_jam theme added
This should get rid of your checks not passing. More info can be found here: [Contributing.md](https://github.com/monkeytypegame/monkeytype/blob/master/CONTRIBUTING.md)

**Comment by GaryGosh** [comment]
Thanks renamed.

**Comment by GaryGosh** [comment]
Someone check and merge this pr pls

**Review by sleeepstorm — APPROVED** [review]

**Review by sleeepstorm — COMMENTED** [review]
I did not mean to click approve, I would see if @Miodec wants it in monkeytype so he can approve it.

**Comment by GaryGosh** [comment]
Ok . Something purple + white theme was necessary . That's why added. Lets see if @Miodec  approves / decline

**Comment by Miodec** [comment]
Sorry, I don't like the color combination here. The whole thing seems oversaturated too.

**Pull request closed without merging**
