### PR TITLE
feat(languages): Add Serbian 10k option

### PR DESCRIPTION
**Pull request by Fooftilly**
### Description

I've added a list of 10k words for Serbian, both in Latin and Cyrillic variants.

### Checks

- [ ] Adding quotes?
  - [ ] Make sure to include translations for the quotes in the description (or another comment) so we can verify their content.
- [x] Adding a language or a theme?
  - [x] If is a language, did you edit `_list.json`, `_groups.json` and add `languages.json`?
  - [ ] If is a theme, did you add the theme.css?
    - Also please add a screenshot of the theme, it would be extra awesome if you do so!
- [ ] Check if any open issues are related to this PR; if so, be sure to tag them below.
- [ ] Make sure the PR title follows the Conventional Commits standard. (https://www.conventionalcommits.org for more info)
- [x] Make sure to include your GitHub username inside parentheses at the end of the PR title

### CODE REVIEW

**Comment by monkeytypegeorge** [comment]
Continuous integration check(s) failed. Please review the failing check's logs and make the necessary changes. https://github.com/monkeytypegame/monkeytype/actions/runs/9877363902

**Comment by Fooftilly** [comment]
I have no idea what I should do about failed check. Please advise.

**Comment by fehmer** [comment]
- [Error: Name is not serbian_10k](https://github.com/monkeytypegame/monkeytype/actions/runs/9877363902/job/27278793483?pr=5603#step:7:18)  the name in the json file needs to match the file name.

**Review by DecoyGameDev — APPROVED** [review]

**Comment by Fooftilly** [comment]
Updated the names in the new language files. Didn't notice that there is also the language name inside the json files, because I copied and modified original 200 word versions.

**Comment by Miodec** [comment]
Thanks

**Pull request merged**
