### PR TITLE
impr(quotes): add guilty gear quote (remalucard)

### PR DESCRIPTION
**Pull request by remalucard**
### Description
added quote from guilty gear? idk if the text length is correct, if it's too short i'll just make it the song quote instead of game quote

### CODE REVIEW

**Comment by monkeytypegeorge** [comment]
Continuous integration check(s) failed. Please review the failing check's logs and make the necessary changes. https://github.com/monkeytypegame/monkeytype/actions/runs/6373878778

**Review by Warrobot10 — CHANGES_REQUESTED** [review]
Add a comma at line 38692, just after the curly bracket. That should make sure the checks pass. Also, make sure correct grammar is used in the quote. To change things, just commit to your clone of monkeytype that you started the pull request against. One last thing, make sure you change the title to chore: (title here). This ensures that the contribution can automatically be added to the release notes.

**Comment by remalucard** [comment]
now it should be fine.

**Comment by monkeytypegeorge** [comment]
Continuous integration check(s) failed. Please review the failing check's logs and make the necessary changes. https://github.com/monkeytypegame/monkeytype/actions/runs/6380270786

**Comment by monkeytypegeorge** [comment]
Continuous integration check(s) failed. Please review the failing check's logs and make the necessary changes. https://github.com/monkeytypegame/monkeytype/actions/runs/6380374416

**Comment by remalucard** [comment]
that was a pain but hey now i know how to do this properly

**Pull request merged**
