### PR TITLE
IBM Plex Mono Font

### PR DESCRIPTION
**Pull request by ibrab000**
### Description

Added the IBM Plex Mono Font.
This is the second pull request, because I fixed an error.

### CODE REVIEW

**Comment by Miodec** [comment]
Did you test that it shos up correctly?

**Comment by ibrab000** [comment]
Ok, just updated it, how do I test it?

**Comment by Miodec** [comment]
You would need to get the website running locally. Tested it and its fine.

**Comment by ibrab000** [comment]
Alright, thank you.

**Pull request merged**
