### PR TITLE
Adding theme "wikipedia"

### PR DESCRIPTION
**Pull request by Warrobot10**
### Description
Hey everyone, this is my first pull request pretty much ever, so please tell me if I did something wrong.
I'm adding a theme, that is meant to look similar to the default Wikipedia theme, because I thought it would be cool.
I guess you can check what stuff I added, and I can show you what screenshot I was working off. I don't know how to add a screenshot of how my theme is meant to look, so this is probably the best I can do. Thanks!

image

### CODE REVIEW

**Comment by monkeytypegeorge** [comment]
Continuous integration check(s) failed. Please review the failing check's logs and make the necessary changes. https://github.com/monkeytypegame/monkeytype/actions/runs/5350350732

**Comment by Miodec** [comment]
image

Theme makes most of the text invisible. But even if you fixed it, i think its pretty simmilar to the `milkshake` theme. Sorry.

**Comment by Warrobot10** [comment]
Okay, my bad. Btw, what do you do to see what the themes look like?

**Comment by Warrobot10** [comment]
Anyway, I kind of think that milkshake and Wikipedia is different after checking myself, because milkshake has blue text and Wikipedia was black with blue errors. All good anyways.

**Pull request closed without merging**
