### PR TITLE
Ignore modifier keys for test autofocus

### PR DESCRIPTION
**Pull request by andrewhchang**
### Description
Currently, when the user is focused on the restart button, any other key pressed will refocus the test. This poses problems for users who utilise remapping functions such as `ModTap` commonly utilised on sub 60% boards where `<hold> == Shift, <tap> == Enter`. This causes two keystrokes to be sent in quick succession such that a modtap user with the aforementioned mapping will never be able to use the `Tab+Enter` restart as `Shift` is always sent first.

This was resolved in https://github.com/monkeytypegame/monkeytype/commit/9a0026a1ab6de87e7597d5216912a5849b1cbb2d in reponse to  https://github.com/monkeytypegame/monkeytype/issues/1941, but was undone in https://github.com/monkeytypegame/monkeytype/commit/76664fc7ae778a58bf803a8558dc71e2279d6941 as part of  https://github.com/monkeytypegame/monkeytype/issues/2206 - as seemingly targeting the refresh button specifically caused unexpected behaviour.

Rather than dismiss keystrokes, I've elected to implement a small 200ms delay to refocus the test, other than for keys `Tab` and `Enter`, for which it will not take place. This gives time for `Enter` to be the prevailing key in the niche case above, and for the first returning key to resume normal operation.

Given every key will autofocus the test, the delay will never be present to affect typing as the the first keydown event will autofocus regardless after 200ms, or immediately if esc or tab, i.e. no delayed keystrokes appearing in typing test, no infinite debounce.

### CODE REVIEW

**Comment by Miodec** [comment]
I kinda don't like the sleep. Especially when out of focus warning is disabled and you want to start typing - the first keypresses within the 200ms are ignored. 

Maybe we can only autofocus on alphanumeric keys? And ignore the problematic shift?

**Comment by andrewhchang** [comment]
> I kinda don't like the sleep. Especially when out of focus warning is disabled and you want to start typing - the first keypresses within the 200ms are ignored.

Yeah good catch, didn't look at this scenario - that's a bummer.

> Maybe we can only autofocus on alphanumeric keys? And ignore the problematic shift?

Targeting alphanumeric might add some complexities with non-english languages and special characters, perhaps we could meet in the middle and just ignore modifier keys.

Made the change for the time being - would you also want to update the autofocus warning to something else to better describe the change? e.g. "Click here or start typing to focus"

**Comment by Miodec** [comment]
> Targeting alphanumeric might add some complexities with non-english languages and special characters, perhaps we could meet in the middle and just ignore modifier keys,

Yeah that's alright

> e.g. "Click or press any key to focus" -> "Click here or start typing to focus"

Yeap, good idea

**Comment by andrewhchang** [comment]
All done 👌🏻

**Review by Miodec — APPROVED** [review]

**Pull request merged**
