### PR TITLE
More french quotes

### PR DESCRIPTION
**Pull request by EMRD95**
Translation: 

 "text": "You are sitting and you only want to wait, wait only until there is nothing left to wait for: until the night comes, until the hours ring, until the days go by, until the memories fade away",
      "source": "A Sleeping Man (1967) by Georges Perec",
      "length": 207,
      "id": 117
    },
    {
      "text": "I love peanuts. You're drinking a beer and you're sick of the taste. So you eat peanuts. Peanuts are sweet and salty, strong and tender, like a woman. Eating peanuts, it's a really strong feeling. And then you feel like drinking beer again. Peanuts are the perpetual motion within the reach of man,
      "source": "JCVD cult quotes from Jean-Claude Van Damme",
      "length": 342,
      "id": 118
    },
    {
      "text": "To live is to go from one space to another trying as much as possible not to bump into each other.",
      "source": "Espèces d'espaces (1974) by Georges Perec",
      "length": 100,
      "id": 119
    },
    {
      "text": "He was a word killer: he worked on updating the Larousse dictionaries.",
      "source": "La Vie mode d'emploi (1978) by Georges Perec",
      "length": 84,
      "id": 120
    },
    {
      "text": "The law is implacable, but the law is unpredictable. No one is supposed to ignore it, but no one can know it.",
      "source": "W. ou le Souvenir d'enfance (1975) by Georges Perec",
      "length": 110,
      "id": 121
    },
    {
      "text": "You have everything to learn, everything that cannot be learned: solitude, indifference, patience, silence.",
      "source": "A Sleeping Man by Georges Perec",
      "length": 107,
      "id": 122
    },
    {
      "text": "You can be God of the dogs, God of the cats, God of the poor, all you need is a leash, some slack, some fortune, but you will never be master of the tree. You will never be able to but want to become a tree in your turn.",
      "source": "A Sleeping Man by Georges Perec",
      "length": 229,
      "id": 123
    },
    {
      "text": "Yea, though I walk through the valley of the shadow of death, I will fear no evil: for thou art with me, thy rod and thy staff, they comfort me.",
      "source": "Psalm 23:4 Darby Bible",
      "length": 164,
      "id": 124
    },
	{
      "text": "Nature has not made each of us like each other, but different in ability, and fit for this or that purpose.",
      "source": "Plato's Republic",
      "length": 88,
      "id": 125
    },
	{
      "text": "None of the human things are worth taking with great seriousness.",
      "source": "Plato's Republic",
      "length": 65,
      "id": 126
    },
	{
      "text": "True philosophers guard against all the passions of the body, resist them and do not give themselves over to them.",
      "source": "Phaedo, 82b by Plato",
      "length": 107,
      "id": 127
    },
	{
      "text": "Some call the body the tomb of the soul where it is presently buried.",
      "source": "Cratylus of Plato",
      "length": 106,
      "id": 128

### CODE REVIEW

**Comment by Miodec** [comment]
Remove the peanuts quote.
Remove the word killer quote.

**Comment by EMRD95** [comment]
Updated.
Is "peanut" not allowed because of allergies?

**Comment by Miodec** [comment]
> Updated. Is "peanut" not allowed because of allergies?

Haha, no. Just don't think its pg13

**Comment by Miodec** [comment]
Quote length fields are incorrect. Please fix ids 119,125,126,128.

**Pull request merged**
