### PR TITLE
feat(language): add English Shakespearean (risograph)

### PR DESCRIPTION
**Pull request by risograph**
### Description

++ Added Shakespearean English language
List of ≈ 200 shakespearean words

### CODE REVIEW

**Comment by monkeytypegeorge** [comment]
Continuous integration check(s) failed. Please review the failing check's logs and make the necessary changes. https://github.com/monkeytypegame/monkeytype/actions/runs/6358864468

**Comment by Warrobot10** [comment]
This pr would better fit as a feat:

**Comment by Warrobot10** [comment]
Looks like the checks failed because there is a duplicate of a word you included.

**Comment by monkeytypegeorge** [comment]
Continuous integration check(s) failed. Please review the failing check's logs and make the necessary changes. https://github.com/monkeytypegame/monkeytype/actions/runs/6360354884

**Review by Miodec — CHANGES_REQUESTED** [review]
Rename the file and language name to `english_shakespearean` and put it in the `english` group.

**Comment by Miodec** [comment]
> Should I add Shakespeare quotes along with this? It would tie it up nicely.

Sure

**Comment by Miodec** [comment]
Actually, this wont work with quote mode because it always switches the language to the group name..

**Pull request merged**
