### PR TITLE
Added Marathi

### PR DESCRIPTION
**Pull request by akhilesh-w**
Created a new file "marathi.json" to add Quotes in "Marathi" language.

### CODE REVIEW

**Comment by monkeytypegeorge** [comment]
Continuous integration check(s) failed. Please review the failing check's logs and make the necessary changes. https://github.com/monkeytypegame/monkeytype/actions/runs/4683763010

**Comment by monkeytypegeorge** [comment]
Continuous integration check(s) failed. Please review the failing check's logs and make the necessary changes. https://github.com/monkeytypegame/monkeytype/actions/runs/4683838606

**Comment by Miodec** [comment]
Could you also add a marathi file for 200 most common words? Also, i think it would be nicer to start with more quotes than 2.

**Comment by akhilesh-w** [comment]
yeah sure, will do

**Review by Miodec — APPROVED** [review]

**Pull request merged**
