### PR TITLE
test: fix getMonths test (@marcosatc147)

### PR DESCRIPTION
**Pull request by Marcosatc147**

### CODE REVIEW

**Comment by fehmer** [comment]
hi @Marcosatc147 ,

the tests were depending on the machines timezone. Can you check if https://github.com/monkeytypegame/monkeytype/pull/5740 solves your problem? Thanks

**Comment by Marcosatc147** [comment]
yes, it does!
but caused fails to config.spec, layout-emulator.spec and format.spec?

**Comment by fehmer** [comment]
Test on CI pass: https://github.com/monkeytypegame/monkeytype/actions/runs/10268594064

What timezone are you using locally? Can you share the error messages you get on the tests now?

**Comment by Marcosatc147** [comment]
https://imgur.com/a/Fdm880D
UTC-3

**Comment by fehmer** [comment]
looks like you have not build the packages. Try executing `npm run test-be` from the project root.

**Comment by Marcosatc147** [comment]
That's it. Works fine now

**Comment by Marcosatc147** [comment]
I'm closing the PR, thank you sm for explaining

**Pull request closed without merging**
