### PR TITLE
feat(quotes): add Kotlin quotes (Fynn-Pritzkau)

### PR DESCRIPTION
**Pull request by Fynn-Pritzkau**
feat: Kotlin Quotes Initialization (Fynn-Pritzkau)

### Description

Added three quotes to the Kotlin language.

### Checks

- [x] Adding a language or a theme?
    - [x] If is a language, did you edit `_list.json`, `_groups.json` and add `languages.json`?
    - [x] If is a theme, did you add the theme.css?
        - Also please add a screenshot of the theme, it would be extra awesome if you do so!
- [x] Check if any open issues are related to this PR; if so, be sure to tag them below.
- [x] Make sure the PR title follows the Conventional Commits standard. (https://www.conventionalcommits.org for more info)
- [x] Make sure to include your GitHub username inside parentheses at the end of the PR title

### CODE REVIEW

**Comment by monkeytypegeorge** [comment]
Continuous integration check(s) failed. Please review the failing check's logs and make the necessary changes. https://github.com/monkeytypegame/monkeytype/actions/runs/7571750479

**Comment by Miodec** [comment]
I think it would be good to start with a few more quotes

**Comment by monkeytypegeorge** [comment]
Continuous integration check(s) failed. Please review the failing check's logs and make the necessary changes. https://github.com/monkeytypegame/monkeytype/actions/runs/7630484604

**Comment by Fynn-Pritzkau** [comment]
i will add more tomorrow

**Comment by monkeytypegeorge** [comment]
Continuous integration check(s) failed. Please review the failing check's logs and make the necessary changes. https://github.com/monkeytypegame/monkeytype/actions/runs/7665127300

**Comment by Miodec** [comment]
Thanks

**Pull request merged**
