### PR TITLE
feat(funbox): add plaintext (@baerchen201)

### PR DESCRIPTION
**Pull request by baerchen201**
### Description

removes all punctuation and capitalization from the text very useful
 
### Checks

- [ ] Adding quotes?
  - [ ] Make sure to include translations for the quotes in the description (or another comment) so we can verify their content.
- [ ] Adding a language or a theme?
  - [ ] If is a language, did you edit `_list.json`, `_groups.json` and add `languages.json`?
  - [ ] If is a theme, did you add the theme.css?
    - Also please add a screenshot of the theme, it would be extra awesome if you do so!
- [x] Check if any open issues are related to this PR; if so, be sure to tag them below.
- [x] Make sure the PR title follows the Conventional Commits standard. (https://www.conventionalcommits.org for more info)
- [x] Make sure to include your GitHub username prefixed with @ inside parentheses at the end of the PR title.

### CODE REVIEW

**Comment by fehmer** [comment]
similar to https://github.com/monkeytypegame/monkeytype/pull/5850

**Comment by baerchen201** [comment]
> similar to #5850

yes but period

**Comment by baerchen201** [comment]
> similar to #5850

not anymore

**Comment by Miodec** [comment]
Yeap, duplicate of IM.

**Pull request closed without merging**
