### PR TITLE
impr(quotes): add Mongolian quotes (filename24)

### PR DESCRIPTION
**Pull request by filename24**
### Description

This PR adds 50 initial Mongolian quotes to the existing language group. There are a combination of proverbs, book quotes, and some song lyrics.

This is just to get the ball rolling and provide initial content for others to build upon. If you have any questions or requests to help with merging, let me know and I'd be happy to oblige!

#### Translations 
| text                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              |  source                                                              |  length |  id |   |
|-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|----------------------------------------------------------------------|---------|-----|---|
|  It is said that there were three fish in a river: wise, stupid and cunning. The fisherman caught the wily fish and threw it over the net, and it quickly dived into the water and disappeared.                                                                                                                                                                                                                                                                                                                                                                                   |  Three friends - Mongolian folk tale                                 |  153    |  1  |   |
|  The squirrel jumped from tree to tree and fell upon the sleepy wolf.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             |  Squirrel and wolf                                                   |  65     |  2  |   |
| " Squirrels and bears were called to a race in front of the forest animals to ""get ready for winter."""                                                                                                                                                                                                                                                                                                                                                                                                                                                                          |  An unusual competition                                              |  86     |  3  |   |
|  There is another animal that has long wanted to live with Sargai flower.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         |  The sorghum and the lark                                            |  73     | 4   |   |
|  Maralmaa Anaraa went to pick fruit with her two brothers and sisters. He went to the mountain tree and started picking fruit. I saw that Anaraa was eating pomegranate fruit with branches.                                                                                                                                                                                                                                                                                                                                                                                      |  Picking fruit                                                       |  156    |  5  |   |
|  The little mouse found something amazing. What he found was white, square, and smelled good. Then I took the white square thing and went home. The parents of the little mouse were very happy.                                                                                                                                                                                                                                                                                                                                                                                  |  A little mouse                                                      |  235    |  6  |   |
| There is silence in the room. The teacher goes to each child and looks at the picture they are drawing. All children were tasked with drawing one of the five-headed animals.                                                                                                                                                                                                                                                                                                                                                                                                     |  Spring - D. Bazarragchaa                                            |  145    |  7  |   |
| " A small leaf will grow up, mirroring itself in the riverbed, shouting, ""I'm getting big. I'm getting big."""                                                                                                                                                                                                                                                                                                                                                                                                                                                                   |  Dream of green leaves                                               |  127    |  8  |   |
|  A puppy and a kitten of a family lived in harmony and well.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      |  Puppies and kittens                                                 |  75     |  9  |   |
| Attach a bell to the core. He told me to find out where he is going by the sound of the bell. And it is said that a bell that children wear was born.                                                                                                                                                                                                                                                                                                                                                                                                                             |  Bell                                                                |  122    |  10 |   |
|  Once upon a time, Ele and Chochigo went far away to learn science and music. He flew to his destination.                                                                                                                                                                                                                                                                                                                                                                                                                                                                         |  Learning science - Mongolian folk tale                              |  83     |  11 |   |
|  Old man, when are you planting the fruit of this tree when you are such an old man? Can you wait for the apple tree to grow and bear fruit? he asked mockingly.                                                                                                                                                                                                                                                                                                                                                                                                                  |  Apple tree                                                          |  187    |  12 |   |
| "Pretty fingers will ""catch it"" like that. Can't get rid of it? Squeeze the stem of the bat you're holding! There will be a liquid white juice. Just rub it on it and it will go away! said old man Osor. Bold pressed the stem of the bat against it and made it disappear. Bold stopped playing with the medicinal herb bat that helped his body ailment. But he took part in a drawing competition."                                                                                                                                                                         |  Removal of fingernails - D. Bazarragchaa                            |  412    |  13 |   |
| One day, Suvdaa's mother went to work without being able to wash her shirt because she was busy with work. That blouse was the most beautiful of her mother's clothes. Pearl washed the shirt to help her mother. Wash it in the washing machine and press it on the fabric. When he looked at his shirt in the evening, it was too small to fit his brother. Mom will come home from work soon. The pearl girl panicked, took the shirt and stretched it with an iron, but it did not grow. There was a knock on the door. He hid his shirt because he was afraid of his mother. |  Mother's shirt                                                      |  463    |  14 |   |
| It is good to inflate the raw milk with a gentle fire of dung. The fire of the fire burns fiercely. Then turn down the heat and stir the milk well. If it burns for a long time, then it will be a yellow drill. If the milk is heated with a strong fire, the milk will burn and the drill will not work well.                                                                                                                                                                                                                                                                   |  Drill                                                               |  250    |  15 |   |
| " My father's acquaintance, Mrs. Dorje, kept rabbits. Last summer, they camped in our yard. For my son, their little brown bunny was a very ""fun"" toy."                                                                                                                                                                                                                                                                                                                                                                                                                         |  Why did the brown rabbit turn white?                                |  174    |  16 |   |
| "Once upon a time, Lord Buddha gave the name of an animal that was hunted in twelve years. The names of eleven animals were spoken directly. But what animal name will be given in the last or the first year of twelve years? Both the camel and the mouse said ""I, I"". God said, ""Decide for yourselves"" so as not to offend either of them."                                                                                                                                                                                                                               |  The reason why the camel turned into ashes - Mongolian folk tale    |  318    |  17 |   |
|  Amar was speechless. He is a child who keeps his voice down and hangs his lips like this to appease his mother and father. He wanted to say something to his classmates.                                                                                                                                                                                                                                                                                                                                                                                                         | Classmates - S. Nadmid                                               |  159    |  18 |   |
|  In the past, there was only one orphan and three orphans. Three children drank this milk, and the mother nursed her mother for a living.                                                                                                                                                                                                                                                                                                                                                                                                                                         |  The three festivals - Mongolian folk tale                           |  126    |  19 |   |
|  Since it was a weekend, people from the city took light carriages, two-wheelers, and some even flew in a plane flying straight up to go for a walk on the mountain.                                                                                                                                                                                                                                                                                                                                                                                                              |  Eternal water - L. Tudev                                            |  270    |  20 |   |
| "Before his death, a poor farmer with an only son told his wife, ""Make your son a good, learned man. Then everyone will respect him."""                                                                                                                                                                                                                                                                                                                                                                                                                                          |  Father's message                                                    |  135    |  21 |   |
| " One wants to make it ""white as a swan"". The other said to make it ""black as a crow""."                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       |  Human mind - Mythology                                              |  74     |  22 |   |
|  Do not touch the eggs of prairie birds. As soon as the shadow of the whip touches them, they reject the seed.                                                                                                                                                                                                                                                                                                                                                                                                                                                                    |  Don't let your shadow fall on the eggs of prairie birds - D. Nyamaa |  99     |  23 |   |
| In ancient times, people did not grow crops, so they ate only meat. It is said that waterfowl leave their eggs in the water in the fall, hibernate in warm beds, and come back with joy to see them in the spring.                                                                                                                                                                                                                                                                                                                                                                |  Man planting crops - Myth                                           |  209    |  24 |   |
|  The functioning of the two sides of the cerebrum is unbalanced.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  |  Why do most people use their right hand?                            |  58     |  25 |   |
|  Brother! It will be very cold on this cold stormy night. They both said to find a rock cave and sleep.                                                                                                                                                                                                                                                                                                                                                                                                                                                                           |  Gold and silver                                                     |  95     |  26 |   |
|  grandfather and a boy went on a journey with a donkey. When approaching the city, he leads the donkey.                                                                                                                                                                                                                                                                                                                                                                                                                                                                           |  Grandfather and son                                                 |  96     |  27 |   |
|  The two sisters were very busy since morning preparing and decorating their dresses.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             |  Cinderella - Fairy Tale                                             |  68     |  28 |   |
|  When the chicks jump in a line, and when they dive and come out into the water, their legs move on their own, and when they go nuts, the ugly brown chicks go nuts too.                                                                                                                                                                                                                                                                                                                                                                                                          |  The Ugly Duckling - Fairy Tale                                      |  165    |  29 |   |
| "Princess Tuya, who is beautiful through the mountains and bright through the house, connects the earth and the sky with a rainbow. While singing in the sky and dancing on the ground, one day Father Sun called and said, ""My daughter, you are now grown up. It is time for you to work."" But Tuya was surprised and said, ""Work? I wandered through the sky and went here and there. I saw a lot of stars and spaceships. But I didn't see any work there."" said."                                                                                                        |  Princess Tuya of Naran Khan                                         |  394    |  30 |   |
|  This dream of mine is abnormal, about you and me                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 |  Chinii Nudeer (feat. Anir) - Vandebo                                |  48     |  31 |   |
| Now I was so happy when I was with you                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            |  Missed Call - Ginjin                                                |  85     |  32 |   |
|  Is it a tree that I come to touch?                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               |  You Really Are - Davaidasha                                         |  43     |  33 |   |
|  But I was in the wrong place at the right time                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   |  Dug Noiron Dundaas - Davaidasha                                     |  44     |  34 |   |
|  Why do I think of you every night?                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               |  Temtruul - Davaidasha                                               |  46     |  35 |   |
|  A festival full of sweets and laughter                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           |  The same year's festival I saw with Iji                             |  36     |  36 |   |
|  It's nice when the plants grow and turn green, and the wire tree turns blue and withers                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          |  Four hours                                                          |  74     |  37 |   |
| "In the past, when giving the names of the animals for the twelve years of the Mongolian liturgy, God directly counted the names of the eleven animals and asked, ""Which animal will be named for the first year of the twelve years?"" But the camel and the mouse entered their names and were captured to fit into the twelve years."                                                                                                                                                                                                                                         |  Because the camel turns to ashes                                    |  267    |  38 |   |
|  Once upon a time, a poor boy used to make a living by making traps and nets for rats and mice.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   |  Argat red fox                                                       |  93     |  39 |   |
| The two boys came back and slept under the tree, and when they woke up in the morning, there was a big house full of wealth and five heads of cattle.                                                                                                                                                                                                                                                                                                                                                                                                                             |  The king's son is gombo, and the gaze's son is gongor               |  133    |  40 |   |
|  One of the three wolves was named Wise Gray, the other was named Bulk Gray, and the third was named Swift Gray.                                                                                                                                                                                                                                                                                                                                                                                                                                                                  |  A king as wise as a lion                                            |  103    |  41 |   |
|  Let's show you if love is blind                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  |  HAPPY U YEAR - U Brand                                              |  53     |  42 |   |
|  A hardworking population is blessed, a lazy person has a bad fate                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                |  Mongolian proverb                                                   |  47     |  43 |   |
|  Take the front and put it on the mane, take the handle and put it on the pinch                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   | Mongolian proverb                                                    |  57     |  44 |   |
|  Respecting one's elders is a sign of pride, Arguing with a lion is a sign of stupidity                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           |  Mongolian proverb                                                   |  64     |  45 |   |
|  In self-defense, like a bird that lays eggs                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      |  Mongolian proverb                                                   |  44     |  46 |   |
|  It's easy for a dull person to get discouraged, and it's easy for a lead spear to fall                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           |  Mongolian proverb                                                   |  65     |  47 |   |
|  A wise man knows his sin, a sober man knows his sin                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              |  Mongolian proverb                                                   |  59     |  48 |   |
|  Gems are rare but can be found, Knowledge is deep but can be learned                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             |  Mongolian proverb                                                   |  60     |  49 |   |
|  thumb is learned, but without a little finger, it is lacking                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     |  Mongolian proverb                                                   |  50     |  50 |   |

### Checks

- [x] Adding quotes?
  - [x] Make sure to include translations for the quotes in the description (or another comment) so we can verify their content.
- [ ] Adding a language or a theme?
  - [ ] If is a language, did you edit `_list.json`, `_groups.json` and add `languages.json`?
  - [ ] If is a theme, did you add the theme.css?
    - Also please add a screenshot of the theme, it would be extra awesome if you do so!
- [ ] Check if any open issues are related to this PR; if so, be sure to tag them below.
- [x] Make sure the PR title follows the Conventional Commits standard. (https://www.conventionalcommits.org for more info)
- [x] Make sure to include your GitHub username inside parentheses at the end of the PR title

<!-- label(optional scope): pull request title (your_github_username) -->

<!-- I know I know they seem boring but please do them, they help us and you will find out it also helps you.-->

<!-- the issue(s) your PR resolves if any (delete if that is not the case) -->
<!-- please also reference any issues and or PRs related to your pull request -->
<!-- Also remove it if you are not following any issues. -->

<!-- pro tip: you can mention an issue, PR, or discussion on GitHub by referencing its hash number e.g: [#1234](https://github.com/monkeytypegame/monkeytype/pull/1234) -->

<!-- pro tip: you can press . (dot or period) in the code tab of any GitHub repo to get access to GitHub's VS Code web editor Enjoy! :) -->

### CODE REVIEW

**Comment by monkeytypegeorge** [comment]
Continuous integration check(s) failed. Please review the failing check's logs and make the necessary changes. https://github.com/monkeytypegame/monkeytype/actions/runs/8203405505

**Comment by monkeytypegeorge** [comment]
Continuous integration check(s) failed. Please review the failing check's logs and make the necessary changes. https://github.com/monkeytypegame/monkeytype/actions/runs/8203986606

**Comment by Miodec** [comment]
Seems like some of these are missing periods. Could you also replace any quotes shorter than 60 characters with longer ones?

**Comment by filename24** [comment]
> Seems like some of these are missing periods. Could you also replace any quotes shorter than 60 characters with longer ones?

@Miodec , Okay, I fixed it. Please review it again. And here's a translation of the changed quotes.

| Text | Source | Length | id |
|--------|--------|--------|--------|
| The first historical monument of our Mongolian nation is the Mongolian Secret Bureau. | Secret history of Mongolia | 94 | 31 |
| In 1466, Queen Mandukhay Seten installed Batmunkh on the throne with the support of other princes of the Golden Family and elevated her to the title of Dayan Khan. | History of Mongolia | 128 | 33 |
| Once upon a time, Shigemuni went to Khurmast to worship the God of Heaven, before the appearance of Nirvana. | Summary of Geser's novel | 99 | 34 |
| Give a proclamation to this great country, put on the shirt, house, and socks you wear there. | A poem depicting the hero of Sunid Gilugedei | 83 | 35 |
| Genghis Khan's roots, Burt Chino, who was born from heaven, and his wife Khoo Maral, came to rescue the sea and settled in Mount Burhan Khaldun, the source of the Onon River, and gave birth to a 
 boy named Batsagaan. | Mongolian secret bureau - Temujin's origin and childhood | 197  | 36 |
 | All of Mongolia was ruled by Khabul Khan. When Habul Khan was seven years old, he told him to make Ambagai, the son of Sengun yil, the king of all Mongolia. | Mongolian secret bureau - Temujin's origin and childhood | 147 | 42 |
 | Bodonchar is staring at the snoring of his horse. | Bodonchar Bogd | 68 | 43 |
 | Over the remains of eight centuries ago, a lark chirps today, and the head of the native king bows down mournfully. | A short story of Jamukh | 147 | 46 |
 | The merriment of the country folk frolicking around me immediately captivates my heart, and the beauty of San Bey's horse stirs my will. | Country Fair | 146 | 48 |
 | In the summertime, the smell of urine and feces on the five streets of West Dhannuurch is overwhelming, so much so that you can't suppress it even if you burn a lot of incense. | Tears of Lambugay | 141 | 50 |

**Comment by Miodec** [comment]
Thanks

**Pull request merged**
