### PR TITLE
impr(settings): replace sound volume with a slider (@amarnathsama)

### LINKED ISSUE #4764: Replace sound volume settings with a slider

### PR DESCRIPTION
**Pull request by amarnathsama**
### Description
Replaced the volume settings with a slider for better user experience.

### Checks

- [x] Check if any open issues are related to this PR; if so, be sure to tag them below.
- [x] Make sure the PR title follows the Conventional Commits standard. (https://www.conventionalcommits.org for more info)
- [x] Make sure to include your GitHub username inside parentheses at the end of the PR title

Closes #4764

Looks like this
image

### CODE REVIEW

**Comment by Miodec** [comment]
Thank you for the PR. However, some time recently we added a `range` mode to the `SettingsGroup` class, which means you dont need to create a slider handling file anymore. You should be able to just use `SettingsGroup` like this:

image

(and then ensure the html structure is correct).

Conversion of the config value to a float is good though.

Please update the PR.

**Comment by amarnathsama** [comment]
Hi @Miodec, since changes are being handled by the SettingsGroup class, it shows the actually float value(instead of it being multiplied by 100), is this fine?
image

**Comment by Miodec** [comment]
> Hi @Miodec, since changes are being handled by the SettingsGroup class, it shows the actually float value(instead of it being multiplied by 100), is this fine? image

Yeah

**Review by Miodec — APPROVED** [review]
Thanks

**Pull request merged**
