### PR TITLE
feat: alphas in thumbs (@zigotica)

### PR DESCRIPTION
**Pull request by zigotica**
### Description
ROW 5 in Matrix keyboards allow for alphas in thumb keys.
           * Any combination of 1 or two keys.
           * Space key with layout name is automatically added.
           * If only one alpha key defined, it will be assigned to right hand.
           * If the alpha key must be on the left, explicitly set ["eE", " "]
           * You can also define two alpha keys (space is added automatically on the left).
           * Added keymaps using alphas in thumbs: anishtro, BEAKL_Zi, MALTRON, PRSTEN and RSTHD

### Checks

- [ ] Adding quotes?
  - [ ] Make sure to include translations for the quotes in the description (or another comment) so we can verify their content.
- [ ] Adding a language or a theme?
  - [ ] If is a language, did you edit `_list.json`, `_groups.json` and add `languages.json`?
  - [ ] If is a theme, did you add the theme.css?
    - Also please add a screenshot of the theme, it would be extra awesome if you do so!
- [x] Check if any open issues are related to this PR; if so, be sure to tag them below.
- [x] Make sure the PR title follows the Conventional Commits standard. (https://www.conventionalcommits.org for more info)
- [x] Make sure to include your GitHub username prefixed with @ inside parentheses at the end of the PR title.

Closes #2291

### CODE REVIEW

**Comment by zigotica** [comment]
fixed

**Comment by zigotica** [comment]
Sorry @Miodec this is a mess now, and I don't like rebasing. I will close this and eventually (maybe during w/e) open a new PR with selective cherry-picks.

**Comment by Miodec** [comment]
> Sorry @Miodec this is a mess now, and I don't like rebasing. I will close this and eventually (maybe during w/e) open a new PR with selective cherry-picks.

Alright, sorry for causing a mess.

**Comment by zigotica** [comment]
> > Sorry @Miodec this is a mess now, and I don't like rebasing. I will close this and eventually (maybe during w/e) open a new PR with selective cherry-picks.
> 
> Alright, sorry for causing a mess.

don't worry, not your fault

**Pull request closed without merging**
