### PR TITLE
Remove daily lb cache

### PR DESCRIPTION
**Pull request by Bruception**
### Description

Closes #

### CODE REVIEW

**Comment by monkeytypegeorge** [comment]
Continuous integration check(s) failed. Please review the failing check's logs and make the necessary changes. https://github.com/monkeytypegame/monkeytype/actions/runs/4835630869

**Comment by monkeytypegeorge** [comment]
Continuous integration check(s) failed. Please review the failing check's logs and make the necessary changes. https://github.com/monkeytypegame/monkeytype/actions/runs/4835642643

**Comment by Ferotiq** [comment]
May I ask what the cache was used for previously and why it's not needed now?

**Comment by Bruception** [comment]
> May I ask what the cache was used for previously and why it's not needed now?

Avoid re-creating daily leaderboard objects for every new result. But should be minimal impact.

**Review by Miodec — APPROVED** [review]

**Pull request merged**
