### PR TITLE
add xmint theme

### PR DESCRIPTION
**Pull request by Axorax**
### Description

Added xmint theme to the themes folder and _list.json

### Screenshots

image

image

### CODE REVIEW

**Comment by Miodec** [comment]
Text color cannot be colored.
Sub alt color is too dark imo.
Looks a bit like `mint`, not sure if it will get merged.

**Comment by Axorax** [comment]
> Text color cannot be colored. Sub alt color is too dark imo. Looks a bit like `mint`, not sure if it will get merged.

i changed the colors and name to xmint

**Comment by Miodec** [comment]
Yeah, sorry - this theme is too simmilar to mint.

**Comment by monkeytypegeorge** [comment]
Continuous integration check(s) failed. Please review the failing check's logs and make the necessary changes. https://github.com/monkeytypegame/monkeytype/actions/runs/5333308967

**Pull request closed without merging**
