### PR TITLE
Added a few malay words and quotes

### PR DESCRIPTION
**Pull request by zer0exia**
### Description

Added a few more common malay words, and also added a new quote file "malay.json" that contain excerpts from poems, idioms, lyrics.

### CODE REVIEW

**Comment by monkeytypegeorge** [comment]
Continuous integration check(s) failed. Please review the failing check's logs and make the necessary changes. https://github.com/monkeytypegame/monkeytype/actions/runs/5289870984

**Comment by monkeytypegeorge** [comment]
Continuous integration check(s) failed. Please review the failing check's logs and make the necessary changes. https://github.com/monkeytypegame/monkeytype/actions/runs/5289938868

**Comment by monkeytypegeorge** [comment]
Continuous integration check(s) failed. Please review the failing check's logs and make the necessary changes. https://github.com/monkeytypegame/monkeytype/actions/runs/5289963567

**Comment by monkeytypegeorge** [comment]
Continuous integration check(s) failed. Please review the failing check's logs and make the necessary changes. https://github.com/monkeytypegame/monkeytype/actions/runs/5290024179

**Comment by monkeytypegeorge** [comment]
Continuous integration check(s) failed. Please review the failing check's logs and make the necessary changes. https://github.com/monkeytypegame/monkeytype/actions/runs/5290068117

**Comment by monkeytypegeorge** [comment]
Continuous integration check(s) failed. Please review the failing check's logs and make the necessary changes. https://github.com/monkeytypegame/monkeytype/actions/runs/5290131456

**Comment by Miodec** [comment]
Please dont push the default list much past 200 words. If you want to add more words, duplicate the list and rename it to `malay_1k`.

Please translate the quotes so I can verify their content.

**Comment by zer0exia** [comment]
Sorry didn't realize about the limit. I'll create that file and add the words there.  Where do you want the quote's translations to be posted?

Also, apologies in advanced.  I'm not experienced with git, so I don't know how to remove only that one file with changes. Could you maybe dismiss this PR and I'll create a new PR with the new files instead?

**Pull request closed without merging**
