### PR TITLE
feat(theme): Add lilac_mist (sandyg6)

### PR DESCRIPTION
**Pull request by sandyg6**
### Description
 - Added a new color palette feature to themes.

### Checks

- [ ] Adding quotes?
  - [ ] Make sure to include translations for the quotes in the description (or another comment) so we can verify their content.
- [x] Adding a language or a theme?
  - [ ] If is a language, did you edit `_list.json`, `_groups.json` and add `languages.json`?
  - [x] If is a theme, did you add the theme.css?
    - Also please add a screenshot of the theme, it would be extra awesome if you do so!
- [ ] Check if any open issues are related to this PR; if so, be sure to tag them below.
- [x] Make sure the PR title follows the Conventional Commits standard. (https://www.conventionalcommits.org for more info)
- [x] Make sure to include your GitHub username inside parentheses at the end of the PR title

Screenshot (117)

Screenshot (118)

Closes #

### CODE REVIEW

**Comment by Miodec** [comment]
Text must be white or black (can be tinted). Please update.

**Comment by sandyg6** [comment]
DESCRIPTION:
 - Updated theme lilac_mist

image
image

**Comment by Miodec** [comment]
Switch the sub and text color around, and also diffrentiate somehow between (new) sub and main. That way text color will be darker.

**Comment by sandyg6** [comment]
DESCRIPTION:

Updated new colors to the theme lilac_mist

Screenshot 2024-06-04 091710
Screenshot 2024-06-04 091728

**Comment by sandyg6** [comment]
Description:
- Newly updated error color
Screenshot 2024-06-07 193537

**Comment by Miodec** [comment]
Thanks

**Pull request merged**
