### PR TITLE
feat(theme): add mockingbird theme (@chinmaydwivedi)

### PR DESCRIPTION
**Pull request by chinmaydwivedi**
### Checks

- [ yes] Adding quotes?
  - [yes] Make sure to include translations for the quotes in the description (or another comment) so we can verify their content.
- [ yes] Adding a language or a theme?
  - [yes] If is a language, did you edit `_list.json`, `_groups.json` and add `languages.json`?
  - [yes] If is a theme, did you add the theme.css?
    - Also please add a screenshot of the theme, it would be extra awesome if you do so!
    - 
Theme While Typing

Theme Overview
<--Theme while overview-->
Navigation Preview

Color Flip Mode
<--Color flip Mode-->
Colur Full Mode
<--Color full Mode-->
- [none] Check if any open issues are related to this PR; if so, be sure to tag them below.
- [yes] Make sure the PR title follows the Conventional Commits standard. (https://www.conventionalcommits.org for more info)
- [okay] Make sure to include your GitHub username prefixed with @ inside parentheses at the end of the PR title.

Closes #

### CODE REVIEW

**Comment by FFUV** [comment]
please show example pictures!

**Comment by Miodec** [comment]
Screenshots missing

**Comment by chinmaydwivedi** [comment]
> Screenshots missing


> please show example pictures!

sorry i forgot to do that earlier, I just updated the comment.

**Comment by FFUV** [comment]
beautiful  theme honestly

**Review by FFUV — APPROVED** [review]

**Comment by FFUV** [comment]
Bump merge this

**Comment by Miodec** [comment]
Sorry, look like a duplicate of paper, with worse color choices. For example here it looks like these buttons are on, but they are in fact off.

image

**Comment by FFUV** [comment]
> Sorry, look like a duplicate of paper, with worse color choices. For example here it looks like these buttons are on, but they are in fact off.
> 
> image

looks like but is it really?

**Pull request closed without merging**
