### PR TITLE
make the bg color a bit darker* 🕳

### PR DESCRIPTION
**Pull request by Abod1960**
no big deal, just made the bg darker

**before:**

Screenshot 2022-05-05 163150
---
**after:**
Screenshot 2022-05-05 163157

### CODE REVIEW

**Comment by Miodec** [comment]
Please include screenshots of before and after

**Comment by Miodec** [comment]
Also, why the change?

Are you the original creator of this theme or the keyset GB runner?

image

Based on this the current color is fine?

**Comment by Abod1960** [comment]
> Also, why the change?
> 
> Are you the original creator of this theme or the keyset GB runner?
> 
> image
> 
> Based on this the current color is fine?

well, this is because I'm making some other moonlight themes for other software, apps, etc, and I needed a darker color to be in the bg, then I wanted monkey-type moonlight theme to be compatible with the other themes, this is why...
and I'm not the original creator of keyset GB runner, but I'm planning on making a color inspired by moonlight keyset.

**Comment by Miodec** [comment]
> I'm not the original creator of keyset GB runner, but I'm planning on making a color inspired by moonlight keyset.

Maybe you could try to find the original creator and just ask him for the HEX codes?

**Comment by Abod1960** [comment]
> > I'm not the original creator of keyset GB runner, but I'm planning on making a color inspired by moonlight keyset.
> 
> Maybe you could try to find the original creator and just ask him for the HEX codes?

here are they:
image
**#d3ab6d, #3b4856**

but I don't want them, I made the bg darker because I feel it should be, you know something I hate light themes this is why when I was trying to have a color palette out of only these two colors in the image I went for darker colors, and let me show u the colors I came up with:
image

and the hex colors are different for sure.
and sorry for making this a long story 😅
ty for understanding

**Comment by Miodec** [comment]
Alright, ok. Lets merge it

**Pull request merged**
