### PR TITLE
Added 7 quotes on spanish

### PR DESCRIPTION
**Pull request by Dioswilson**
Added 7 spanish quotes and deleted a word from a previous quote which made no sense. Also i'm not too sure about last quote's format

### CODE REVIEW

**Comment by rizwanmustafa** [comment]
I think you will be fine this time. Also you did not need to close the last PR. You could have just pushed the changes.

Please post a translation of these quotes here.

**Comment by Dioswilson** [comment]
Translations:

1: There's no magic, only illusion. Things only change when we change them, but you have to be clever, do it secretly. And then it looks like magic.

2: our thinking is molded by dualism. In, out. Black, white. Good, evil. Everything look like opposite pairs. But it's wrong

3: Death is incomprehensible but you can reconciliate with her. Until then, you will ask yourself everyday if you made the right choices.

4: The man is a strange creature. Every action he makes is motivated by desire, his nature forjed by pain. it doesn't matter how much he tries to supress that pain, desire, he cannot free himself from eternal bondage to his feelings. While the storm unleashes inside of him, he can't find peace. Not in life, not in death. And he will do what it needs to be done, day after day.

5: Two thing are infinite: human stupidity and the Universe. And I'm not sure about the second one.

6: there has been 25 years since Gold Roger explored all the Grand Line. His archnemesis, Whitebeard, didn't sit on the throne, he just standed in front of it and took the leashes. What's now? The number of pirates is risign and there's only one empty seat! You know what i mean. Right? It will soon begin! the biggest battle for supremacy in the pirates history!

7: This "New Era" that everyone is talking about is bullshit. the time where pirates dreams have ended?! People dreams never ends!

**Comment by Miodec** [comment]
> 

Remove swears, keep it PG13.

**Comment by Dioswilson** [comment]
Should i change Einstein's quote about stupidity?

**Comment by Miodec** [comment]
> Should i change Einstein's quote about stupidity?

That one is fine

**Pull request merged**
