### PR TITLE
impr(quotes): Added quotes. (sleeepstorm)

### PR DESCRIPTION
**Pull request by sleeepstorm**
### Description
I added varying amounts of quotes. Here is the amount so far:
- 7 Spanish Quotes
- 2 Hindi Quotes
- 2 Go Quotes

As far as I know this doesn't close any issues.

### CODE REVIEW

**Comment by monkeytypegeorge** [comment]
Continuous integration check(s) failed. Please review the failing check's logs and make the necessary changes. https://github.com/monkeytypegame/monkeytype/actions/runs/7106335838

**Comment by monkeytypegeorge** [comment]
Continuous integration check(s) failed. Please review the failing check's logs and make the necessary changes. https://github.com/monkeytypegame/monkeytype/actions/runs/7106381477

**Comment by monkeytypegeorge** [comment]
Continuous integration check(s) failed. Please review the failing check's logs and make the necessary changes. https://github.com/monkeytypegame/monkeytype/actions/runs/7108368432

**Comment by Miodec** [comment]
Please add a comment with quote translations

**Comment by sleeepstorm** [comment]
> Please add a comment with quote translations

## Spanish Quotes:
`ID: 148`: "To err is human, but it is even more so to blame others" - Baltasar Gracián
`ID: 149`: "The pessimist complains about the wind, the optimist hopes it will change, but the realist adjusts the sails." - William Wars
`ID: 150`: "If you do what you've always done, you'll get what you've always gotten. It is not what we do from time to time that shapes our lives, but what we do constantly." - Tony Robbins
`ID: 151`: "There must be something wrong with the job or the rich would have already monopolized it." - Cantinflas
`ID: 152`: "Life is like riding a bicycle. To maintain balance you have to move forward." - Albert Einstein
`ID: 153`: "How wonderful it is that no one has to wait even a second to start improving the world." - Anne Frank
`ID: 154`: "Happiness is internal, not external; Therefore, it does not depend on what we have, but on what we are." - Pablo Neruda
## Hindi Quotes
`ID: 38`: “Wherever the eyes of a free spirit fall, that is my home." - Amrita Pritam
`ID: 39`: "If we are committed, we can create a world in which there is much less prejudice, and consequently much less conflict." - Sadhguru

**Comment by monkeytypegeorge** [comment]
Continuous integration check(s) failed. Please review the failing check's logs and make the necessary changes. https://github.com/monkeytypegame/monkeytype/actions/runs/7310165730

**Comment by sleeepstorm** [comment]
> > Please add a comment with quote translations
> 
> ## Spanish Quotes:
> `ID: 148`: "To err is human, but it is even more so to blame others" - Baltasar Gracián `ID: 149`: "The pessimist complains about the wind, the optimist hopes it will change, but the realist adjusts the sails." - William Wars `ID: 150`: "If you do what you've always done, you'll get what you've always gotten. It is not what we do from time to time that shapes our lives, but what we do constantly." - Tony Robbins `ID: 151`: "There must be something wrong with the job or the rich would have already monopolized it." - Cantinflas `ID: 152`: "Life is like riding a bicycle. To maintain balance you have to move forward." - Albert Einstein `ID: 153`: "How wonderful it is that no one has to wait even a second to start improving the world." - Anne Frank `ID: 154`: "Happiness is internal, not external; Therefore, it does not depend on what we have, but on what we are." - Pablo Neruda
> 
> ## Hindi Quotes
> `ID: 38`: “Wherever the eyes of a free spirit fall, that is my home." - Amrita Pritam `ID: 39`: "If we are committed, we can create a world in which there is much less prejudice, and consequently much less conflict." - Sadhguru

@Miodec I have provided translations

**Review by Miodec — APPROVED** [review]
Thanks

**Pull request merged**
