### PR TITLE
feat(themes): added lean theme (FFUV) 

### PR DESCRIPTION
**Pull request by FFUV**
I've added a lean theme for the memes. I hope it suffices
Screen Shot 2024-06-24 at 12 40 52 AM
Screen Shot 2024-06-24 at 12 41 03 AM
Screen Shot 2024-06-24 at 12 41 43 AM

### CODE REVIEW

**Comment by FFUV** [comment]
btw if the name is a little inappropriate will gladly change (it was kind of cringe)

**Comment by Miodec** [comment]
Sorry, I don't think it looks good enough to add.

**Comment by FFUV** [comment]
@bacn can you stop stalking me and finding ever chance you get to harass me i'm 16 man you're 29 please stop annoying me I just want to live my life I've learnt from my mistakes what do you want from me

**Comment by FFUV** [comment]
@Miodec could you also reopen this because beuty is objective and there are many themes that "dont look good enough"

**Comment by FFUV** [comment]
and @MattMadness just because I asked you to change some things on your pull request on A SEPERATE repository doesnt mean you need to stalk me onto here and annoy me.

**Pull request closed without merging**
