### PR TITLE
Added Rainbow Trail theme

### PR DESCRIPTION
**Pull request by DastardlySky**
### **Rainbow Trail**

rainbow_trail

Subtle flashing on typing errors:
rainbow_trail_error

Slick animated gradient on logo:
rainbow_trail_logo

Rainbow palette colour codes from: https://coolors.co/palette/33a8c7-52e3e1-a0e426-fdf148-ffab00-f77976-f050ae-d883ff-9336fd

This is my first ever pull request on GitHub and my first time making a theme so any feedback would be greatly appreciated!

### CODE REVIEW

**Comment by Miodec** [comment]
So, its just a white version of the `rgb` theme right

**Comment by Miodec** [comment]
I would apply the rainbow to other elements. Settings page looks a bit dull. Also i would stick with the pastel choice and pull down the background a bit and pull up the pure blacks. Also, the sub color needs to be different than the text. Lastly, flip test colors is not working at all.

**Comment by DastardlySky** [comment]
> I would apply the rainbow to other elements. Settings page looks a bit dull. Also i would stick with the pastel choice and pull down the background a bit and pull up the pure blacks. Also, the sub color needs to be different than the text. Lastly, flip test colors is not working at all.

I've applied the rainbow to all buttons (on hover):
button_rework

Here's what I've done to try and spruce up the settings page:
settings_rework

Here's the toned down black and whites:
rework animation

and here's a demo of typing:
rework typing

**Comment by DastardlySky** [comment]
> Can't tell which mode is active image

Is this enough contrast?:

image

**Comment by Miodec** [comment]
Yeah, thats better

**Comment by DastardlySky** [comment]
> Yeah, thats better

Is there anything else that needs to be amended?

**Review by typ-AhmedSleem — APPROVED** [review]
So cool theme

**Comment by DastardlySky** [comment]
> So cool theme

thank you 😁

**Review by FraneCaleta — APPROVED** [review]

**Pull request merged**
