### PR TITLE
Add content creator badge

### PR DESCRIPTION
**Pull request by Bruception**
### Description

Badge for note-worthy content creators:

Taeha Types
Alexotos
Glarses
etc.

Screen Shot 2022-06-25 at 11 02 30 AM

### CODE REVIEW

**Comment by Miodec** [comment]
I kinda like it but at the same time not 100% sure since people will say "oh, im a content creator" but they have like 10 videos and 3 subs. Whats the threshold here.

**Comment by Ferotiq** [comment]
I'm thinking 50k-100k subs minimum with at least some typing/keyboard focus on the channel.

**Comment by Miodec** [comment]
Change icon to <i class="fas fa-video"></i>

**Review by rizwanmustafa — APPROVED** [review]
LGTM IIW

**Pull request merged**
