### PR TITLE
Added 10 new quotes to the German pool

### PR DESCRIPTION
**Pull request by hanabo-mk**
Title, quotes in various lenghts from various sources

### CODE REVIEW

**Comment by Miodec** [comment]
Please translate the quotes so i can verify content is appropriate

**Comment by hanabo-mk** [comment]
Sure, here you are: 
- "You always have a choice, but sometimes the choice you make is not the choice you want to make."
- "I created a world in my dream that was more real than anything I've ever experienced while awake."
- "We are here to steal dreams, not make them come true. A dream can change a life, sometimes you have to be willing to sacrifice your own to change someone else's life."
- "It's not about who you are, it's about who you want to be. And if you choose to be a winner, you have to be willing to give it your all and risk everything to achieve your dreams."
- "Friendship means being there for someone no matter what. It means you're willing to give your all to help a friend, and you trust them when they help you."
- "Life is like a train ride, you don't know where you're going, but you can enjoy the scenery and the company of other people."
- "People who drive slow cars are either angry or boring."
- "Being smart is not knowing everything, but asking the right questions and making the right decisions."
- "Um klare Gedanken zu fördern, müssen wir lernen, uns auf das Wesentliche zu konzentrieren und uns von Ablenkungen und unnötigen Informationen fernzuhalten."
- "Unser Gehirn ist wie ein Computer: Je mehr unnötige Daten wir speichern, desto langsamer wird es."

**Comment by hanabo-mk** [comment]
Sure, here you are:
- "You always have a choice, but sometimes the choice you make is not the choice you want to make."
- "I created a world in my dream that was more real than anything I've ever experienced while awake."
- "We are here to steal dreams, not make them come true. A dream can change a life, sometimes you have to be willing to sacrifice your own to change someone else's life."
- "It's not about who you are, it's about who you want to be. And if you choose to be a winner, you have to be willing to give it your all and risk everything to achieve your dreams."
- "Friendship means being there for someone no matter what. It means you're willing to give your all to help a friend, and you trust them when they help you."
- "Life is like a train ride, you don't know where you're going, but you can enjoy the scenery and the company of other people."
- "People who drive slow cars are either angry or boring."
- "Being smart is not knowing everything, but asking the right questions and making the right decisions."
- "To foster clear thinking, we must learn to focus on what's important and stay away from distractions and unnecessary information."
- "Our brain is like a computer: the more unnecessary data we store, the slower it gets."

**Comment by monkeytypegeorge** [comment]
Continuous integration check(s) failed. Please review the failing check's logs and make the necessary changes. https://github.com/monkeytypegame/monkeytype/actions/runs/4098858935

**Comment by hanabo-mk** [comment]
fixed 'em

**Pull request merged**
