### PR TITLE
Add simplified chinese language support

### PR DESCRIPTION
**Pull request by ba1man**
### Description

Add simplified chinese language words support.

### CODE REVIEW

**Comment by monkeytypegeorge** [comment]
Continuous integration check(s) failed. Please review the failing check's logs and make the necessary changes. https://github.com/monkeytypegame/monkeytype/actions/runs/4981320697

**Comment by Miodec** [comment]
Have you tested this? Does it work as expected?

**Comment by ba1man** [comment]
> Have you tested this? Does it work as expected?

Yes, It is working as I expected. Although It has some converting-pinyin-to-chinese issues as typing, but it still works fine more or less. 
Snipaste_2023-05-15_22-39-24

**Comment by Miodec** [comment]
Yeah we have #4256 to fix pinyin.

**Pull request merged**
