### PR TITLE
Added Santali language

### PR DESCRIPTION
**Pull request by Prasanta-Hembram**
Added Santali Words from Foundational Language Tech: Santali Wordlist. O Foundation. CC0 1.0. (2021)

### CODE REVIEW

**Review by rizwanmustafa — CHANGES_REQUESTED** [review]
There are too many changes in the `_groups.json`. Fix the formatting to make it easy to review. Run `prettier` if possible.

**Review by rizwanmustafa — DISMISSED** [review]
As far as formatting and rules for languages go, it is fine now.

**Comment by Prasanta-Hembram** [comment]
Hi, @rizwanmustafa still learning git and coding ;-), now only capable of doing only basic tasks (simple merging and Pull etc.). I have never used prettier, but will. Can you guide me, if I did something wrong (below pic) .  
image

**Comment by rizwanmustafa** [comment]
The formatting has been fixed so don't worry about running Prettier anymore.

Everything else is correct. Now Miodec will handle this PR

**Review by Miodec — APPROVED** [review]
Thanks

**Pull request merged**
