### PR TITLE
style: make the .content grid more responsive (FFUV)

### PR DESCRIPTION
**Pull request by FFUV**
This addition makes the .content grid responsive by allowing the columns to automatically adjust based on the available width, ensuring better display on different screen sizes and devices.

### CODE REVIEW

**Comment by monkeytypegeorge** [comment]
Continuous integration check(s) failed. Please review the failing check's logs and make the necessary changes. https://github.com/monkeytypegame/monkeytype/actions/runs/8031639403

**Review by Ttrmaniacs — APPROVED** [review]
LGTM!

**Review by Ttrmaniacs — APPROVED** [review]
lgtm

**Comment by Miodec** [comment]
Please revert the nesting change.

**Comment by FFUV** [comment]
> Please revert the nesting change.

I gotchu

**Review by Ttrmaniacs — APPROVED** [review]
Nice👌

**Comment by FFUV** [comment]
@Miodec Finished can you review the pr?

**Comment by fehmer** [comment]
> LGTM!

do you rev

**Comment by FFUV** [comment]
@fehmer can you review?

**Comment by FFUV** [comment]
@Miodec REVIEW????

**Comment by Miodec** [comment]
???? Do you understand the concept of a weekend? 

And you still haven't reverted the nesting changes.

**Comment by FFUV** [comment]
> ???? Do you understand the concept of a weekend?
> 
> And you still haven't reverted the nesting changes.

Oh lol mb I work from home so dont got a lot to do lol :/ 
and wdym reverse nesting changes I changed it back to scss

**Comment by Miodec** [comment]
I mean you've unrapped all the scss nesting.

It went from 
```scss
.class {
  .class {
    //
  }
}
```

to 

```scss
.class .class {
  //
}
```

Please revert that. Also, don't self review your PRs.

**Comment by monkeytypegeorge** [comment]
Continuous integration check(s) failed. Please review the failing check's logs and make the necessary changes. https://github.com/monkeytypegame/monkeytype/actions/runs/8055976730

**Comment by FFUV** [comment]
@Miodec very very sorry but may you review now

**Comment by Miodec** [comment]
> @Miodec very very sorry but may you review now

You still havent reverted the nesting change.

**Comment by FFUV** [comment]
> > @Miodec very very sorry but may you review now
> 
> You still havent reverted the nesting change.

im done with this I dont understand what nesting change your talking about

**Pull request closed without merging**
