### PR TITLE
impr(themes): added and Created theme cy_red (StickminBruv)

### PR DESCRIPTION
**Pull request by StickminBruv**
### Description

Once again, I remade my PR about the new theme cy_red. I learned plenty much about my mistakes, and fixed them. The error color of my theme is now blue, so hopefully it gets approved. (that rhymes a little) I might have messed up on a thing or two, but I just added a new theme, not that big of an impact. Thanks!

image_2024-05-08_200319470

### Checks

- [ ] Adding quotes?
  - [ ] Make sure to include translations for the quotes in the description (or another comment) so we can verify their content.
- [x] Adding a language or a theme?
  - [ ] If is a language, did you edit `_list.json`, `_groups.json` and add `languages.json`?
  - [x] If is a theme, did you add the theme.css?
    - Also please add a screenshot of the theme, it would be extra awesome if you do so!
- [ ] Check if any open issues are related to this PR; if so, be sure to tag them below.
- [x] Make sure the PR title follows the Conventional Commits standard. (https://www.conventionalcommits.org for more info)
- [x] Make sure to include your GitHub username inside parentheses at the end of the PR title

Closes #

### CODE REVIEW

**Comment by monkeytypegeorge** [comment]
Continuous integration check(s) failed. Please review the failing check's logs and make the necessary changes. https://github.com/monkeytypegame/monkeytype/actions/runs/9010165206

**Comment by monkeytypegeorge** [comment]
Continuous integration check(s) failed. Please review the failing check's logs and make the necessary changes. https://github.com/monkeytypegame/monkeytype/actions/runs/9010245814

**Comment by monkeytypegeorge** [comment]
Continuous integration check(s) failed. Please review the failing check's logs and make the necessary changes. https://github.com/monkeytypegame/monkeytype/actions/runs/9023275474

**Comment by Miodec** [comment]
Thanks

**Comment by StickminBruv** [comment]
> Thanks

No problem, but just curious, how many possible themes can a person make? Like can someone just make one (me in this case), or you could make many?

**Pull request merged**
