### PR TITLE
fix: update the background image and hide the scrollbar in the funbox space_balls (yunfachi)

### PR DESCRIPTION
**Pull request by yunfachi**
### Checks

- [ ] Adding a language or a theme?
    - [ ] If is a language, did you edit `_list.json`, `_groups.json` and add `languages.json`?
    - [ ] If is a theme, did you add the theme.css?
        - Also please add a screenshot of the theme, it would be extra awesome if you do so!
- [x] Check if any open issues are related to this PR; if so, be sure to tag them below.
- [x] Make sure the PR title follows the Conventional Commits standard. (https://www.conventionalcommits.org for more info)
- [x] Make sure to include your GitHub username inside parentheses at the end of the PR title

The first commit updates the background image URL, resolving an issue where the previous GIF was not loading due to the gfycat service being discontinued.
The second commit hides the Y-axis scrollbar that appears after rotating the page using `transform: rotateX(35deg);`.

### CODE REVIEW

**Comment by Miodec** [comment]
Which scrollbar are you talking about? Not sure if its needed.

**Comment by yunfachi** [comment]
> Which scrollbar are you talking about? Not sure if its needed.

The page length increases when using the 'transform rotate' property. This is because the 'transform rotate' is applied to the 'main' element, causing its lower part to come closer to the screen. As a result, the lower part occupies more space on the page, leading to an increased page size and the appearance of a scrollbar. My current solution of using 'overflow-y: hidden' is somewhat crude, as it suppresses the scrollbar. An alternative approach is to apply the 'transform rotate' to the '#typingTest' div, which would solve the problem but might significantly alter the appearance of 'space_balls'.
### without rotation (the page cannot be scrolled down)
without rotation
### with rotation (the page can be scrolled down, but only the background will be visible)
with rotation

**Comment by Miodec** [comment]
Right, i zoomed my browser in a bit and can see the scrollbar - but how are you going to reach the footer if you disallow scrolling?

**Comment by Miodec** [comment]
So.. is the overflow change really needed then? It looks exactly the same as live.

**Comment by yunfachi** [comment]
> So.. is the overflow change really needed then? It looks exactly the same as live.

It doesn't work for me without overflow. 1920x1080, firefox 121.0b5
In live I can scroll down like in the screenshot

**Review by Miodec — APPROVED** [review]

**Pull request merged**
