### PR TITLE
create new theme: note dark

### PR DESCRIPTION
**Pull request by mynimi**
### Description
Created a new theme with a few small additions
Features:
- a notepad style overlay on the background (it will overlay background images too)
- error strike-through instead of underline
- fun little dot transformation on already typed text
- some more rounded corners

Screenshot 2022-12-27 172447

### CODE REVIEW

**Comment by mynimi** [comment]
actually, realized I've forgotten to fix the dot colors for the colormode and they display wrong colors, and the color isn't properly working in Firefox.
Was about to just commit the fix, but then I thought, maybe the entire thing might be better suited in the funbox? 
"dots" funbox that turns the previous letters into dots. I could split this up into theme and the text effect as a funbox mode, would that be better suited and if I close this and make two separate pull requests for that?

**Review by AzkaPrata — COMMENTED** [review]
Great, send me screenshot all page from monkey type

**Comment by Miodec** [comment]
What does it look like with a custom background applied?

**Comment by mynimi** [comment]
The image is placed behind the lines right now. Adjusting it so it's behind the custom background is only a matter of adding z-index to it thugh, so if it shouldn't interfere with the custom background in any way, I could make that adjustment.

image

image

**Comment by Miodec** [comment]
On top is fine

**Pull request merged**
