### PR TITLE
impr(quotes): add English and Hindi quotes (pantharshit007)

### PR DESCRIPTION
**Pull request by pantharshit007**
### Description

**Quotes translation** 

> “Dreams are not those that you see while sleeping, dreams are those that don’t let you sleep.”

### Checks

- [x] Adding quotes?
  - [x] Make sure to include translations for the quotes in the description (or another comment) so we can verify their content.
- [ ] Adding a language or a theme?
  - [ ] If is a language, did you edit `_list.json`, `_groups.json` and add `languages.json`?
  - [ ] If is a theme, did you add the theme.css?
    - Also please add a screenshot of the theme, it would be extra awesome if you do so!
- [ ] Check if any open issues are related to this PR; if so, be sure to tag them below.
- [ ] Make sure the PR title follows the Conventional Commits standard. (https://www.conventionalcommits.org for more info)
- [x] Make sure to include your GitHub username inside parentheses at the end of the PR title

Closes #

### CODE REVIEW

**Comment by Miodec** [comment]
Please resolve conflicts.

**Comment by pantharshit007** [comment]
> Please resolve conflicts.

could you check now.

**Comment by Miodec** [comment]
How did you merge? It seems like the diff is much bigger than it should be

**Comment by pantharshit007** [comment]
> How did you merge? It seems like the diff is much bigger than it should be

yeah I was also thinking the same, so should I revert it all and once everything is sorted out then do the pr

(I think some extension messed up somewhere)

**Comment by Miodec** [comment]
Yeah, try redoin the PR.

**Comment by monkeytypegeorge** [comment]
Continuous integration check(s) failed. Please review the failing check's logs and make the necessary changes. https://github.com/monkeytypegame/monkeytype/actions/runs/8239906858

**Comment by monkeytypegeorge** [comment]
Continuous integration check(s) failed. Please review the failing check's logs and make the necessary changes. https://github.com/monkeytypegame/monkeytype/actions/runs/8240026571

**Pull request closed without merging**
