### PR TITLE
Quotes and words in Kannada language 

### PR DESCRIPTION
**Pull request by ajay-vishnu**

### CODE REVIEW

**Comment by monkeytypegeorge** [comment]
Continuous integration check(s) failed. Please review the failing check's logs and make the necessary changes. https://github.com/monkeytypegame/monkeytype/actions/runs/5769621329

**Comment by ajay-vishnu** [comment]
@monkeytypegeorge, it's fixed now. Let me know if there needs to be any other changes to be made.

**Comment by monkeytypegeorge** [comment]
Continuous integration check(s) failed. Please review the failing check's logs and make the necessary changes. https://github.com/monkeytypegame/monkeytype/actions/runs/5787737343

**Review by Miodec — APPROVED** [review]
Thanks

**Pull request merged**
