### PR TITLE
Added a bunch of quotes

### PR DESCRIPTION
**Pull request by holyhearted**
### Description

Added 5 new quotes to English quote .json

Closes #

### CODE REVIEW

**Comment by Bruception** [comment]
Please fix quote lengths

**Comment by holyhearted** [comment]
fixed

**Comment by Bruception** [comment]
Merge conflicts

**Comment by holyhearted** [comment]
done(?) i’m horrible at using git

**Comment by Bruception** [comment]
Invalid quote IDs

**Comment by holyhearted** [comment]
IDs should be proper now, added a few more quotes also

**Review by Bruception — APPROVED** [review]
lgtm

**Pull request merged**
