### PR TITLE
feat(language): add special lazy mode replacement to serbian (while1618)

### PR DESCRIPTION
**Pull request by while1618**
### Description

A lot of people when writing online don't bother to type letters like "ž š č", and we simply type them as "z s c". I made a 
serbian_latin_simplified, which is basically all words from serbian_latin, but just without those letters.

### Checks

- [ ] Adding quotes?
  - [ ] Make sure to include translations for the quotes in the description (or another comment) so we can verify their content.
- [x] Adding a language or a theme?
  - [x] If is a language, did you edit `_list.json`, `_groups.json` and add `languages.json`?
  - [ ] If is a theme, did you add the theme.css?
    - Also please add a screenshot of the theme, it would be extra awesome if you do so!
- [x] Check if any open issues are related to this PR; if so, be sure to tag them below.
- [x] Make sure the PR title follows the Conventional Commits standard. (https://www.conventionalcommits.org for more info)
- [x] Make sure to include your GitHub username inside parentheses at the end of the PR title

### CODE REVIEW

**Comment by fehmer** [comment]
Can we use lazy mode for this?

**Comment by while1618** [comment]
I was not aware of this mode. So if I set `"noLazyMode": false` in `serbian_latin.json`, it should automatically change `ž` to `z`? Or I need to make some other changes? Also, one more thing, letter `đ` in Serbian is usually written as `dj`, will this mode be able to detect that?

**Comment by fehmer** [comment]
If you remove the `"noLazyMode": true,` from the serbian_latin language file it should be possible to activate lazy mode in the settings or using the command line.
In lazy mode accents get converted. For all languages [these rules](https://github.com/monkeytypegame/monkeytype/blob/bfc9500d324bdc8da58ec8fe1f6cd8158aa79833/frontend/src/ts/test/lazy-mode.ts#L1) apply.
You can specify language specific replacements e.g.  `đ` to `dj` within the language file with `additionalAccents`. I did this a while back for [german](https://github.com/monkeytypegame/monkeytype/blob/bfc9500d324bdc8da58ec8fe1f6cd8158aa79833/frontend/static/languages/german.json#L4C4-L4C21) language files.

**Comment by while1618** [comment]
Great, thanks for the explanation. Should I create a new PR for this, or can I just make changes here?

**Comment by fehmer** [comment]
you can just make the changes in this pr

**Review by fehmer — APPROVED** [review]

**Review by Miodec — APPROVED** [review]
Thanks

**Pull request merged**
