### PR TITLE
Updated Quote Submission Button Icon

### PR DESCRIPTION
**Pull request by UnrealApex**
### Description
I feel that the quote submission button icon(Font Awesome `chevron-right`) doesn't properly convey the idea of submission:
Screenshot 2022-08-21 11 27 24 AM
The Font Awesome `right-to-bracket` icon better conveys this in my opinion:
image

What do you think? Is it better just to not have a submission button at all and have quote reviews be submitted when the user leaves the quote modal?
I apologize for not having a screenshot of the new icon on the site, I don't have access to my dev machine right now.

### CODE REVIEW

**Comment by rizwanmustafa** [comment]
Yo, there are so many merge commits that could have been avoided if you reset your branch instead of merging. Please avoid them next time.

**Comment by Miodec** [comment]
I think out of the two i still prefer the chevron

**Comment by UnrealApex** [comment]
> I think out of the two i still prefer the chevron

I understand, thank you!

**Comment by UnrealApex** [comment]
> Yo, there are so many merge commits that could have been avoided if you reset your branch instead of merging. Please avoid them next time.

Sure. I believe when merging PRs, the extra commits are ignored and not shown in Git's history so it should be fine.

**Pull request closed without merging**
