### PR TITLE
Added hinglish under hindi (not as separate language)

### PR DESCRIPTION
**Pull request by KParthSingh**
### Description

Closes #

### CODE REVIEW

**Comment by rizwanmustafa** [comment]
The `bcp47` field's value seems incorrect. This is not Indian english but Hindi written in Latin script.

**Comment by rizwanmustafa** [comment]
@Miodec there is no proper bcp47 value for Roman Hindi (Hindi written in Latin script). So I am thinking of removing the attribute from the json file. What do you say?

**Comment by KParthSingh** [comment]
> @Miodec there is no proper bcp47 value for Roman Hindi (Hindi written in Latin script). So I am thinking of removing the attribute from the json file. What do you say?

It's your choice 🤷🏻‍♂️

**Comment by Miodec** [comment]
> @Miodec there is no proper bcp47 value for Roman Hindi (Hindi written in Latin script). So I am thinking of removing the attribute from the json file. What do you say?

If there is no proper value then remove it

**Review by Miodec — APPROVED** [review]

**Pull request merged**
