### PR TITLE
fix(typing): pinyin input (hakujitsu)

### LINKED ISSUE #4230: Can not type traditional Chinese
### Did you clear cache before opening an issue?

- [X] I have cleared my cache

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Does the issue happen when logged in?

Yes

### Does the issue happen when logged out?

Yes

### Does the issue happen in incognito mode when logged in?

Yes

### Does the issue happen in incognito mode when logged out?

Yes

### Account name

stevencheng

### Account config

_No response_

### Current Behavior

when I use "pinyin" input , I can't type any Chinese word.
like this 
CleanShot 2023-04-27 at 09 09 21

### Expected Behavior

because Chinese type need to transcoding, but monkeytype seems not work.
So, my expected is Chinese type transcoding is work.

### Steps To Reproduce

1. chose traditional Chinese type test
2. chose pinyin input source
3. type "taiyang" + space need to show "太陽“，type "baozi" need to show "包子".

### Environment

- OS: Mac OS Ventura 13.3.1
- Browser: Safari 
- Browser Version: 16.4

### Anything else?

none

### PR DESCRIPTION
**Pull request by hakujitsu**
### Description

Added support for Pinyin typing (closes #4230)

- Ignored spaces when typing Chinese and composition has not ended
- Added additional check to ensure all characters are parsed by `handleChar` before ending the test (since Chinese input can result in multiple characters being added (re_dai_yu_lin -> 熱帶雨林)
- Added an additional check when the number of characters decreases to handle the conversion of pinyin to Chinese characters

https://user-images.githubusercontent.com/54730257/236153450-7482908d-dc79-4cee-95eb-388a06e710d6.mov

### Testing

Conducted some manual testing using both pinyin input method and handwriting input method.

If anyone could do additional testing using other input methods (e.g. Cangjie and Wubi), that would be most appreciated, as I am unfamiliar with how to use them.

### CODE REVIEW

**Comment by monkeytypegeorge** [comment]
Continuous integration check(s) failed. Please review the failing check's logs and make the necessary changes. https://github.com/monkeytypegame/monkeytype/actions/runs/4880841373

**Comment by Miodec** [comment]
Any update? @hakujitsu

**Comment by Miodec** [comment]
@hakujitsu have you had a chance to test this?

**Review by Miodec — APPROVED** [review]

**Comment by Miodec** [comment]
Tested by Discord server members

**Pull request merged**
