### PR TITLE
feat(themes): add suisei theme (@moonbamijam)

### PR DESCRIPTION
**Pull request by moonbamijam**
### Description

Add a new theme called suisei inspired from the Japanese VTuber from hololive, Hoshimachi Suisei.

This is also a attempt to improve the past version of this theme which is,
- #5793 

### Checks

- [ ] Adding quotes?
  - [ ] Make sure to include translations for the quotes in the description (or another comment) so we can verify their content.
- [x] Adding a language or a theme?
  - [ ] If is a language, did you edit `_list.json`, `_groups.json` and add `languages.json`?
  - [x] If is a theme, did you add the theme.css?
    - Also please add a screenshot of the theme, it would be extra awesome if you do so!
- [ ] Check if any open issues are related to this PR; if so, be sure to tag them below.
- [x] Make sure the PR title follows the Conventional Commits standard. (https://www.conventionalcommits.org for more info)
- [x] Make sure to include your GitHub username prefixed with @ inside parentheses at the end of the PR title.

### Screenshots

image
image
image
image

### Flip test colors & colorful mode

image
image
image

### CODE REVIEW

**Comment by moonbamijam** [comment]
> Im not sure about the top right nav bar styling here image image
> 
> Also text color cannot be colored.

updated ver commited :)

**Comment by Miodec** [comment]
image

Current nav setup seems incoherent. Some icons have a background, some dont. Some are rounded at the top, some arent. 3 different colors are used.

Also, the logo is cut off at the bottom, and the top text is not visible.

**Comment by moonbamijam** [comment]
> image
> Current nav setup seems incoherent. Some icons have a background, some dont. Some are rounded at the top, some arent. 3 different colors are used.
> 
> Also, the logo is cut off at the bottom, and the top text is not visible.

### Nav updated ver

image

### Other changes

- slightly adjusted text color
- remove text gradient in logo due to it being cut off at the bottom

### Full view

image
image
image

**Comment by fehmer** [comment]
hi @moonbamijam ,  

i liked the gradient on the header. this should fix the cut text issue:

```css
header #logo .text {
  background: linear-gradient(120deg, var(--main-color), var(--sub-color));
  background-clip: text;
  -webkit-background-clip: text;
  color: transparent;
  padding-bottom: 0.1em;
}

header #logo .text .top {
  color: var(--main-color);
}
```

**Comment by moonbamijam** [comment]
### Update to logo

image


### On focus

image

Credits to @fehmer, super thanks!!!

**Comment by Miodec** [comment]
The animation on the nav buttons is causing some clicks to be missed. If you hover over the very bottom of the button, the animation runs, but clicking the button does nothing.

**Comment by moonbamijam** [comment]
> The animation on the nav buttons is causing some clicks to be missed. If you hover over the very bottom of the button, the animation runs, but clicking the button does nothing.

### Update

- change the value of transform property from translate to scale

**Comment by Miodec** [comment]
Thanks

**Pull request merged**
