### PR TITLE
Setup

### PR DESCRIPTION
**Pull request by m7mdtiger**
Fixing **webpack-cli**  [issue](https://github.com/webpack/webpack/issues/15951) & type error.

### CODE REVIEW

**Comment by Miodec** [comment]
Does it actually fix any isues in MT?

**Comment by m7mdtiger** [comment]
> Does it actually fix any isues in MT?

I meant to simplify the work of other contributors ^^

**Comment by Miodec** [comment]
I mean, i wouldn't be able to develop if it didnt work locally - what issues were you running into.

**Comment by Miodec** [comment]
Please remove the unrelated challenge controller changes. Also, shouldnt the version number change include changes in package-lock file? Did you just manually up the version number instead of using the install command?

**Comment by m7mdtiger** [comment]
> Please remove the unrelated challenge controller changes. Also, shouldnt the version number change include changes in package-lock file? Did you just manually up the version number instead of using the install command?

I used the install command. But package-lock file got messed up before that as I had to install typescript for MT locally as the global one didn't work! At that time, I was primarily focused on setting up the project so I didn't make things separately :v
I am not sure how important is that ?

**Comment by Miodec** [comment]
Yes, its important. I've installed webpack-cli 4.10 and pushed to master. Going to close your pr, thanks though.

Here's what happens to the lock file when installed correctly: https://github.com/monkeytypegame/monkeytype/commit/369be4db76178790665aefe29af2ad52153b8f85

**Comment by m7mdtiger** [comment]
> Yes, its important. I've installed webpack-cli 4.10 and pushed to master. Going to close your pr, thanks though.
> 
> Here's what happens to the lock file when installed correctly: [369be4d](https://github.com/monkeytypegame/monkeytype/commit/369be4db76178790665aefe29af2ad52153b8f85)

Perfect, thank you.

**Pull request closed without merging**
