### PR TITLE
added a new theme hacker.css

### PR DESCRIPTION
**Pull request by isa-2004**
### Screenshot of Theme:

image

image

image

### CODE REVIEW

**Comment by rizwanmustafa** [comment]
Please add more screenshots with different settings as demonstrated in the following PR: #2294

**Comment by isa-2004** [comment]
> Please add more screenshots with different settings as demonstrated in the following PR: #2294

Yes I did.

**Comment by Miodec** [comment]
Duplicate of the matrix theme

**Comment by isa-2004** [comment]
> Duplicate of the matrix theme

not at all. its different. plase check properly i have given screenshots.

**Comment by isa-2004** [comment]
> Please add more screenshots with different settings as demonstrated in the following PR: #2294

yes i added screenshots as described. thanks!

**Comment by rizwanmustafa** [comment]
> > Duplicate of the matrix theme
> 
> not at all. its different. plase check properly i have given screenshots.

Unfortunately it's quite similar to the theme "Matrix" and since we already have many themes on Monkeytype, we now only entertain truly unique and intriguing themes. I am sorry that your theme got rejected but so did mine.

Thanks for the contribution though.

**Comment by isa-2004** [comment]
> > > Duplicate of the matrix theme
> > 
> > 
> > not at all. its different. plase check properly i have given screenshots.
> 
> Unfortunately it's quite similar to the theme "Matrix" and since we already have many themes on Monkeytype, we now only entertain truly unique and intriguing themes. I am sorry that your theme got rejected but so did mine.
> 
> Thanks for the contribution though.

I request you to check Matrix theme on normal mode. Texts have really bad contrast and is not clearly visible. that is why I made this theme. I have given a screenshot of how matrix looks. Please check!

**Comment by isa-2004** [comment]
> Duplicate of the matrix theme

This is how Matrix looks like:
image

And this is how my theme looks like:
image

I literally can't type properly in matrix theme...

**Comment by isa-2004** [comment]
> > One thing you could do is to use my color theme and update Matrix. Then there is no need of adding my theme. Or you can delete matrix theme and add this one. Let me know your thoughts! :)
> 
> I am not the one who approves/rejects themes. It's Miodec. If you are unsatisfied with the decision, I suggest you talk with him in the #development channel of the Discord server of the website. https://discord.com/invite/monkeytype

ok thanks!

**Comment by Miodec** [comment]
image
matrix with flip test colors on

**Pull request closed without merging**
