### PR TITLE
fix: save confidence mode after setting stopOnError and vice versa

### LINKED ISSUE #4638: When stop on word disables confidence mode, make sure confidence mode state is saved

### PR DESCRIPTION
**Pull request by mohanadft**
### Description

Saving config to localStorage after resetting some values.

Closes #4638

### CODE REVIEW

**Comment by mohanadft** [comment]
Hi @Miodec 
```ts
  config.confidenceMode = cm;
  if (config.confidenceMode !== "off") {
    config.freedomMode = false;
    config.stopOnError = "off";
  }
  saveToLocalStorage("confidenceMode", nosave);
  saveToLocalStorage("stopOnError", nosave);
```

I think, in any of set functions, if the condition is true, you have to save all of what you are trying to reset?

**Comment by Miodec** [comment]
> I think, in any of set functions, if the condition is true, you have to save all of what you are trying to reset?

Not sure what you mean here

**Comment by mohanadft** [comment]
> Not sure what you mean here, PR is good though

In the code I attached above, `freedomMode` will be reset if the condition is true, should it be saved to localstorage after that? this is the same as `confidenceMode` & `stopOnError`

**Comment by Miodec** [comment]
Yeah, ideally we should save everything that we change.

**Comment by mohanadft** [comment]
Good, shall I save them on this PR?

**Comment by mohanadft** [comment]
> Good, shall I save them on this PR and make some refactoring?

**Comment by Miodec** [comment]
Yeah

**Comment by mohanadft** [comment]
You can merge now

**Pull request merged**
