### PR TITLE
impr(quotes): add Hindi quotes

### PR DESCRIPTION
**Pull request by Anasdevs**
### Description
Added 10 new Hindi quotes

### CODE REVIEW

**Comment by monkeytypegeorge** [comment]
Continuous integration check(s) failed. Please review the failing check's logs and make the necessary changes. https://github.com/monkeytypegame/monkeytype/actions/runs/7371877078

**Comment by Anasdevs** [comment]
Fixed the incorrect character counts of the quotes

**Comment by Miodec** [comment]
Please provide translations and remove the unrelated theme addition.

**Review by Anasdevs — COMMENTED** [review]
Actually I added the quotes by "Kabir Das", so as i can see there's no translation needed for these quotes as they're already in hindi. 
Also i've removed the unrelated theme changes in this pr. 
Please tell me if there's any changes required.

**Comment by monkeytypegeorge** [comment]
Continuous integration check(s) failed. Please review the failing check's logs and make the necessary changes. https://github.com/monkeytypegame/monkeytype/actions/runs/7474531752

**Comment by monkeytypegeorge** [comment]
Continuous integration check(s) failed. Please review the failing check's logs and make the necessary changes. https://github.com/monkeytypegame/monkeytype/actions/runs/7474672349

**Comment by Miodec** [comment]
By translations i mean comment the english versions so i can verify their content is appropriate

**Comment by Anasdevs** [comment]
> By translations i mean comment the english versions so i can verify their content is appropriate

Can you tell me where i have to add the translations?

**Comment by Miodec** [comment]
You can just commeny here

**Comment by Anasdevs** [comment]
> You can just commeny here

here are the translations  


{ "id": 40, "translation": "What is not broken cannot be joined, what is joined cannot be broken. When both are the same, then why take offense at dust." },

{ "id": 41, "translation": "The illusion died, not the mind, the world is illusory. Leave all this illusion, scattered everywhere."},

{ "id": 42, "translation": "As I walked looking for evil, I found none. When I searched within myself, I found no one more evil than me."},

{ "id": 43, "translation": "A sage's food leads to sagehood, it matches everyone's disposition. As one eats so he becomes, thus says the wise one."},

{ "id": 44, "translation": "Guru and Govind both stand before me, to whom shall I first bow? I'll first bow to the Guru, who introduced me to Govind."},

{ "id": 45, "translation": "Even if one is big, so what? He's like a date tree. No shade for travelers, fruit is hard to reach."},

{ "id": 46, "translation": "The enlightened are all virtuous, not so for women. Those who understand virtue, they alone are virtuous."},

{ "id": 47, "translation": "If it's a diamond, discard it. If it's useless, abandon it. If it's an ordinary stone, break it. But show the true path of your Guru."},

{ "id": 48, "translation": "Mixing water in deep water, and putting out a lamp. What goes out without flickering, how can it be rekindled?"},

{ "id": 49, "translation": "The thread of love, don't break by pulling hard. Once broken it won't join again, once tied it will get entangled."}

**Review by Miodec — APPROVED** [review]

**Pull request merged**
