### PR TITLE
feat(theme): added tangerine theme (devdenisalex)

### PR DESCRIPTION
**Pull request by devdenisalex**
## this theme gives monkeytype a light orange look based on the colors of a tangerine 

Screenshot_8
Screenshot_7
Screenshot_6
Screenshot_5

### CODE REVIEW

**Comment by Miodec** [comment]
Text color needs to be either black or white (can have a very slight tint)

**Comment by devdenisalex** [comment]
alr, done :)

**Comment by monkeytypegeorge** [comment]
Continuous integration check(s) failed. Please review the failing check's logs and make the necessary changes. https://github.com/monkeytypegame/monkeytype/actions/runs/7886037790

**Comment by monkeytypegeorge** [comment]
Continuous integration check(s) failed. Please review the failing check's logs and make the necessary changes. https://github.com/monkeytypegame/monkeytype/actions/runs/7886059685

**Comment by devdenisalex** [comment]
image
hope this is enough

oh and also it keeps telling that "Monkey CI / ci-assets (pull_request)" failing. idk how any of this works so im not really sure how to fix it cus its my first time

**Comment by Miodec** [comment]
Thanks

**Comment by Miodec** [comment]
Nevermind, reverting - errors are invisible.

image

**Pull request merged**
