### PR TITLE
impr(quote): Add a quote

### PR DESCRIPTION
**Pull request by mohanadft**
### Description

I've added a new quote for Simon Sinek. [Source](https://youtu.be/lFMrrIxOU4Q?si=tVh7VNlXRvTR2yMW&t=425)

Here is the added quote:
```json
{
      "text": "If you want to be an elite warrior, you better get really, really good at helping the person to the left of you and helping the person to the right of you.",
      "source": "Simon Sinek",
      "length": 155,
      "id": 6990
}
```

### CODE REVIEW

**Comment by mohanadft** [comment]
Note: This is just to test my contribution. In the meantime, I am looking for issues that I can resolve them.
Thanks

**Review by DevChaudhary78 — APPROVED** [review]

**Review by joeBash — APPROVED** [review]

**Comment by mohanadft** [comment]
> I feel like adding a few more sentences that he said afterwards would make a tiny bit more sense and give some context.

Yes, it make sense.

**Review by Miodec — APPROVED** [review]
Thanks

**Review by DevChaudhary78 — COMMENTED** [review]
Awesome

**Pull request merged**
