### PR TITLE
fix(ci): update formatting workflow commit message (unrealapex)

### PR DESCRIPTION
**Pull request by unrealapex**
### Description
Ensure that commit message meets Conventional Commits specification adopted recently.

### Checks

- [ ] Adding a language or a theme?
    - [ ] If is a language, did you edit `_list.json`, `_groups.json` and add `languages.json`?
    - [ ] If is a theme, did you add the theme.css?
        - Also please add a screenshot of the theme, it would be extra awesome if you do so!
- [x] Check if any open issues are related to this PR; if so, be sure to tag them below.
- [x] Make sure the PR title follows the Conventional Commits standard. (https://www.conventionalcommits.org for more info)
- [x] Make sure to include your GitHub username inside round brackets at the end of the PR title

### CODE REVIEW

**Comment by unrealapex** [comment]
I feel like `refactor` type would not really make sense here. What do you think about using the `ci` type instead?

**Comment by Miodec** [comment]
Why not?

**Comment by unrealapex** [comment]
I would like to think that refactors would be actual *code changes* rather than just formatting fixes. Taking a look at the Angular commit style guide(which Conventional Commits is based off of), it suggests using `style`. I have seen `format` used in some larger projects. However, if you feel that using `refactor` would be a better choice, that is fine.

**Comment by Miodec** [comment]
In my mind, refactoring is keeping the same functionality but just changing how the code looks / structure and so on. I think refactor fits.

**Comment by unrealapex** [comment]
You are correct about refactoring. Though I feel like refactoring is more related to code structure rather than code style. I will change it to `refactor`.

**Review by Miodec — APPROVED** [review]

**Comment by Miodec** [comment]
Thanks

**Comment by unrealapex** [comment]
No problem, Miodec.

**Pull request merged**
