### PR TITLE
Adding Spanish 646K language json

### PR DESCRIPTION
**Pull request by AntikoreDev**
### Description

My PR is just adding an almost complete spanish dictionary with 646k words, including conjugated verbs. Plurals are not included at all.

### CODE REVIEW

**Comment by Miodec** [comment]
I feel like this is a bit of an overkill - I wouldn't expect anyone to realistically use this.

**Comment by Miodec** [comment]
> english 450k and french 600k

Yeah, i guess. Can you rename this file to 650k?

**Comment by AntikoreDev** [comment]
Sorry for lasting too long, it's done now

**Comment by monkeytypegeorge** [comment]
Continuous integration check(s) failed. Please review the failing check's logs and make the necessary changes. https://github.com/monkeytypegame/monkeytype/actions/runs/5211898073

**Comment by JArdelian** [comment]
I am going to use it. Thank you so much. I requested this long ago, since I had not been able to submit the whole list.

**Pull request merged**
