### PR TITLE
impr(quotes): added 23 portuguese quotes (nivaldinho-jpg)

### PR DESCRIPTION
**Pull request by Nivaldinho-jpg**
Added more quotes

### Description
Quote translation

68. "He launched himself, in part, into doctrinal experiments, exchange banks and workers' associations, in other words, into a movement in which he gave up on revolutionizing the old world with his great store of own resources; he tried, rather, to consummate his redemption behind society's back, privately, within his restricted conditions of existence, and therefore necessarily failed."
69. "As long as the domination of the bourgeois class was not fully organized, as long as it did not acquire its pure political expression, and where it did appear, it could not take on that dangerous version which transforms every struggle against state power into a struggle against capital."
70. "The Nazis and their fanatical followers in the pedagogical and university world have armed themselves with a manly pen to vigorously reject the pale and sickly figure of the anemic theoretician, a reasoner who practices philosophy as one practices religion, having dedicated his life to the study of abstractions to the detriment of the concreteness of reality."
71. "To begin with, Marx defines a commodity as the specific social form that the product of labor takes when it is not used for the producer's own consumption or for occasional exchanges, and when it is already produced for the market."
72. "Capital has fetishistic power not only because it takes the form of merchandise or money, but because it commands the labor process in such a way as to present itself as an element of production that is also capable of producing value."
73. "Deprived of ownership of the means of production, the individual no longer fully recognizes himself in the product of his work and only has access to it later, when he buys it on the market."
74. "Tremble, ruling classes, in the face of a communist revolution. The proletarians have nothing to lose with it apart from their shackles. They have a world to gain. Proletarians of all countries, unite!"
75. "However, Stalin's speech to the plenum, like Molotov's, offered a mixed message. He called for vigilance on the one hand and advised moderation on the other. Not every Party member with a history of oppositionism was an enemy."
76. "A careful reading of the plenum, however, suggests that Stalin intended a ruthless, albeit limited, attack on the former oppositionists, along with a new effort to educate, integrate and empower the lower ranks of the Party. But whatever he intended, repression and democracy were intertwined. The hunt for oppositionists, fueled by new elections and attacks on leaders, spread to all party and trade union organizations."
77. "After the June 1953 uprising in the GDR, in response to the imposition of new labor standards by the government, the Soviet Union began to return the East German factories it had taken over as reparations, and to provide vital economic support, mainly cheap raw materials, including oil."
78. "So far they have not been able to have a more consistent political influence, either nationally or globally, due to difficulties in translocal articulations and the fact that the liberal democratic political system is monopolized by parties that, on both the right and the left, tend to be hostile to the autonomy of social movements."
79. "The movie leaves no doubt that capitalist consumerism and corporations - or rather, the Buy n Large megacorporation - were responsible for this devastation. And when we finally meet the human beings in their exile off the planet, they are childish and obese, interacting through their little screens, transported back and forth by huge floating chairs and sucking an indeterminate amount of goo from plastic cups through straws."
80. "So we can take this reflection even further: the thousands of people who die every day because they have nothing to eat, victims of the capitalist system that prioritizes the accumulation of the very few over the misery and poverty of millions of people. Isn't this a system of naturalized social murder? Has our ability to feel been destroyed by capitalism? Why is this characteristic only typical of totalitarian governments? Or is it just ideology?"
81. "No, no, no; it was all so absurd! Only a millionaire could live a life like that; Marques would be satisfied with much less. For example, he'd be fine if he only worked four hours a day and earned around five thousand reais a month."
82. "It was with bitter surprise that he found himself ready to start work. It was time to return to reality. Harsh reality. Sad reality. Almost unbearable reality. He lowered his head to take a look at himself. Once again, he found himself in that ridiculous, stained, patched, creased uniform that had belonged to who knows how many other poor bastards before him."
83. "Beyond the store doors, in the street, the hues of dusk were already beginning to emerge. The blue sky was darkening in the east and turning orange in the west."
84. "Soon night would fall, soon the supermarket would close; time was running out against Marques and Pedro. Eager to put into practice the plan that would perhaps make them rich in the long run, they didn't even consider the possibility of gradually collecting the thousand reais they needed: it had to be all at once, it had to be all today."
85. "Hand in hand, groping, the young man walked carefully, so as not to bump into the piles of beer crates and soda bales."
87. "He advanced very slowly, without making the slightest sound, and put his head near the entrance to the first room, peering inside, initially with one eye, at a closed angle that allowed him to see only the tip of a closet, positioned in the left corner of the room."
88. "My youth full of vices was dead. I was on my way to maturity, and the more I advanced in years, the more shamefully I allowed myself to be contaminated by vain things."
89. "My spirit protested vehemently against all my old ghosts, and I tried hard to push the swarm of unworthy images that fluttered around me away from my mind's eye in one fell swoop. But they had only just dispersed, and in the twinkling of an eye, they came back, compact and violent, blinding me."
90. "What folly not to know how to love men as they are! Foolish of those who can't bear the human condition. That's how I felt back then, and that's why I was restless, moaning, crying and agitated, without finding peace, without knowing what to do."
91. "Everything was unbearable, even the daylight."
92. "It seemed strange to me that life should go on for other mortals, since the person I had loved was dead, as if she should never die."
93. "Following the normal course program, I came across the book by a certain Cicero, whose language - but not his heart - is almost unanimously admired."
94. "Suddenly all my vain hopes seemed hopeless."
95. "Philosophers have only interpreted the world in different ways. What matters is transforming it."

### Checks

- [ ] Adding a language or a theme?
    - [ ] If is a language, did you edit `_list.json`, `_groups.json` and add `languages.json`?
    - [ ] If is a theme, did you add the theme.css?
        - Also please add a screenshot of the theme, it would be extra awesome if you do so!
- [x] Check if any open issues are related to this PR; if so, be sure to tag them below.
- [x] Make sure the PR title follows the Conventional Commits standard. (https://www.conventionalcommits.org for more info)
- [x] Make sure to include your GitHub username inside parentheses at the end of the PR title

Closes #

### CODE REVIEW

**Comment by Miodec** [comment]
Please provide translations so that the quote content can be verified.

**Comment by Nivaldinho-jpg** [comment]
> Please provide translations so that the quote content can be verified.

done

**Comment by Miodec** [comment]
Remove 86

**Comment by monkeytypegeorge** [comment]
Continuous integration check(s) failed. Please review the failing check's logs and make the necessary changes. https://github.com/monkeytypegame/monkeytype/actions/runs/7342034518

**Comment by monkeytypegeorge** [comment]
Continuous integration check(s) failed. Please review the failing check's logs and make the necessary changes. https://github.com/monkeytypegame/monkeytype/actions/runs/7561112393

**Comment by Miodec** [comment]
IDs 82 and 83 have incorrect length fields. Also please resolve merge conflicts.

**Comment by Nivaldinho-jpg** [comment]
> IDs 82 and 83 have incorrect length fields. Also please resolve merge conflicts.

The lenght fields have been fixed. I don't know exactly how were the merge conflicts, but I tried to fix it. Let me know if its still not working

**Comment by monkeytypegeorge** [comment]
Continuous integration check(s) failed. Please review the failing check's logs and make the necessary changes. https://github.com/monkeytypegame/monkeytype/actions/runs/7615775869

**Comment by Nivaldinho-jpg** [comment]
> > > IDs 82 and 83 have incorrect length fields. Also please resolve merge conflicts.
> > 
> > 
> > The lenght fields have been fixed. I don't know exactly how were the merge conflicts, but I tried to fix it. Let me know if its still not working
> 
> Theres still issues
> 
> image

done I guess

**Comment by monkeytypegeorge** [comment]
Continuous integration check(s) failed. Please review the failing check's logs and make the necessary changes. https://github.com/monkeytypegame/monkeytype/actions/runs/7680704124

**Comment by Miodec** [comment]
Theres still some issues that need to be resolved.

**Comment by monkeytypegeorge** [comment]
Continuous integration check(s) failed. Please review the failing check's logs and make the necessary changes. https://github.com/monkeytypegame/monkeytype/actions/runs/7698757686

**Comment by monkeytypegeorge** [comment]
Continuous integration check(s) failed. Please review the failing check's logs and make the necessary changes. https://github.com/monkeytypegame/monkeytype/actions/runs/7698797810

**Comment by Miodec** [comment]
Thanks

**Comment by Nivaldinho-jpg** [comment]
lets gooooooooo

**Pull request merged**
