### PR TITLE
impr(quotes): add 2 english quotes (D0rkKnight)

### PR DESCRIPTION
**Pull request by D0rkKnight**
### Description

Quote 1: "GLASSY SKY" by Yutaka Yamada. Composed for the anime Tokyo Ghoul Root A.
Quote 2: "On My Own" by Anamanaguchi and HANA.

If there are any suggestions regarding content, syntax, or otherwise, feel free to respond. This is my first commit to this repo and would love to learn more about how things are done around here.

### Checks

- [x] Adding quotes?
  - [ ] Make sure to include translations for the quotes in the description (or another comment) so we can verify their content.
- [ ] Adding a language or a theme?
  - [ ] If is a language, did you edit `_list.json`, `_groups.json` and add `languages.json`?
  - [ ] If is a theme, did you add the theme.css?
    - Also please add a screenshot of the theme, it would be extra awesome if you do so!
- [ ] Check if any open issues are related to this PR; if so, be sure to tag them below.
- [ ] Make sure the PR title follows the Conventional Commits standard. (https://www.conventionalcommits.org for more info)
- [ ] Make sure to include your GitHub username inside parentheses at the end of the PR title

Closes #

### CODE REVIEW

**Comment by Miodec** [comment]
Im not sure if these are really quotable. They seem a bit random.

**Comment by FFUV** [comment]
> Im not sure if these are really quotable. They seem a bit random.

It seems like he wants to get on the contributors' list for attention. His profile looks weird, like he's trying too hard. But I'm not totally sure.

**Comment by D0rkKnight** [comment]
Hey, what's up with the gatekeeping? I just want to contribute to a tool that I personally use from time to time.

Anyhow, I'll close the PR for now and reopen it or a new one if some more quotable quotes come around.

Best
- DK

**Comment by FFUV** [comment]
> Hey, what's up with the gatekeeping? I just want to contribute to a tool that I personally use from time to time.
> 
> Anyhow, feedback noted. I'll close the PR for now and reopen it or a new one if some more quotable quotes come around.
> 
> Best
> 
> * DK

I said im not 100% sure but thanks for the info either way

**Pull request closed without merging**
