### PR TITLE
impr: replace JSONSchema with ajv for faster validation (sanidhyas3s)

### LINKED ISSUE #5102: Replace jsonschema with ajv for faster json validation

### PR DESCRIPTION
**Pull request by sanidhyas3s**
### Description
Replace uses of JSONSchema with ajv for JSON validation, also removed JSONSchema from packages.

Also, locally checked whether this made any improvement, and yes it did.

```
Validation (with ajv): 5.122s
```

```
Validation (with JSONSchema): 16.249s
```

### Checks

- [ ] Adding quotes?
  - [ ] Make sure to include translations for the quotes in the description (or another comment) so we can verify their content.
- [ ] Adding a language or a theme?
  - [ ] If is a language, did you edit `_list.json`, `_groups.json` and add `languages.json`?
  - [ ] If is a theme, did you add the theme.css?
    - Also please add a screenshot of the theme, it would be extra awesome if you do so!
- [x] Check if any open issues are related to this PR; if so, be sure to tag them below.
- [x] Make sure the PR title follows the Conventional Commits standard. (https://www.conventionalcommits.org for more info)
- [x] Make sure to include your GitHub username inside parentheses at the end of the PR title

Closes #5102

### CODE REVIEW

**Comment by Miodec** [comment]
It seems like you didnt add `ajv` as a dev dependency?

**Comment by sanidhyas3s** [comment]
@Miodec Done!

**Comment by sanidhyas3s** [comment]
@Miodec Ready to be merged?

**Comment by Miodec** [comment]
Looks like its erroring out and its not giving any reasons
image

**Comment by sanidhyas3s** [comment]
@Miodec Will check on why this is happening. Also how did you run the script for the above ss? (it worked earlier when I tested it)

**Comment by sanidhyas3s** [comment]
@Miodec Validating fine for me, can you run again and check if it persists?

image

**Comment by Miodec** [comment]
> @Miodec Validating fine for me, can you run again and check if it persists?
> 
> image

Still failing. Using `npm run validate-json`.

**Comment by sanidhyas3s** [comment]
image
Running the tests with `npm run validate-json` also doesn't give any error for me. Maybe verify if you have the correct version of json and code active?

**Comment by Miodec** [comment]
What do you get when running `npm ajv -v` and `node -v`?

**Comment by sanidhyas3s** [comment]
`v18.19.1` and `ajv@6.12.6 invalid: "8.12.0" from the root project` respectively.

**Comment by Miodec** [comment]
Can you hop on Discord? It will be quicker to debug there (also found some other stuff i would like to discuss)

**Comment by sanidhyas3s** [comment]
Ok, just a minute.

**Pull request merged**
