### PR TITLE
Add Tokyo Night theme

### PR DESCRIPTION
**Pull request by Fxzzi**
image
image

### Description

This adds the Tokyo Night theme to the site. Adding the `tokyo_night.css` and adding the respective info to the `_list.json` file also.

### CODE REVIEW

**Comment by monkeytypegeorge** [comment]
Continuous integration check(s) failed. Please review the failing check's logs and make the necessary changes. https://github.com/monkeytypegame/monkeytype/actions/runs/4979688828

**Comment by Miodec** [comment]
Sorry, i dont think the color scheme is unique enough.

**Comment by Fxzzi** [comment]
It's based on the popular [Tokyo Night VSCode theme](https://github.com/enkia/tokyo-night-vscode-theme) and [Neovim colorscheme](https://github.com/folke/tokyonight.nvim).

I think the theme may be popular enough to add like Nord, onedark, catppuccin, etc

**Comment by kunzooz** [comment]
Nah man this would be very useful for lots of people! I agree it's one of the more popular themes unlike many of the existing themes on monkeytype. It is different enogh to warrant an addition imo. Please add!

**Pull request closed without merging**
