### PR TITLE
added 'breeze' and '2077' theme

### PR DESCRIPTION
**Pull request by trevorwrightdev**
### Description

I added a theme called 'breeze,' and another called '2077.'

SCREENSHOTS:
Breeze Theme:
screenshot1
screenshot2
2077 Theme:
image
image

### CODE REVIEW

**Comment by monkeytypegeorge** [comment]
Continuous integration check(s) failed. Please review the failing check's logs and make the necessary changes. https://github.com/monkeytypegame/monkeytype/actions/runs/4277954078

**Comment by trevorwrightdev** [comment]
My bad, should be good now

**Comment by trevorwrightdev** [comment]
I added another theme called '2077.' Here is what it looks like:
image
image

**Comment by Ferotiq** [comment]
Do you have screenshots of the breeze theme?

**Comment by Ferotiq** [comment]
Also in the future, please separate different theme additions into separate pull requests.

**Comment by trevorwrightdev** [comment]
Sounds good, I'll do that next time.  I'll edit the title of this pull request as well.

**Comment by Miodec** [comment]
The 2077 theme is way too bright

**Comment by trevorwrightdev** [comment]
Made the yellow less bright. Let me know if I should just scrap this theme, my goal was to create a bright yellow theme.
image

**Pull request closed without merging**
