### PR TITLE
impr(quotes): add 1 English quote (ProBottler)

### PR DESCRIPTION
**Pull request by ProBottler**
### Description

Added 1 English quote. Source: https://www.fia.com/news/2014-abu-dhabi-grand-prix-thursday-press-conference

### CODE REVIEW

**Comment by monkeytypegeorge** [comment]
Continuous integration check(s) failed. Please review the failing check's logs and make the necessary changes. https://github.com/monkeytypegame/monkeytype/actions/runs/7513633374

**Comment by monkeytypegeorge** [comment]
Continuous integration check(s) failed. Please review the failing check's logs and make the necessary changes. https://github.com/monkeytypegame/monkeytype/actions/runs/7517961371

**Comment by Miodec** [comment]
Please revert all the indentation changes

**Comment by ProBottler** [comment]
> Please revert all the indentation changes

Sorry for asking, but I'm not sure what you means by "indentation" here. I could close this PR and open a new one since the latest file is pretty bodge.

**Comment by Miodec** [comment]
> Sorry for asking, but I'm not sure what you means by "indentation" here. I could close this PR and open a new one since the latest file is pretty bodge.

I mean the diff is massive, indicating you changed something about the indentation (maybe converted spaces to tabs?):
image

You could try opening a new pr yeah

**Pull request closed without merging**
