### PR TITLE
Create quotesfile (esperanto.json)

### PR DESCRIPTION
**Pull request by GwenXt**
Added quotes for Esperanto

### Description

Closes #

### CODE REVIEW

**Review by uMaoow — APPROVED** [review]
seems good

**Comment by Miodec** [comment]
Please comment with the quote translations so i can verify their content.

**Comment by GwenXt** [comment]
I have done a comit to remove a duplicate quote

**Comment by GwenXt** [comment]
Here are the translations : 

Quote 1 : The reader will probably take the brochure now offered in his hands with mistrust, with a previously prepared thought that he will be offered some kind of unrealizable utopia.

Quote 2 : I must therefore first of all ask the reader to put aside this prejudice and to think seriously and critically about the matter proposed.

Quote 3 : The question of an international language has occupied me for a long time; but feeling neither more talented nor more energetic than the authors of all the fruitless attempts, I limited myself for a long time only to dreaming and involuntary meditation on this matter. But some happy ideas that appeared as the fruit of this involuntary meditation encouraged me to continue working and made me try to see if it would not be possible for me to systematically overcome all the barriers to the creation and introduction into the use of a rational international language.

Quote 4 : The Unua Libro is at the same time an introduction to the origin and ideals of the language and a description of its simple grammar (with examples from prose and poetry and an added dictionary of common words).

Quote 5 : Dactylography  (also touchtyping) is writing text by typing, with a machine. A more correct way to type consists in not looking at the keyboard, but only at paper (in the case of a machine) or at the screen (in the case of a computer). There are methods to learn that system, either through direct instruction from a teacher, through a book method, or through an online course or computer program.

Quote 6 : Esperanto Wikipedia is a collaborative encyclopedia project, universal and multilingual, created online according to the wiki principle. It aims to deliver free, objective and verifiable content in Esperanto that anyone can edit

Quote 7 : That the language should be extraordinarily easy, so that you can learn it while playing.

Quote 8 : Young Rikardo almost cried at that terrible realization. He looked around. In the dormitory, he was alone. Apparently, not only his money disappeared, but also Janĉjo.

Quote 9 : Merci, ami !

Quote 10 : Normally I should run off with your money and ticket without telling you anything. But my friendly feelings prevent that, and I want to write you goodbye. I feel obliged to teach you about life. If at the age of 21 you have not yet understood the risks to which you are exposing yourself, someone has to teach you. We met by chance only three days ago. You knew nothing about me. However, you told me all your life and... showed me all your money.

Quote 11 : Slowly, Rikardo turned his head towards the speaker.

Quote 12 : And now he feels inclined to worry about Linda. Isn't that beautiful girl in danger? He loves her, he even loves her a lot, more and more, and the idea that dangerous people could do something to her is hard to live with.

Quote 13 : What should Esperantists do after the war? Istvan Szabolcs tries to shed light on this question in a second point of view article on the subject.


Quote 14 : In the village of Nomen Tuum, an ancient deer fountain is believed to contain healing powers. In certain cases people were healed, but more often they acquired a certain beauty.

Quote 15 : When I entered the main street of the small village, it was completely deserted, except that an old man with the help of a walking stick was walking slowly in the direction of the port and I knew that the villagers would be there where he was going.

Quote 16 : Do you know what kind of ship that is?

Quote 17 : I came to the slope above the harbor.

**Review by uMaoow — APPROVED** [review]

**Comment by Miodec** [comment]
Please remove quotes shorter than 60 characters.

**Comment by GwenXt** [comment]
Done.

I change the last quote to have at least two quotes in the 0-100 characters ranges

Translation : The walls of the harbor itself and the slope above it were covered by groups of the villagers.

**Comment by monkeytypegeorge** [comment]
Continuous integration check(s) failed. Please review the failing check's logs and make the necessary changes. https://github.com/monkeytypegame/monkeytype/actions/runs/5377639145

**Comment by Miodec** [comment]
One of the length fields is incorrect (id 3)

**Pull request merged**
