### PR TITLE
Add an upside down mode to the Funbox

### PR DESCRIPTION
**Pull request by Veemyu**
### Description

This PR adds a new upside-down mode to the Funbox.
As the name says it's basically an extension of the mirror mode.
I wanted to increase my ability to read text upside down and mirrored.
Mirrored was already implemented so the upside-down text mode wasn't too far away.

Screenshot 2023-01-13 at 18 42 43

Screenshot 2023-01-13 at 18 42 59

<!-- pro tip: you can press . (dot or period) in the code tab of any GitHub repo to get access to GitHub's VS Code web editor Enjoy! :)

### CODE REVIEW

**Comment by Veemyu** [comment]
Fun little thing. Sorry for the PR spam I couldn't force push.
And #3914 failed the ci-assets check because the bot wasn't able to access GitHub at that moment.
Welcome back from your Winter break as well :)

**Comment by Miodec** [comment]
I think the `upside_down.css` is missing.

**Comment by Veemyu** [comment]
Thank you, strange that it wasn't tracked. It's in now, as of the latest commit :)

**Comment by Veemyu** [comment]
Very nice.

**Pull request merged**
