### PR TITLE
Strict equality migration

### LINKED ISSUE #4098: Require Strict Equality
Currently, much of the codebase has instances of `==` which is known to be unreliable due to type coercion. Replacing it with `===` and enforcing it with lint will improve the security of the codebase.

Tasks: 
- String Mode2: #4094 
- Backend: #4086

### PR DESCRIPTION
**Pull request by aviiciii**
### Description
This pull request modifies the codebase to replace loose equality (double equals ==) comparisons with strict equality (triple equals ===) comparisons.

Closes #4098 on merge.

### CODE REVIEW

**Comment by aviiciii** [comment]
I checked all of the "==" if they are comparing two variables of same datatype before changing them to "===" and not do a replace all

**Comment by aviiciii** [comment]
do you want to separate the pr into **two** as it will be a large one or do I just do it in this itself?

**Comment by Miodec** [comment]
One is fine

**Comment by monkeytypegeorge** [comment]
Continuous integration check(s) failed. Please review the failing check's logs and make the necessary changes. https://github.com/monkeytypegame/monkeytype/actions/runs/5281046923

**Comment by Miodec** [comment]
Have you done any initial tests? Made sure the website runs?

**Comment by aviiciii** [comment]
yes, i ran it locally using docker and as far as I saw everything worked

**Review by Miodec — APPROVED** [review]

**Pull request merged**
