### PR TITLE
impr(quotes): add english quote

### PR DESCRIPTION
**Pull request by NipulM**
Added English quote by Abraham Lincoln.

### CODE REVIEW

**Comment by Miodec** [comment]
You don't need to close and reopen the pr everytime.

**Comment by NipulM** [comment]
> You don't need to close and reopen the pr everytime.

I'm really sorry.

**Comment by iwmywn** [comment]
this quote is similar to ID 433 @Miodec

**Comment by Miodec** [comment]
Thanks, ill revert. @NipulM please make sure quotes are not a duplicate next time.

**Pull request merged**
