### PR TITLE
impr(quotes): created and added two quotes in chinese_simplified.json (extoplasm)

### PR DESCRIPTION
**Pull request by extoplasm**
### Description

added a quote file for chinese simplified (chinese_simplified.json)
included 2 quotes both from confucious (孔子):
"躬自厚而薄责于人，则远怨矣。“
translates to: blame not others but yourself and you will be free from resentment
"三人行，必有我师焉，择其善者而从之，择其不善者而改之。"
translates to: when three travel together, there must be one who is my teacher; learn from their successes and change their mistakes

### Checks

- [x] Adding quotes?
  - [x] Make sure to include translations for the quotes in the description (or another comment) so we can verify their content.
- [ ] Adding a language or a theme?
  - [ ] If is a language, did you edit `_list.json`, `_groups.json` and add `languages.json`?
  - [ ] If is a theme, did you add the theme.css?
    - Also please add a screenshot of the theme, it would be extra awesome if you do so!
- [x] Check if any open issues are related to this PR; if so, be sure to tag them below.
- [x] Make sure the PR title follows the Conventional Commits standard. (https://www.conventionalcommits.org for more info)
- [x] Make sure to include your GitHub username inside parentheses at the end of the PR title

Closes #

### CODE REVIEW

**Comment by monkeytypegeorge** [comment]
Continuous integration check(s) failed. Please review the failing check's logs and make the necessary changes. https://github.com/monkeytypegame/monkeytype/actions/runs/8825478582

**Comment by Miodec** [comment]
Could you add a few more quotes? It would reduce the repetition

**Comment by extoplasm** [comment]
> Could you add a few more quotes? It would reduce the repetition

yes was planning to, how many more do u think?

**Comment by Miodec** [comment]
Around 20?

**Comment by extoplasm** [comment]
> Around 20?

yea sure i’ll see what i can do, but gotta do it tomorrow not at computer rn

thinking about adding a poem, for new lines is there a special escape character or anything? or should i type it in like one continuous line?

**Comment by Miodec** [comment]
You can add newlines with `\n`, but don't use them too much.

**Comment by extoplasm** [comment]
*added a few more quotes,*
translation of everything:

"躬自厚而薄责于人，则远怨矣。"
blame yourself not others and you will be free from resentment

"三人行，必有我师焉，择其善者而从之，择其不善者而改之。"
when three travel together, one shall be my teacher, learn from their virtues and change their flaws

"知可以战与不可以战者，胜。 "
one who knows whether to fight or not, wins

"知己知彼,百战不殆。"
know yourself and your enemy and you will fear not the result of a hundred battles

"横看成岭侧成峰，远近高低各不同。/n不识庐山真面目，只缘身在此山中。"
viewed horizontally, a ridge, viewed on the side, a peak, with different heights near and far. one cannot know the true shape of mount lu, because one resides within the peaks
(meaning: people have different interpretations of different things)

"乱生于治，怯生于勇，弱生于强。"
chaos is born from governance, timidity is born from courage, weakness is born from strength

"路遥知马力，日久见人心。"
as a distance tests a horse's strength, time reveals a person's character

"十年树木，百年树人。"
it takes ten years to grow a tree, but a hundred to grow a man

"人逢喜事精神爽。"
a happy event gladdens one's spirit

"木已成舟，生米煮成熟饭。"
the wood has already been made into a boat, the rice has already been cooked
(meaning: what's done is done, cannot be changed)

"冰冻三尺，非一日之寒。"
to freeze a lake a metre deep, it takes more than one cold day
(meaning: rome wasn't built in a day)

"千里之行，始于足下。"
a journey of a thousand miles starts with a single step

"小洞不补，大洞吃苦。"
if one does not fix a small hole, it will become a larger one

"凡人不可貌相，海水不可斗量。"
men cannot be judged by looks as seas cannot be measured by the cup

"严家出好儿，严师出高徒。"
a strict family produces fine children, a strict teacher produces fine students

**Comment by monkeytypegeorge** [comment]
Continuous integration check(s) failed. Please review the failing check's logs and make the necessary changes. https://github.com/monkeytypegame/monkeytype/actions/runs/8841806071

**Comment by extoplasm** [comment]
sorry it isn't quite the 20 you asked, but do some more soon

**Comment by Miodec** [comment]
Thanks

**Comment by Jeanot-Zubler** [comment]
I think quote nr. 5 is wrong. You used `/n` instead of `\n`

**Comment by extoplasm** [comment]
yea i saw that, made a new pr yesterday

**Pull request merged**
