### PR TITLE
Shows you leaderboard position in the stats page

### LINKED ISSUE #3096: Display daily leaderboard rank in result summary after completing a test

### PR DESCRIPTION
**Pull request by YummyOreo**
### Description

Adds your leaderboard position in both of the all time leaderboards, and your highest position in the daily leaderboard. It also your wpm under it.

### CODE REVIEW

**Comment by YummyOreo** [comment]
> Sorry for the confusion, #3096 refers to showing daily leaderboard rank after they complete a test (instead of displaying a notification). I'm not sure if we want this.

ok, my mistake

**Comment by Bruception** [comment]
> > Sorry for the confusion, #3096 refers to showing daily leaderboard rank after they complete a test (instead of displaying a notification). I'm not sure if we want this.
> 
> ok, my mistake

Mention this to @Miodec

**Comment by YummyOreo** [comment]
> > > Sorry for the confusion, #3096 refers to showing daily leaderboard rank after they complete a test (instead of displaying a notification). I'm not sure if we want this.
> > 
> > 
> > ok, my mistake
> 
> Mention this to @Miodec

ok

**Comment by YummyOreo** [comment]
Screenshot:
Screenshot 2022-06-21 155657

**Comment by YummyOreo** [comment]
Not needed

**Pull request closed without merging**
