### PR TITLE
impr(quote): add 24 korean quotes (lazy-seal)

### PR DESCRIPTION
**Pull request by lazy-seal**
### Description

While using the quote mode, I realized I keep getting repeating Korean quotes over and over again. And those weren't even good quotes.

Thus, I've added few good Korean quotes I can find. Those are mostly from books and poems of different authors. I've also fixed grammar on some of existing quotes. (I just realized the length of the quote nine should be 54 since I added a space to correct grammar. So please fix that too.

Below is the id and meaning pairs of the quotes I've added.

| id | meaning (in translation) |
| --- | --- |
31 | Have you ever seen a stuffed genius?
32 | Surely, even to you flea, the night must seem long. The night will undoubtedly be lonely.
33 | When I die, bury me under the liquor jar. If I'm lucky, my bottom might leak.
34 | Even from a thief, one can learn following seven things. He works late into the night. If he doesn't finish what he set out to do in one night, he tries again the next night. He feels every action of his coworkers as if they were his own. He risks his life no matter what the reward is. He doesn't cling to valuable items and knows to let it go for a just a few bucks. He withstands pain and suffering; they mean nothing to him. He does his best in what he does and know very well on what he is doing.
35 | Now the two of them will no longer get wet in the rain. Because they will be each other's roofs. Now the two of them will not feel cold. Because they will be warmth for each other. Now the two of them will no longer be lonely. Because they will be companions for each other. Now the two of them may have two bodies, but in front of them, there will be only one life. Now, enter your home. Enter into the days spent together. On this earth, you will forever be happy.
36 | A bell's not a bell 'til you ring it, A song's not a song 'til you sing it, Love in your heart wasn't put there to stay, Love isn't love 'til you give it away!
37 | Be neither too smart nor too foolish. Neither too forward nor too reticent. Neither too arrogant nor too humble. Neither too loud nor too silent. Neither too strong nor too weak. If you're too smart, people will expect too much from you. If you're too foolish, people will try to deceive you. If you're too arrogant, people will see you as difficult, and if you're too humble, people won't respect you. If you talk too much, your words will lack weight, and if you're too silent, nobody will care. If you're too strong, you'll break, and if you're too weak, you'll shatter.
38 | To laugh often and much; to win the respect of intelligent people and the affection of children; to earn the appreciation of honest critics and endure the betrayal of false friends; to appreciate the beauty; to find the best in others; to leave the world a bit better, whether by a healthy child, a garden patch Or a redeemed social condition; to know even one life has breathed easier because you have lived. This is to have succeeded!
39 | None (I skipped it apparently. A mistake)
40 | "I've lived a life filled with shame. I just can't seem to understand the human existence."
41 | Far out in the uncharted backwaters of the unfashionable end of the western spiral arm of the Galaxy lies a small unregarded yellow sun.
42 | "I still hold onto that happy summer when I used to create weather. I remember the childhood days when spraying water from a hose towards the sun in the garden would conjure up marvelous rainbows. When storms arose, for a brief moment, there would appear a beautifully curved, small, boomerang-like rainbow over my head. It was like a miraculous game of uncovering unintended treasures hidden in the garden by someone who lived in this house long before our family moved in. That's how I gifted weather to myself. Now, fearing that the rainbow soaring into the sky like a newborn goddess might lose its strength and fall, I supported her on my shoulders like a young priest, and with my young hands growing weary from the weight of the sprayer, I continued to sprinkle droplets towards the sun."
43 | "Professor Matapi retorted cynically, questioning whether trading weapons at a high price wasn't rather amusing. 'After all, the purpose of a weapon is to kill the opponent, so there's hardly any problem in killing them with a shovel or a pickaxe. On the other hand, the purpose of a musical instrument is to play beautiful music, and a fine instrument produces heavenly melodies. Which trade is more reasonable?' I shrugged and said, 'Good weapons save lives. Good instruments may delight the ears, but they don't save lives. Considering that there's nothing more valuable than life, the former seems more reasonable.' 'Nonsense, Tyl. A proper and healthy attitude towards life is what saves lives, not possessing good weapons. Even if you have good weapons, living recklessly with it seems more dangerous, doesn't it?'"
44 | "Dreams are the darkest of things, yet they possess qualities that are the exact opposite of the night. While the night conceals, hides, and covers, dreams reveal, discover, and unveil, and such qualities of dreams strangely resemble those of the day. However, the nature of dreams, which can only be seen in the darkness and not in the bright daylight, proves, like the stars, that their essence belongs to the night."
45 | "'What is alcohol?' Byung's response puzzled Ryun. 'It's like cold fire. We drink it with the moon in it. Don't you folks have them?'"
46 | "Falling from the sky is one of those things that's hard to cancel midway."
47 | "The darkness of Kiboren, the darkness that washed its body with dew dripping from stiff wooden branches, silently sang a dirge towards the fragrance in the humid darkness, was a child of the night nurtured for an absurdly long time, as the verdant earth, completely rejecting sunlight, covered itself in lushness." (This is supposed to be a poetic description of a forest with a little to no light. It's a beautiful quote in Korean, but I don't think the ChatGPT did justice here.)
48 | "But as the sun dipped into the western horizon, casting its final light upon the world, as the forest began to sing its sunset lament, and crimson rays seeped through the canopy like textured ribbons sliding through the air, as the Dokkebi who had been caressing the beetle suddenly glanced back, flashing a mischievous grin, Keigan felt as if he had slipped back into a time when he could eagerly await the unknown of tomorrow with a joyful heart."
49 | 'Mistake' refers to the unpleasant outcome created by the discrepancy between intention and action. 
50 | "The boy possessed traits that, while not typically classified as virtues, could be considered advantageous in that moment's context. So, Keigan approached the boy and said, 'Are you the only one alive?'"
51 | "In your arrogant twenties, where you come to believe that you won't experience anything for the first time again, ironically, is when most of life's firsts actually happen."
52 | "Love is a lie that only tells the truth."
53 | "When love is suddenly poured into a dry heart, it tends to choke."
54 | "To someone, murder is nothing but a means to alleviate minor inconvenience."
55 | "Why do good things only come when they're not needed?"
56 | "I want to give all of me. I want to have all of you."

Honestly, I know it's a bit too much, but these are really good quotes (in Korean). So please do consider them!
Thanks for taking the time to verify those quotes. I appreciate all efforts made by the moderators and works you guys do. 

### Checks

- [x] Adding quotes?
  - [x] Make sure to include translations for the quotes in the description (or another comment) so we can verify their content.
- [ ] Adding a language or a theme?
  - [ ] If is a language, did you edit `_list.json`, `_groups.json` and add `languages.json`?
  - [ ] If is a theme, did you add the theme.css?
    - Also please add a screenshot of the theme, it would be extra awesome if you do so!
- [ ] Check if any open issues are related to this PR; if so, be sure to tag them below.
- [ ] Make sure the PR title follows the Conventional Commits standard. (https://www.conventionalcommits.org for more info)
- [ ] Make sure to include your GitHub username inside parentheses at the end of the PR title

Closes #

### CODE REVIEW

**Comment by monkeytypegeorge** [comment]
Continuous integration check(s) failed. Please review the failing check's logs and make the necessary changes. https://github.com/monkeytypegame/monkeytype/actions/runs/8890449980

**Comment by monkeytypegeorge** [comment]
Continuous integration check(s) failed. Please review the failing check's logs and make the necessary changes. https://github.com/monkeytypegame/monkeytype/actions/runs/8906094786

**Review by Miodec — APPROVED** [review]

**Comment by monkeytypegeorge** [comment]
Continuous integration check(s) failed. Please review the failing check's logs and make the necessary changes. https://github.com/monkeytypegame/monkeytype/actions/runs/8924317400

**Comment by Miodec** [comment]
Please fix length fields

**Pull request closed without merging**
