### PR TITLE
Add "vintage_red" theme + add quotes for 3 languages

### PR DESCRIPTION
**Pull request by SwiftyProgrammer690**
### Description

- I added the "vintage_red" theme I made (screenshots below)
- Added quotes for english
- Added quotes for hindi
- Added quotes for norwegian

### Vintage_Red Screenshots
vintage_red1
vintage_red2
vintage_red3
vintage_red4

### CODE REVIEW

**Comment by rizwanmustafa** [comment]
For future PRs please separate functionalies. One PR for the theme and one for the Qoutes

**Comment by Miodec** [comment]
Quotes are okay, but i dont think i will accept the theme - we already have too many.

**Comment by SwiftyProgrammer690** [comment]
> Quotes are okay, but i dont think i will accept the theme - we already have too many. Please remove.

Yep! Done!

**Comment by SwiftyProgrammer690** [comment]
> For future PRs please separate functionalies. One PR for the theme and one for the Qoutes

I'll keep that in mind next time!

**Review by Miodec — APPROVED** [review]

**Pull request merged**
