### PR TITLE
fix(language): typos in russian 10k (kae)

### PR DESCRIPTION
**Pull request by kae**
- fixed typos
- removed duplicates

### CODE REVIEW

**Comment by monkeytypegeorge** [comment]
Continuous integration check(s) failed. Please review the failing check's logs and make the necessary changes. https://github.com/monkeytypegame/monkeytype/actions/runs/7774644760

**Comment by Miodec** [comment]
Thanks

**Comment by shynekomaid** [comment]
Put it back the way it was, I'm sick of drag to 'ё', or make it an option.

**Comment by penguin-teal** [comment]
@shynekomaid it seems like that is what "lazy mode" does

**Pull request merged**
