### PR TITLE
Changes in the profile

### PR DESCRIPTION
**Pull request by guijun13**
### Description

* In the 'Edit profile' popup:
  - Change the Github and Twitter input positions, to match the same position in the profile page.
  - Add static Github and Twitter URL before their inputs ("prevents" user insert the whole URL, causing nesting URL errors such as `https://github.com/https://github.com/<username>`)

| Before | After |
| --------------- | --------------- |
| image | image |

  - Idea: Add a regex similar to the website input to extract the username from Github and Twitter input URL. What do you guys think?

### CODE REVIEW

**Comment by Miodec** [comment]
Looks like the github and twitter input fields are taller than usual. Please change. Also please add a bit of spacing between the static URL and the input field.

**Comment by Bruception** [comment]
I think a simpler solution is to rename the input label to: "github username, twitter username"

**Comment by Miodec** [comment]
> I think a simpler solution is to rename the input label to: "github username, twitter username"

True, but I guess with this PR there is absolute no second guessing

**Review by Miodec — APPROVED** [review]
Thanks

**Pull request merged**
