### PR TITLE
fix(language): Update turkish_5k.json (myakinx)

### PR DESCRIPTION
**Pull request by myakinx**
Changed Words: 
“mahallesi” to “mahalle”
“standı” to “stand “
“tahminler” to “tahmin”
“dinle” to “dinlemek”
“kısaltmalar” to “kısaltma”
“aminoasit” to “amino asit”
“fotojeni” to "fotojenik”
“onanması” to “onanma“
“prospektüsü” to “prospektüs”
“molekülü” to “moleküllü”
“işareti” to “işaret”
“süblimasyon” to “süblimleşme”
“aralığı” to “aralık”
“yakalandı” to “yakalanmak”

“jonglör” removed because it was not included in the Turkish Dictionary. 
“kyanit”  removed because it was not included in the Turkish Dictionary.

“sıralarında” must be “sıra” but it already exists, removed
“geçmişi” must be “geçmiş” but it already exists, removed
“toplamı” must be “toplam” but it already exists, removed
“vardır” must be “var” but it already exists, removed
“düştü” must be “düşmek” but it already exists, removed
“numarası” must be “numara” but it already exists, removed
“geldi” must be “gelmek” but it already exists, removed

Summary : correcting some words according to Turkish Dictionary and deleting some words that are not in Turkish Dictionary, some of the correted words were already included so the duplicates are removed.

Words are corrected according to Türk Dil Kurumu(TDK)
Türk Dil Kurumu(TDK) = Turkish Language Society

### CODE REVIEW

**Review by Miodec — DISMISSED** [review]
Thanks

**Comment by monkeytypegeorge** [comment]
Continuous integration check(s) failed. Please review the failing check's logs and make the necessary changes. https://github.com/monkeytypegame/monkeytype/actions/runs/8001482772

**Comment by Miodec** [comment]
Please remove a comma from the last list element.

**Comment by myakinx** [comment]
I removed the comma.

**Comment by monkeytypegeorge** [comment]
Continuous integration check(s) failed. Please review the failing check's logs and make the necessary changes. https://github.com/monkeytypegame/monkeytype/actions/runs/8006052726

**Comment by Miodec** [comment]
Thanks

**Pull request merged**
