### PR TITLE
feat(languages): added medical terms (aarnav593)

### PR DESCRIPTION
**Pull request by aarnav593**
### Description

Added English medical terms as a language, "english medical". 
### Checks

- [x] Adding a language or a theme?
    - [x] If is a language, did you edit `_list.json`, `_groups.json` and add `languages.json`?
    - [x] If is a theme, did you add the theme.css?
        - Also please add a screenshot of the theme, it would be extra awesome if you do so!
- [x] Check if any open issues are related to this PR; if so, be sure to tag them below.
- [x] Make sure to include your GitHub username inside round brackets at the end of the PR title
- [x] Make sure the PR title follows the Conventional Commits standard. (https://www.conventionalcommits.org for more info)

Closes #

### CODE REVIEW

**Comment by monkeytypegeorge** [comment]
Continuous integration check(s) failed. Please review the failing check's logs and make the necessary changes. https://github.com/monkeytypegame/monkeytype/actions/runs/7136459031

**Comment by Miodec** [comment]
I think this is a bit too specific to add to the website? Im not sure anyone will use it. I would just direct you to use custom mode.

**Comment by Miodec** [comment]
Ok fine, but i will ask you to add a bit more words.

**Comment by monkeytypegeorge** [comment]
Continuous integration check(s) failed. Please review the failing check's logs and make the necessary changes. https://github.com/monkeytypegame/monkeytype/actions/runs/7172730114

**Comment by monkeytypegeorge** [comment]
Continuous integration check(s) failed. Please review the failing check's logs and make the necessary changes. https://github.com/monkeytypegame/monkeytype/actions/runs/7172855387

**Comment by monkeytypegeorge** [comment]
Continuous integration check(s) failed. Please review the failing check's logs and make the necessary changes. https://github.com/monkeytypegame/monkeytype/actions/runs/7173083524

**Comment by monkeytypegeorge** [comment]
Continuous integration check(s) failed. Please review the failing check's logs and make the necessary changes. https://github.com/monkeytypegame/monkeytype/actions/runs/7176178582

**Comment by aarnav593** [comment]
@Miodec 

Is 500 words enough? I have added an additional 300 to the original 200 words.

**Comment by Miodec** [comment]
How about we aim for a 1000?

**Comment by monkeytypegeorge** [comment]
Continuous integration check(s) failed. Please review the failing check's logs and make the necessary changes. https://github.com/monkeytypegame/monkeytype/actions/runs/7326111271

**Comment by monkeytypegeorge** [comment]
Continuous integration check(s) failed. Please review the failing check's logs and make the necessary changes. https://github.com/monkeytypegame/monkeytype/actions/runs/7326264555

**Comment by monkeytypegeorge** [comment]
Continuous integration check(s) failed. Please review the failing check's logs and make the necessary changes. https://github.com/monkeytypegame/monkeytype/actions/runs/7331035727

**Comment by ebblies** [comment]
adding this would be great.

**Comment by aarnav593** [comment]
> adding this would be great.

@ebblies 

i’m working on it and i’ll create another pull request when im finished

**Pull request closed without merging**
