### PR TITLE
add new theme: dark note

### PR DESCRIPTION
**Pull request by mynimi**
### Creates a new theme
Features
* note overlay
*  Dot animation 
* rounded corners on buttons and the test setup.

image
image

### CODE REVIEW

**Comment by Miodec** [comment]
The typed text animation seems very distracting. Also i keep losing track of the caret, the color could be brighter.

**Comment by mynimi** [comment]
Would you like me to change the way the animation behaves (slow it down or maybe add more delay before it starts) or remove it entirely?

**Comment by Miodec** [comment]
Not sure, up to you

**Comment by mynimi** [comment]
Making the dots more subtle wasn't quite working out. Kept the original idea, but made it a more subtle change. If you feel like it's still too distracting, I'm fine killing it completely.

**Comment by mynimi** [comment]
honestly, I like the dots a lot, but I can see how they may be distracting (I think probably especially for really fast typers). Maybe instead of baking the typing effect into the theme I could make the dots a funbox feature, so people can turn it on or off however they like and can use the theme with or without them? What do you think?

**Comment by Miodec** [comment]
Funboxes are meant to change the experience in some way. Hiding the already typed words doesn't really change much.

**Comment by mynimi** [comment]
gave the dot animation another try. Made the scaling of the text a bit more linear and changed some of the pacing.

**Pull request merged**
