### PR TITLE
impr(quotes): add some french quotes

### PR DESCRIPTION
**Pull request by Augustin68**
Hi, I have just added ~~1240~~ 1227 french quotes :) 

You can find all the translations in the attached markdown file ! (too long to add in commit message)

[PR_message.md](https://github.com/monkeytypegame/monkeytype/files/12801962/PR_message.md)

### CODE REVIEW

**Comment by monkeytypegeorge** [comment]
Continuous integration check(s) failed. Please review the failing check's logs and make the necessary changes. https://github.com/monkeytypegame/monkeytype/actions/runs/6404372570

**Comment by jvondermarck** [comment]
Really good PR, I can't wait it to be merge ! weee weee 🎉

**Comment by Miodec** [comment]
> Added *some* french quotes

https://media.tenor.com/FTLcK5Rm_YsAAAAC/good-luck-its-okay.gif

> added 1240 quotes

https://media.tenor.com/v39NutxlUMwAAAAd/what-is-that-what-is-happening.gif

**Comment by Miodec** [comment]
> I have tried to remove as much adult content as I found. If you find some more can you provide me the keyword you searched with or the id of the quotes ?

image

**Pull request closed without merging**
