### PR TITLE
Create azerbaijani.json

### PR DESCRIPTION
**Pull request by ajafov98**
### Description

Created quotes file for Azerbaijani language and  added some quotes

### CODE REVIEW

**Comment by monkeytypegeorge** [comment]
Continuous integration check(s) failed. Please review the failing check's logs and make the necessary changes. https://github.com/monkeytypegame/monkeytype/actions/runs/4063524433

**Review by Miodec — DISMISSED** [review]

**Comment by Miodec** [comment]
Quote lengths are incorrect, please fix.

**Comment by monkeytypegeorge** [comment]
Continuous integration check(s) failed. Please review the failing check's logs and make the necessary changes. https://github.com/monkeytypegame/monkeytype/actions/runs/4064881947

**Comment by Miodec** [comment]
Also, could you give rough translations of the quotes? Want to make sure the content is pg13

**Comment by Miodec** [comment]
Closing due to inactivity.

**Pull request closed without merging**
