### PR TITLE
Language turkish 5k edit

### PR DESCRIPTION
**Pull request by s3rdarb**
minor updates and typos

### CODE REVIEW

**Comment by Miodec** [comment]
Please resolve conflicts.

**Comment by monkeytypegeorge** [comment]
Continuous integration check(s) failed. Please review the failing check's logs and make the necessary changes. https://github.com/monkeytypegame/monkeytype/actions/runs/4979007276

**Comment by monkeytypegeorge** [comment]
Continuous integration check(s) failed. Please review the failing check's logs and make the necessary changes. https://github.com/monkeytypegame/monkeytype/actions/runs/4979147591

**Comment by s3rdarb** [comment]
> Please resolve conflicts.

conflicts resolved. 
CI assets fail but I do not know why.

**Pull request merged**
