### PR TITLE
refactor(build): Optimized Dockerfiles (@ilolm)

### PR DESCRIPTION
**Pull request by ilolm**
### Description

Optimized frontend Dockerfile and backend Dockerfile. Reduced layers amount, reduce size of the image.

### Closes #

 Optimizes the output docker image and it's size.

### CODE REVIEW

**Comment by ilolm** [comment]
This should work now, everything compiles good on me. It turned out that copying directories works differently under the hood in Dockerfile.

**Comment by ilolm** [comment]
This should work now, everything compiles as expected on me.

**Comment by fehmer** [comment]
Backend image reduction is 3MB and one less layer, frontend size/layers is not reduced.

**Review by fehmer — APPROVED** [review]

**Comment by Miodec** [comment]
Thanks guys

**Pull request merged**
