### PR TITLE
impr(quotes): add English quotes

### PR DESCRIPTION
**Pull request by iwmywn**

### CODE REVIEW

**Comment by Miodec** [comment]
Did you really just add 1000 quotes?

**Comment by iwmywn** [comment]
I'm pretty careful so the likelihood of a coincidence is almost nil, it's mostly motivational sentences, you can read

**Comment by Miodec** [comment]
Well, the problem is that I really don't want to have to read through 1000 quotes to verify things..

**Comment by iwmywn** [comment]
I dont want to have to open pull requests multiple times, but if you want easier verification then i can break down about 50 quotes at a time.

**Comment by Miodec** [comment]
That could make it more managable

**Pull request closed without merging**
