### PR TITLE
Create egypt.css

### PR DESCRIPTION
**Pull request by TryftzTheDev**
### Description

Closes #

### CODE REVIEW

**Comment by Miodec** [comment]
Please include screenshots

**Comment by TryftzTheDev** [comment]
how do i leave a screenshot and see even the work i did? all i did was copy a file's code with the CSS and changed to red white black (egypt) theme so what can i do to be able to view this theme that i made?

**Comment by TryftzTheDev** [comment]
> Please include screenshots


how do i leave a screenshot and see even the work i did? all i did was copy a file's code with the CSS and changed to red white black (egypt) theme so what can i do to be able to view this theme that i made?

**Review by sambhav1729 — APPROVED** [review]
good

**Comment by Miodec** [comment]
image

Sorry, I don't think this theme is good enough to be added.

**Pull request closed without merging**
