### PR TITLE
impr(themes): added and Created new theme (StickminBruv)

### PR DESCRIPTION
**Pull request by StickminBruv**
### Description

I made a new theme idea called cy red, based off a color someone made. It's my first time doing this stuff on github, so I know I messed up a lot.

image_2024-05-06_184542516

### Checks

- [ ] Adding quotes?
  - [ ] Make sure to include translations for the quotes in the description (or another comment) so we can verify their content.
- [x] Adding a language or a theme?
  - [ ] If is a language, did you edit `_list.json`, `_groups.json` and add `languages.json`?
  - [x] If is a theme, did you add the theme.css?
    - Also please add a screenshot of the theme, it would be extra awesome if you do so!
- [ ] Check if any open issues are related to this PR; if so, be sure to tag them below.
- [x] Make sure the PR title follows the Conventional Commits standard. (https://www.conventionalcommits.org for more info)
- [x] Make sure to include your GitHub username inside parentheses at the end of the PR title

Closes #

### CODE REVIEW

**Comment by cobie8708** [comment]
I believe that in order to follow the conventional commits standards, you must name your pull request "impr(themes): added and Created new theme"

**Comment by Miodec** [comment]
Text color must be close to white/black (can be slightly tinted).
Error color must be clearly visible (right now its very hard to spot).
Missing colors in the _list file (take a look at other themes)

**Comment by monkeytypegeorge** [comment]
Continuous integration check(s) failed. Please review the failing check's logs and make the necessary changes. https://github.com/monkeytypegame/monkeytype/actions/runs/8938281407

**Comment by StickminBruv** [comment]
> Text color must be close to white/black (can be slightly tinted). Error color must be clearly visible (right now its very hard to spot). Missing colors in the _list file (take a look at other themes)

I have now changed the text color, the error color, and the _list file
I believe the error color is still wrong, so correct me if I am really wrong with the error color

**Comment by Miodec** [comment]
Please post some updated screenshots

**Comment by StickminBruv** [comment]
> Please post some updated screenshots

Updated screenshot for,comment

**Comment by Miodec** [comment]
Errors are still not visible.

**Comment by StickminBruv** [comment]
Changed again
Im definitely stuck in an endless loop, but that's alright

**Comment by Miodec** [comment]
Sorry, looks like i broke your pr. If you work on the theme again please make a new PR. Again, sorry.

**Comment by StickminBruv** [comment]
> Sorry, looks like i broke your pr. If you work on the theme again please make a new PR. Again, sorry.

It's alright, I can just very easily copy and paste stuff
Also the comment about red errors in a red theme kinda makes sense now..

**Pull request closed without merging**
