### PR TITLE
impr: add zen_huhn theme (@neinja007)

### PR DESCRIPTION
**Pull request by neinja007**
### Description

Added a new theme called *Zen Huhn*, the title referring to Zen Buddhism. The colors are meant to represent the calm nature of the religion, and its view of enlightenment.

#### Screenshot

image

image

### Checks

- [ ] Adding quotes?
  - [ ] Make sure to include translations for the quotes in the description (or another comment) so we can verify their content.
- [ ] Adding a language or a theme?
  - [ ] If is a language, did you edit `_list.json`, `_groups.json` and add `languages.json`?
  - [ ] If is a theme, did you add the theme.css?
    - Also please add a screenshot of the theme, it would be extra awesome if you do so!
- [ ] Check if any open issues are related to this PR; if so, be sure to tag them below.
- [ ] Make sure the PR title follows the Conventional Commits standard. (https://www.conventionalcommits.org for more info)
- [ ] Make sure to include your GitHub username prefixed with @ inside parentheses at the end of the PR title.

Closes #

### CODE REVIEW

**Comment by neinja007** [comment]
Why does prettier complain?

**Comment by fehmer** [comment]
@neinja007  indentation is wrong on zen_huhn.css, try runnin `npm run pretty-fix`  on project root.

**Comment by neinja007** [comment]
@fehmer thank you very much for this recommendation, will do so.

**Comment by Miodec** [comment]
Sorry, it's too simmilar to `metropolis`.

**Pull request closed without merging**
