### PR TITLE
Added Turkish Quotes

### PR DESCRIPTION
**Pull request by devkennyy**
Added quotes with ID's 61 through to 69.
Language: Turkish

### CODE REVIEW

**Comment by devkennyfr** [comment]
Trailing commas removed!

**Comment by devkennyfr** [comment]
Added:
- wordle.json
- wordle_1k.json

**Comment by Bruception** [comment]
> Added:
> 
> * wordle.json
> * wordle_1k.json

Please keep this PR focused. Add the wordle lists in a separate PR.

**Comment by devkennyy** [comment]
I'm pretty new to whatever this is. I tried creating a new pull request but it said there was already a pull request for 'master'?

**Comment by devkennyy** [comment]
How can I do that @Bruception?

**Comment by Bruception** [comment]
> How can I do that @Bruception?

Create two separate branches on your fork containing the respective changes for each branch. Then merge those branches into the master branch on this repo.

**Comment by devkennyy** [comment]
On it!

**Pull request closed without merging**
