### PR TITLE
feat(layout): Add recurva layout

### PR DESCRIPTION
**Pull request by GalileoBlues**
Please consider adding recurva to monkeytype, I've had a few people ask if it could be added so if it'd be great if that's possible :)

### CODE REVIEW

**Comment by Miodec** [comment]
Any source on this layout? Website? Github repo?

**Comment by monkeytypegeorge** [comment]
Continuous integration check(s) failed. Please review the failing check's logs and make the necessary changes. https://github.com/monkeytypegame/monkeytype/actions/runs/6587283848

**Comment by GalileoBlues** [comment]
> Any source on this layout? Website? Github repo?

I've just updated the repo for Recurva and populated it with the relevant infomation - https://github.com/GalileoBlues/Recurva

**Comment by Miodec** [comment]
Why is this PR closed?

**Pull request closed without merging**
