### PR TITLE
feat(language): add code v (Dlurak)

### PR DESCRIPTION
**Pull request by Dlurak**
### Description

I've added the (programming) language [V](https://vlang.io).

### Checks

- [ ] Adding quotes?
  - [ ] Make sure to include translations for the quotes in the description (or another comment) so we can verify their content.
- [x] Adding a language or a theme?
  - [x] If is a language, did you edit `_list.json`, `_groups.json` and add `languages.json`?
  - [ ] If is a theme, did you add the theme.css?
    - Also please add a screenshot of the theme, it would be extra awesome if you do so!
- [x] Check if any open issues are related to this PR; if so, be sure to tag them below.
- [x] Make sure the PR title follows the Conventional Commits standard. (https://www.conventionalcommits.org for more info)
- [x] Make sure to include your GitHub username inside parentheses at the end of the PR title

### CODE REVIEW

**Comment by monkeytypegeorge** [comment]
Continuous integration check(s) failed. Please review the failing check's logs and make the necessary changes. https://github.com/monkeytypegame/monkeytype/actions/runs/7629507664

**Comment by Dlurak** [comment]
I've addressed and fixed the issue

**Comment by Miodec** [comment]
Is all the keywords that are available? With only 20 words there will be alot of repetition.

**Comment by Dlurak** [comment]
I've just checked the docs, V has 44 keywords and some types which I all added. Also the json file now includes more built in functions.

**Comment by Dlurak** [comment]
Are there any problems left?
This PR still has the "waiting for an update" label

**Review by Miodec — APPROVED** [review]
Thanks

**Comment by Miodec** [comment]
> Are there any problems left? This PR still has the "waiting for an update" label

Yeah sorry, that label relies on me manually toggling it on and off

**Comment by Dlurak** [comment]
> Yeah sorry, that label relies on me manually toggling it on and off

Oh, no problem :)

**Pull request merged**
