### PR TITLE
impr(quotes): add English quotes (@yogiyiorgos)

### PR DESCRIPTION
**Pull request by yogiyiorgos**
### Checks

- [ ] Adding quotes?
  - [ ] Make sure to include translations for the quotes in the description (or another comment) so we can verify their content.
- [ ] Adding a language or a theme?
  - [ ] If is a language, did you edit `_list.json`, `_groups.json` and add `languages.json`?
  - [ ] If is a theme, did you add the theme.css?
    - Also please add a screenshot of the theme, it would be extra awesome if you do so!
- [ ] Check if any open issues are related to this PR; if so, be sure to tag them below.
- [ ] Make sure the PR title follows the Conventional Commits standard. (https://www.conventionalcommits.org for more info)
- [ ] Make sure to include your GitHub username inside parentheses at the end of the PR title

Closes #

### CODE REVIEW

**Comment by yogiyiorgos** [comment]
Made the corrections and pushed the code. Can't figure out whether it has worked though. Excuses I'm a newbie.

**Comment by Miodec** [comment]
I tried merging master into your PR but you didnt check "allow edits by maintainers". Please merge master into your PR.

**Comment by yogiyiorgos** [comment]
I still can't make it work, although I pushed to `master` and the option `Allow edits by maintainers` is ticked.
I will make another attempt with a different quote and document my steps from the beginning.

**Comment by Miodec** [comment]
Closing due to inactivity.

**Pull request closed without merging**
